### ISSUE TITLE
CI4: Bootstrap-table header broken on scroll

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3854] opened 2023-11-03 10:37 UTC
bootstrap-table handles creating the table header and body. The header is pinned during scroll, which is good, but on scroll it breaks causing the formerly non-visible header columns to appear and scrolling to no longer be fixed to the table.

![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/cf54178b-c38e-483c-8b65-05618d3ac345)

You can see below that the header row is decoupled in horizontal scrolling from the table body.  This does not happen when the header is not trying to pin itself.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/d7edd7d1-d659-40bc-9071-32419ded8ba6)

**Comment by objecttothis** [comment] 2023-12-12 07:44
I upgraded the version of bootstrap-table to 1.22.1, but the issue persists.  I was able to duplicate the issue on the bootstrap-table demo page of their website, so this is an issue specific to the StickyHeaders functionality in bootstrap-table. I created an issue in their repo https://github.com/wenzhixin/bootstrap-table/issues/7090

**Comment by jekkos** [comment] 2023-12-12 08:37
Thanks for looking into this @objecttothis ! I wonder if there would be a way to make the table more responsive.

**Comment by objecttothis** [comment] 2023-12-12 10:23
> Thanks for looking into this @objecttothis ! I wonder if there would be a way to make the table more responsive.

It's responsive for large and medium screens but not for small.  It's possible that moving everything to bootstrap 5 will make it easier to make the entire table responsive.  Likely the goal will be to specify how wide the table view is able to get down to and possibly to make the footer sticky on small displays. We may need to replace bootstrap-table if it can't do these things.

I just checked this example on their site (https://examples.bootstrap-table.com/) and it's much more responsive with sticky footers, so it looks like we may be able to make it work... they are using Bootstrap 5 though.

**Comment by jekkos** [comment] 2023-12-20 23:06
I saw some activity in the bootstrap tables project for this one, will check if we can upgrade to the latest commit.

**Comment by jekkos** [comment] 2023-12-29 20:04
I managed to bump the bootstrap table, had to upgrade the travis env to ubuntu jammy and now using a native node installation on that one instead of docker.
I will however try to fix the version to a specific commit hash for bstables  
![Screenshot from 2023-12-29 21-02-28](https://github.com/opensourcepos/opensourcepos/assets/576234/41566361-3f11-4a17-a761-ccebf76a60b6)

**Comment by jekkos** [comment] 2024-01-08 19:10
@objecttothis would the screencap here prove that the issue is fixed?

**Comment by objecttothis** [comment] 2024-01-08 21:10
> @objecttothis would the screencap here prove that the issue is fixed?

The issue wasn't with the table header alignment in it's un-scrolled position. The issue only appears after you scroll past the top of the table and the header goes into "sticky" mode.  Can you confirm that scrolling down so that the header goes into sticky mode does not exhibit the misalignment issue?

**Comment by jekkos** [comment] 2024-01-08 22:27
![image](https://github.com/opensourcepos/opensourcepos/assets/576234/7d78a45d-0c8d-421d-976d-755587311034)

**Comment by jekkos** [comment] 2024-01-08 22:30
The bootstrap tables issue was closed so that is why I thought it was fixed, but indeed, when I resize the window to make the headers sticky then it does not align with the body

**Comment by objecttothis** [comment] 2024-01-08 22:31
> The bootstrap tables issue was closed so that is why I thought it was fixed, but indeed, when I resize the window to make the headers sticky then it does not align with the body

He reopened it right after. I think it was because he had mentioned the issue in a PR that was merged.

**Comment by objecttothis** [comment] 2024-02-06 09:42
The latest release of bootstrap tables is now 1.22.2 and there are some commits since then, but the issue does not seem to have been address so far.  This will be on hold until the issue is resolved in bootstrap tables.

**Comment by objecttothis** [comment] 2024-03-26 21:28
I bumped bootstrap-tables to 1.22.4. Issue persists.

**Comment by objecttothis** [comment] 2024-10-21 14:16
Bumped to 1.23.5 but the issue still persists.

**Comment by objecttothis** [comment] 2024-11-04 09:33
The bootstrap-table dev suggests adding this code will fix the issue but I couldn't get it to work.  Perhaps I was either adding it to the wrong place or the code is running minimized versions of the javascript and ignoring my changes.

I added the code just above the table init code.  I tried manage_tables.js, tabular.php and tabular_details.php but none had an effect on the issue.  Maybe someone else can take a crack at it.

```
const _resetView = BootstrapTable.prototype.resetView

BootstrapTable.prototype.resetView = function (params) {
  _resetView.apply(this, [params])
  setTimeout(() => {
    // only bootstrap3
    this.$tableBody.trigger('scroll')
  }, 100)
}
```

https://github.com/wenzhixin/bootstrap-table/issues/7578#issuecomment-2443040347

**Comment by jekkos** [comment] 2024-11-04 13:34
I believe @BudsieBuds had some bs5 prototype he wanted to show me, curious if that could get us kick started. For the js did you run the gulp install?

**Comment by objecttothis** [comment] 2024-11-04 13:56
> I believe @BudsieBuds had some bs5 prototype he wanted to show me, curious if that could get us kick started. For the js did you run the gulp install?

Yep, 
```
composer install
npm install
npm run build
```

**Comment by BudsieBuds** [comment] 2024-11-05 15:50
> I believe @BudsieBuds had some bs5 prototype he wanted to show me, curious if that could get us kick started. For the js did you run the gulp install?

Yes, I'll make sure to get this to you.

**Comment by jekkos** [comment] 2024-11-28 23:05
A potential solution was posted in https://github.com/wenzhixin/bootstrap-table/issues/7090#issuecomment-2506167603. I tried it out but not sure if it fixes the issue

**Comment by jekkos** [comment] 2024-11-28 23:18
I removed both offsets and looks better now 
![image](https://github.com/user-attachments/assets/b39e3875-ef5f-44c2-ac29-cefefcb1974e)

**Comment by objecttothis** [comment] 2024-11-29 07:02
Super I'd say let's push that and we can close this issue.

**Comment by jekkos** [comment] 2024-11-29 08:02
Should be fixed, will close

**Closed by jekkos** 2024-11-29 08:02 UTC
Labels: bug, pending, CodeIgniter4

**Comment by odiea** [comment] 2024-11-29 09:32
Works great. Thanks
