### ISSUE TITLE
Currency symbol not updating properly in locale config

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2016] opened 2018-06-08 12:08 UTC
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  demo
- OSPOS git commit hash is: demo
- PHP version is:  ??? please!
- MySQL or MariaDB version is:  ??? please!
- OS and version is:  ??? please!
- WebServer is:  well must be apache2 for sure
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i setup currentcy symbol and languaje in the demo site to en-US in Localisation, "$" in currency symbol and English in languaje 

but there-s no change currently symbol are same and show a garbage! Same problem with others languajes, when i set the languaje, only english are set!: 

![ospos-currency1](https://user-images.githubusercontent.com/1571724/41157151-a6a324fe-6af2-11e8-8e71-5fd429faed74.png)

**Comment by jekkos** [comment] 2018-06-11 11:21
You sure this is  a valid locale? Otherwise then this might be an encoding issue.

**Comment by mckaygerhard** [comment] 2018-06-11 12:32
en-EN its not valid but en-US are valid and does not work either

**Comment by WebShells** [comment] 2018-07-14 19:43
@daN4cat it usually needs to submit first time then change it again and resubmit, it will then be saved... I tried to lookout the reason then i got used to it :p

**Comment by mckaygerhard** [comment] 2018-07-16 12:40
well maybe are not user friendly that @WebShells said but are valid, in any case i doit that @WebShells  said @daN4cat and in that time still error happened, i not revised recently

**Comment by jekkos** [comment] 2018-08-15 23:18
@daN4cat I think that currency symbol will be overwritten once a new localisation is selected. It's linked to it. After that it can still be overridden. So I would describe that as 'expected behavior'

**Comment by objecttothis** [comment] 2019-03-12 09:40
@jekkos, both @daN4cat and I can confirm funky behavior with the locale in my testing to try to figure out why  PR #2394 wasn't working correctly.  Is this something that you can look into or is there someone better for it?

**Comment by daN4cat** [comment] 2019-03-12 10:47
@objecttothis it works that if you want something fixed / done you pick up and do it. That's what I've done in the past. Dependencies tend to swamp you as people work on their free time on this project.

**Comment by daN4cat** [comment] 2019-03-12 10:48
I would suggest to make it part of your change with the best behaviour you can come up. We can always improve if somebody feels they have a better idea. Hope you got my point...

**Comment by objecttothis** [comment] 2019-03-12 13:03
> 
> 
> @objecttothis it works that if you want something fixed / done you pick up and do it. That's what I've done in the past. Dependencies tend to swamp you as people work on their free time on this project.

Understood.  I just figured since it was someone else's bug that they would want to fix it.  I'll do it.

**Comment by daN4cat** [comment] 2019-03-12 13:23
I assume this goes to 3.3.0.

**Comment by objecttothis** [comment] 2019-03-13 05:31
> 
> 
> I assume this goes to 3.3.0.

That's fine.  I just wasn't wanting to hold 3.3.0 back any longer than it already has been.

**Comment by objecttothis** [comment] 2019-03-13 05:57
OK, I've confirmed something else in my testing.   "opensourcepos/application/language/Language code definition" lists definitions like de, fr, tr, az, etc and none of those work properly with the locale autofill fixed.  Corresponding xx-YY locales (az-AZ, fr-FR, tr-TR, de-DE, etc) have the correct currency symbol.  I think we need to remove the two-character locales from "opensourcepos/application/language/Language code definition"

**Comment by daN4cat** [comment] 2019-03-13 07:38
If you refer to the txt file, that's old stuff. Yes we use the extended form, it's a standard ISO or something which I can't remember right now.

**Comment by objecttothis** [comment] 2019-03-13 08:07
OK, then I will submit in the pull request to update that documentation. The tooltip next to the locale refers to that so we should keep it up to date.  My PR in #2394 fixes this bug, so once it's merged it should work again.

**Comment by jekkos** [comment] 2019-03-13 09:22
Ok didn't see the discussion here but think it's as I described in the PR. Thanks for taking care of this @objecttothis.

**Comment by objecttothis** [comment] 2019-03-13 09:57
Ok as of #2394 this is fixed and in the master. It will be released with 3.3 0

**Closed by objecttothis** 2019-03-13 09:57 UTC
Labels: bug
