### ISSUE TITLE
Pwa

### ISSUE THREAD

**Issue by arielszy** [opensourcepos/opensourcepos#3543] opened 2022-07-05 16:28 UTC
Also suggest to implement a way to create sales without Internet connection and update when reconnect.

**Comment by jekkos** [comment] 2022-07-05 20:45
duplicate of #2128 . Will close.

**Closed by jekkos** 2022-07-05 20:45 UTC

**Comment by arielszy** [comment] 2022-07-06 19:43
> duplicate of #2128 . Will close.

Not the same. In #2128 is about to offline install but I want to use the online one but without internet like google docs f ex. Or WhatsApp web.
