### ISSUE TITLE
Item Description option to view only and not editable

### ISSUE THREAD

**Issue by nathanzky** [opensourcepos/opensourcepos#2052] opened 2018-07-16 11:16 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.0.21
- MySQL or MariaDB version is: 5.7.18
- OS and version is: RHEL7
- WebServer is: apache
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 7.0.21

### Issue / Bug  / Question / New Feature

The description of item on sales can be edited can this be disable?
![desc](https://user-images.githubusercontent.com/26484936/42755815-b5a72f96-890a-11e8-8b19-b8f9bf2a6878.JPG)

**Comment by mckaygerhard** [comment] 2018-07-16 12:10
interesting, this could be  or not a bug!

can made by yourselft just i guess with F12 see that tag are and set read-only in tag..

**Comment by SteveIreland** [comment] 2018-07-16 12:38
This might have been accidentally introduced with the temporary items change.  I believe the rule is that if the allow alt description flag is set on then this field should be editable.  Or if the item is a temporary item it should also be editable.  If neither is the case then the description should be output only.

I'll test that this week and fix it (unless someone wants to add some new rules)

**Comment by nathanzky** [comment] 2018-07-16 12:56
It works by changing the line to read only..

**Comment by mckaygerhard** [comment] 2018-07-16 13:01
so it must classsified as a bug but also as a feature jajaja, so then let editable or read only in official brand? @odiea ? what do you think @nathanzky ?

**Comment by nathanzky** [comment] 2018-07-16 13:05
I think it should be read only ... others may have a different opinion..

**Comment by WebShells** [comment] 2018-07-16 13:08
Lets not make any changes and keep it as is, alt desc makes it editable... I guess thats the best for the 2 cases.. M

**Comment by mckaygerhard** [comment] 2018-07-16 13:10
umm yeah but an option wolud be great! i dont think so that edit a item will be legal on the final payment but for now its best let it as is

**Comment by odiea** [comment] 2018-07-16 13:15
As I recall I believe it has always been an editable field.

**Comment by odiea** [comment] 2018-07-16 16:47
I was asleep when I answered this. In Items form just uncheck allow alt description.

**Comment by izeblood** [comment] 2018-07-17 08:12
Real programmer never sleep..become they still works in their dreams..hahahaha

**Comment by mckaygerhard** [comment] 2018-07-17 12:05
umm now i understand why i hate programming, i love sleep a little!

**Comment by odiea** [comment] 2018-07-18 11:35
Issue was resolved so I will close it now.

**Closed by odiea** 2018-07-18 11:35 UTC
Labels: question
