### ISSUE TITLE
Barcode with product code-price

### ISSUE THREAD

**Issue by pmuruaga** [opensourcepos/opensourcepos#1586] opened 2017-09-13 03:38 UTC
Is there a way to read a barcode, configure a product with the barcode, that is variable, depending on the weight. It's for a butcher shop each peace of meat has a barcode that has a code of product plus a final price, so I can get the weight to based on the price of the product. Thanks.

**Comment by daN4cat** [comment] 2017-09-13 06:00
Search other issue as it was already discussed.

**Comment by daN4cat** [comment] 2017-09-16 15:57
Duplicate of #1243

**Comment by daN4cat** [comment] 2017-09-16 15:58
Actually it's already implemented, see the ticket I mentioned above.

**Closed by daN4cat** 2017-09-16 15:57 UTC
