### ISSUE TITLE
accents converted "?" when enabled config_category_dropdown for atributes

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3241] opened 2021-07-12 06:12 UTC
### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 392d92
- PHP version is: 7.4.20
- MySQL or MariaDB version is: 10.3.29-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64
- WebServer is: LiteSpeed
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

HELP? i enabled config_category_dropdown (TBD) and i have issues with espanish characters, like SSD SOLID = Disco Sólido ===> Disco S?lido (wrong character)

![imagen](https://user-images.githubusercontent.com/6296036/125239095-29e91b00-e2b6-11eb-82f7-fc62e47ae732.png)

**Comment by jekkos** [comment] 2021-07-21 21:12
Thanks for this bugreport @ekardian .

I have pushed a fix for this on the dev server. Can you check and confirm if the issue is fixed?

**Closed** 2021-07-22 17:02 UTC
Labels: bug

**Comment by ekardian** [comment] 2021-07-23 04:13
@jekkos fixed
