### ISSUE TITLE
Add New/Custom Customer Columns

### ISSUE THREAD

**Issue by pimpurmom08** [opensourcepos/opensourcepos#1193] opened 2017-03-20 16:40 UTC
Hello is there anyway to add custom columns in the "Customers" tab? Such as "Balances", "Birthdates", etc.
I would like to import lists of my customers but i need these kinds of columns and more. Please advise. 
Thank you!

**Comment by SteveIreland** [comment] 2017-03-21 01:41
I believe that @jekkos has plans to introduce a new feature to OSPOS that provides for defining custom properties to primary tables, but I don't know what the planned delivery date is for that.

**Comment by daN4cat** [comment] 2017-03-21 06:59
That's for items not customers.

**Comment by SteveIreland** [comment] 2017-03-23 14:07
Oops ... sorry .... but it does sound like an opportunity!

**Comment by daN4cat** [comment] 2017-03-25 11:48
@SteveIreland we live in a land of opportunities but not the one with (free) "milk and honey"...

**Comment by mckaygerhard** [comment] 2018-05-14 13:00
yes this is same as #1983

**Comment by jekkos** [comment] 2021-04-06 14:55
duplicate of #3118

**Closed by jekkos** 2021-04-06 14:55 UTC
Labels: enhancement, needs owner
