### ISSUE TITLE
Empty Reports in 3.3.0

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2471] opened 2019-06-24 10:13 UTC
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: dbf311
- PHP version is: 7.3.3
- MySQL or MariaDB version is: 5.7.25
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English

### Bug
I've noticed this problem during the entirety of the 3.3.0 development, but I am just now getting to it because I'm not sure if it's just my install or if other people are having the same issue.  I have a 3.2.0 database migrated to 3.3.0 and I'm not able to get any data to show up in any of the reports for any date range.  All reports generate with an empty dataset.  Is anyone else experiencing this issue?  I've even tried creating an item after the migration and selling it but it too does not appear in the report.

**Comment by objecttothis** [comment] 2019-06-24 10:33
Looking at the Query logs and comparing them between each other I can see that the 3.2.0 logs are including two queries per sale ID in the date range given:

`SELECT 'name', 'category', 'quantity_purchased', 'item_location', 'serialnumber', 'description', 'subtotal', 'tax', 'total', 'cost', 'profit', 'discount_percent', 'sale_status'`
`FROM 'ospos_sales_items_temp'`
`WHERE 'sale_id' = '[ID NUMBER]'`

`SELECT 'used', 'earned'`
`FROM 'ospos_sales_reward_points'`
`WHERE 'sale_id' = '[ID NUMBER]'`

Yet these queries are not appearing on the migrated database in 3.3.0.  I'm guessing that the code is finding a null result set from the queries performed on the temp sales tables, so it's not generating any.  @daN4cat I know you had setup all the temporary tables and I think some optimization work has been happening in regards to conversations with @dtomlins.  Do you have any ideas about what is causing this?

**Comment by objecttothis** [comment] 2019-06-24 10:37
As an aside, I don't think this is a problem specific to PHP 7.3.3 because that same PHP install is running the 3.2.0 which is showing reports without problems.  I'd say it had to be something with the migration, but even creating an item after the migration doesn't show any results.

**Comment by odiea** [comment] 2019-06-24 11:19
What is stored in the error log?

**Comment by daN4cat** [comment] 2019-06-24 11:44
Are queries taking a long time to execute? Trying to remove the timeout factor.

**Comment by objecttothis** [comment] 2019-06-24 11:56
> What is stored in the error log?

@odiea the error log is being generated, so I know that it's logging, but no errors are being logged during or after the report generation.

> Are queries taking a long time to execute? Trying to remove the timeout factor.

@daN4cat The queries are very quick and the page loads quickly.  The slowest query is 5/100th of a second.

I'll see if I can eliminate the database migration as a factor by installing a clean database.

**Comment by jekkos** [comment] 2019-07-05 20:48
@objecttothis can you confirm if this is a bug or not? Does it need further investigation?

**Comment by objecttothis** [comment] 2019-07-05 20:55
Yes I need to investigate further.

**Comment by objecttothis** [comment] 2019-07-08 13:27
OK, this is indeed a problem.  I am now working with a fresh install of the latest master available (#79e1cc).

If I install a fresh database, then create and item and sell that Item, the Transaction summary report (and others) show the item sale.

If I then take the same code base and migrate a 3.2.3 database not only are all the reports showing up empty for past data but no new sales of either pre-existing items or new items created show up in any reports.

So, we've narrowed this down to affecting migrated databases only and not new installs which explains why the demo works fine and why a fresh database works fine.  

@opensourcepos/org can someone please migrate their database on the latest master and see if they can duplicate?  In the meantime I'll dig into the logs and the database and see if I can see what is causing no reports to show on migrated databases using the same codeset as a fresh database where it's working.

**Comment by objecttothis** [comment] 2019-07-08 13:29
My testing between the two different databases was on the same FAMP stack, so it shouldn't be an issue with the stack.  I'm guessing that something was changed in the schema between 3.2.3 and 3.3.0 and not accounted for, but that's a very premature guess.

**Comment by objecttothis** [comment] 2019-07-09 10:09
I did find that the detailed employee report seems to work properly on migrated databases.  I just need to get down to the cause of why these other reports aren't working.

**Comment by objecttothis** [comment] 2019-07-09 11:49
Here are a list of the reports that are working properly:
**Graphical**
- Expenses
- Sales Tax (data summary at the bottom displays but graph does not)
- Taxes

**Summary**
- Expenses
- Payments
- Taxes

**Detailed**
- Employees
- Discounts

**Comment by odiea** [comment] 2019-07-09 11:59
@objecttothis If you have a backup sql that you can share I can get it in the Dev room and try it out on my end.

**Comment by objecttothis** [comment] 2019-07-09 12:02
This might warrant its own issue but I figured I'd put it here since it's stopping #2485 from release.
Graphical Payments Report.  When attempting to open the Graphical Payments report I get the following error generated in the log. The diff between the /application/models/reports/Summary_payments.php on 3.2.3 and 3.3.0 is pretty significant.  @daN4cat and @SteveIreland I'm seeing you guys on the commit history for those additions to this report.  Do one of you want to tackle this while I see what's causing these other reports to flat out not work?  I guess step one would be for someone to see if they can generate the same error by running a Graphical Payments Report.

`ERROR - 2019-07-09 15:45:41 --> Query error: Unknown column 'ospos_sales_items.item_location' in `'where clause' - Invalid query: SELECT 'Sales' AS trans_group, (CASE sale_type WHEN 0 THEN 'POS' WHEN `1 THEN 'Invoice' WHEN 4 THEN 'Return' END) AS trans_type, COUNT(sales.sale_id) AS trans_count, `SUM(sumpay_items.trans_amount) AS trans_amount, IFNULL(SUM(sumpay_payments.total_payments), `0) AS trans_payments, IFNULL(SUM(sumpay_payments.total_cash_refund), 0) AS trans_refunded, `SUM(CASE WHEN sumpay_items.trans_amount - IFNULL(sumpay_payments.total_payments, 0) > 0 `THEN sumpay_items.trans_amount - IFNULL(sumpay_payments.total_payments, 0) ELSE 0 END) as `trans_due
`FROM `ospos_sales` AS `sales`
`LEFT OUTER JOIN `ospos_sumpay_items_temp` AS `sumpay_items` ON `sales`.`sale_id` = ``sumpay_items`.`sale_id`
`LEFT OUTER JOIN `ospos_sumpay_payments_temp` AS `sumpay_payments` ON `sales`.`sale_id` = ``sumpay_payments`.`sale_id`
`WHERE `sales`.`sale_status` = 0
`AND DATE(sales.sale_time) BETWEEN '2019-06-10' AND '2019-07-09'
`AND `ospos_sales_items`.`item_location` IS NULL
`AND `sales`.`sale_status` = 0
`AND   (
``sales`.`sale_type` = 0
`OR `sales`.`sale_type` = 1
`OR `sales`.`sale_type` = 4
` )
`GROUP BY `trans_type`
`ERROR - 2019-07-09 15:45:41 --> Severity: error --> Exception: Call to a member function result_array() `on bool /usr/local/www/public_html/pos_empty_reports/application/models/reports/Summary_payments.php 66

**Comment by objecttothis** [comment] 2019-07-09 12:37
> 
> 
> @objecttothis If you have a backup sql that you can share I can get it in the Dev room and try it out on my end.

Are you wanting my 3.2.3 or 3.3.0 version?  I'd only be able to send non-identifying data so as not to break any GDPR laws.  I need to figure out what I can send.

**Comment by odiea** [comment] 2019-07-09 12:45
It sounds to me like the migration is not working well. So a copy of the earliest db that needs to be migrated should be the one I am looking for.

**Comment by odiea** [comment] 2019-07-09 12:46
If not I will search my other computers and try to find my earliest db to migrate for testing.

**Comment by objecttothis** [comment] 2019-07-09 12:48
@odiea I've opened up a private chat in gitter, so go there and I will get the file to you.

**Comment by objecttothis** [comment] 2019-07-09 13:02
Converting attribute type from TEXT to DATETIME yields this error.  This was working in the master so I'll look into it, but I'm guessing it is a matter of something not getting regression tested.

ERROR - 2019-07-09 16:59:31 --> Severity: Warning --> Use of undefined constant DATETIME - assumed 'DATETIME' (this will throw an Error in a future version of PHP) /usr/local/www/public_html/pos_empty_reports/application/models/Attribute.php 308
ERROR - 2019-07-09 16:59:31 --> Severity: error --> Exception: Call to undefined function valid_date() /usr/local/www/public_html/pos_empty_reports/application/models/Attribute.php 277

**Comment by objecttothis** [comment] 2019-07-09 13:04
Yeah, it appears someone changed the constants from DATETIME to DATE but didn't change it everywhere.  I'll submit a pull request.

**Comment by objecttothis** [comment] 2019-07-09 13:19
@jekkos, you removed the valid_datetime() method from the locale_helper in commit 0ae6470 on June 5th, but the reference for it still exist in the Attribute model.  Was this on purpose or an accident?  I just need to know before adding it back in so as not to undo something you were intending.  As it stands now, PHP throws an exception when converting from TEXT to DATE because there is no method.

**Comment by objecttothis** [comment] 2019-07-10 11:18
Progress.  here is the var_dump from the models/reports/Detailed_sales->getData() method which is supposed to populate that multi-dimensional array with all the data from the temp table associated with the parameters given in the Detailed Transaction Report view.

`ERROR` - 2019-07-10 15:13:26 --> <pre class='xdebug-var-dump' dir='ltr'>
`<small>/usr/local/www/public_html/pos_empty_reports/application/controllers/Reports.php:1302:</small>`
`<b>array</b> <i>(size=3)</i>`
`  'summary' <font color='#888a85'>=&gt;</font> `
`    <b>array</b> <i>(size=0)</i>`
`      <i><font color='#888a85'>empty</font></i>`
`  'details' <font color='#888a85'>=&gt;</font> `
`    <b>array</b> <i>(size=0)</i>`
`      <i><font color='#888a85'>empty</font></i>`
`  'rewards' <font color='#888a85'>=&gt;</font> `
`    <b>array</b> <i>(size=0)</i>`
`      <i><font color='#888a85'>empty</font></i>`
`</pre>`

It's empty.  This tells me that either the temp table isn't getting populated properly or the query in the getData() method isn't pulling the data properly.

**Comment by objecttothis** [comment] 2019-07-10 11:36
In 3.2.3 the Query for creating the sales_items_temp table and populating it is almost identical to the current master.  The difference is:
3.2.3
`					MAX(sales_items.discount_percent) AS discount_percent,`
3.3.0
`					MAX(sales_items.discount) AS discount,`
`					sales_items.discount_type AS discount_type,`

This doesn't seem to be enough to cause the temp table to not populate, so now I'm going to look at the getData() method to see why it might not be pulling the data... perhaps the temp table is being dropped before it gets there?

**Comment by objecttothis** [comment] 2019-07-10 12:15
I confirmed for sure that the temp table is being populated properly by doing a var_dump of a select * query after the sales_items_temp table gets populated and it had everything in there.  So either the temp table is getting dropped before getData() queries it (unlikely) or the query in getData() has a problem.

**Comment by objecttothis** [comment] 2019-07-10 12:31
Now I've confirmed that the temp table is NOT getting dropped before getData() gets to it by doing the same select at the beginning of getData() to var_dump all of the data in sales_items_temp and it's all there.  So I've narrowed it down to the getData() method... I need to figure out what about that query is returning an empty result set.  If I were to bet on it, i'd say it has something to do with the attributes related changes.

**Comment by objecttothis** [comment] 2019-07-10 13:02
@daN4cat @jekkos I'm zeroing in on the problem.  Take a look at the difference between the generated URL in the two reports:
3.2.3
http://[domain redacted]/[base directory redacted]/public/reports/detailed_sales/2019-05-10/2019-07-10/sales/

3.3.0
http://[domain redacted]/[base directory redacted]/public/reports/detailed_sales/2019-05-10/2019-07-10/sales//0

in 3.3.0 OSPOS is adding a '/0' to the end of the URL.  If I remove that, the report runs fine.  In both reports I have selected the exact same options (Detailed Transactions->Completed Sales and Returns with the date window you see above).  In the backend, getData is coming up with an empty result set, unless I modify the URL.  Is this potentially an issue with the view generating an incorrect URL?

**Comment by objecttothis** [comment] 2019-07-10 13:13
So it's clear to me that the /0 in the URL is the stock_location.  So this seems to be where our bug is.  When you look at the query generated you get:

`SELECT 'sale_id', MAX(CASE`
`			WHEN sale_type = 0 && sale_status = 0 THEN 'POS'			`
`			WHEN sale_type = 1 && sale_status = 0 THEN 'INV'`
`			WHEN sale_type = 2 && sale_status = 1 THEN 'W/O'`
`			WHEN sale_type = 3 && sale_status = 1 THEN 'Q'`
`			WHEN sale_type = 4 && sale_status = 0 THEN 'RET'`
`			WHEN sale_status = 2 THEN 'CNL'`
`			ELSE ''`
`			END) AS type_code, MAX(sale_status) as sale_status, MAX(sale_date) AS sale_date, SUM(quantity_purchased) AS items_purchased, MAX(employee_name) AS employee_name, MAX(customer_name) AS customer_name, SUM(subtotal) AS subtotal, SUM(tax) AS tax, SUM(total) AS total, SUM(cost) AS cost, SUM(profit) AS profit, MAX(payment_type) AS payment_type, MAX(comment) AS comment`
`FROM 'ospos_sales_items_temp'`
`WHERE 'item_location' = '0'`
`AND 'sale_status' = 0`
`AND   (`
`'sale_type' = 0`
`OR 'sale_type' = 1`
` )`
`GROUP BY 'sale_id'`
`ORDER BY MAX(sale_date) `

Note "'item_location' 0 doesn't exist.  I currently have one stock location with ID of 1 and if I change the /0 in the URL to /1 the report also works.  The problem is that the report should not be appending the stock location at all because there is no place to select all/some stock locations in the Detailed Transaction report generator.  It's only date range and type of sale.

**Comment by odiea** [comment] 2019-07-10 13:54
I must be looking at the wrong Report because this is the view I see from Detailed Transaction Report.
![2019-07-10 07_52_34-Window](https://user-images.githubusercontent.com/10962177/60974772-e7b42a00-a2e7-11e9-9d61-f405532dfa59.png)

**Comment by objecttothis** [comment] 2019-07-10 15:17
Wow.  What OSPOS git hash are you using?  I'm using 79e1cc from the other day.  Here is the report that I'm using.
![Detailed Report](https://user-images.githubusercontent.com/17935339/60980981-8e2f1800-a346-11e9-89dd-4b9612744396.jpg)

Here is the Report Input it gives me
![Report Input](https://user-images.githubusercontent.com/17935339/60981186-e5cd8380-a346-11e9-9249-66293534dfa8.jpg)

This must be why it's sending the wrong information.  My install procedure is pretty straightforward.  I create the directory, then unzip the master zip into the directory as is.  I only change the /config/config.php and config/databases.php and change the permissions on my log directory so that the group can write to it.  

I don't see why others would be getting different behavior.  @jekkos @daN4cat thoughts?

**Comment by objecttothis** [comment] 2019-07-10 15:27
OK, here's some further information.  I have only one stock location from the migration after stock locations was added.  If I add a second stock location, then the Stock Location dropdown appears with a default of "all" and the report works properly.

OK, so here is the bug: 
- If there is only one stock location
- 0 gets sent to the detailed_sales() function in the Reports controller for the $location_id variable 
- This overrides the default value for $location_id from 'all' to '0'

The result is empty reports.  As a workaround, a second stock location can be added, but the fix probably will be just correcting the view so that when it calls detailed_sales that it doesn't send "/0" if there is only one stock location.

As a secondary bug, when there is more than one stock location, the location called "stock" that is used as a default when the stock_location feature was added is not selectable.  It just doesn't appear in the dropdown at all.

**Comment by odiea** [comment] 2019-07-10 15:41
Even the Demo Server shows the stock location.

![2019-07-10 09_39_09-Window](https://user-images.githubusercontent.com/10962177/60983169-bee76100-a2f6-11e9-85d4-eff99ff6e3b1.png)

**Comment by odiea** [comment] 2019-07-10 15:58
The payment type was something I added to the Report.

**Comment by daN4cat** [comment] 2019-07-10 16:13
That's probably why I don't see the problem with my migration because stock location was a later addition.
It's probably something that should be fixed in one of the migration scripts. ???

**Comment by objecttothis** [comment] 2019-07-10 17:23
I looked at the data in stock locations and it all looks correct. This seems to me to be a big in the code, so I don't think it's something that can be fixed in a migration script.  We just need to find the bug in the code.

**Comment by odiea** [comment] 2019-07-10 18:07
Did you find out why you do not have the stock location in views. That's possibly why you are getting your 0 stock location

**Comment by objecttothis** [comment] 2019-07-10 18:27
@odiea yes, please read my post 5 posts up. It explains exactly what the bug is.  It's after hours here so I'll have to look at it tomorrow unless someone wants to find it before then. The view that is calling the detailed_sales function is sending it "0" for the stock location id. The logic needs to get corrected to not send anything if there is only one stock location. The drop-down logic also needs to be changed to show all stock locations when there is more than one stock location.

**Comment by odiea** [comment] 2019-07-10 18:36
I would suggest downloading the current bintray version and see if the stock location drop down shows and works because it is working in the demo showing 5 to 7 locations.

**Comment by objecttothis** [comment] 2019-07-10 18:52
> 
> 
> Even the Demo Server shows the stock location.
> 
> ![2019-07-10 09_39_09-Window](https://user-images.githubusercontent.com/10962177/60983169-bee76100-a2f6-11e9-85d4-eff99ff6e3b1.png)

That's because there is more than one stock location setup on the demo server.  If only one were setup on a migrated database it would break.

**Comment by odiea** [comment] 2019-07-10 19:34
I think I might understand now.

**Comment by objecttothis** [comment] 2019-07-10 20:48
@odiea you don't understand. Even on the current bintray if you add a second stock location it works fine even on the hash I'm using. Trying it with the latest bintray master won't change it unless someone fixed the bug in the code.

**Comment by odiea** [comment] 2019-07-10 21:23
I did finally understand what you were getting at.

**Comment by daN4cat** [comment] 2019-07-11 03:51
I will need to spend some time to read this better, but I wonder if this bug is a specific issue if a specific migration or a more generic one.
With my migrated database I don't seem to reproduce at the moment the issue. Not sure @jekkos can reproduce with his setup, or @steveireland with his?
CI uses the url path as a format to access module/function/param/.... if the param/filter is 0 due to one existing stock location being 0 due to a migration then the problem is not the path but that stock location value.
Again I need to spend more time here to read the issue and try to reproduce to understand more.

**Comment by jekkos** [comment] 2019-07-11 06:25
Thanks @objecttothis for getting to the bottom of this. Still I think it's weird that it's showing empty report as the stock location id should be matching an existing location..

**Comment by objecttothis** [comment] 2019-07-11 06:29
Yes, it is weird.  I will be attempting to find the exact code causing the problem.  I agree that if it's an issue caused by the migration, we need to fix that at the migration level.  If, as I think, it is an issue with the code sending a location_id of zero when there is only one stock location (with migration or without) then that needs to get fixed in the code.  I'll let you know what I find.

**Comment by jekkos** [comment] 2019-07-11 06:31
Just an idea, we have this in the migration

```
CREATE TABLE IF NOT EXISTS `ospos_stock_locations` (
  `location_id` int(11) NOT NULL AUTO_INCREMENT,
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=0;

INSERT INTO `ospos_stock_locations` ( `deleted`, `location_name` ) VALUES ('0', 'stock');

```

So the table if only created if it does not already exist. In that case auto increment is set to 0, while the id is not enforced on the stock location. Could it already have existed for some reason? In that case we need to reset the auto increment counter so that the first record gets id = 0 or force the id insert on the record.

**Comment by objecttothis** [comment] 2019-07-11 06:51
I don't know when the stock location feature was added.  I can say that our one and only stock location is called stock and it's id is 1.  Since we didn't set it up, I'm assuming that is the default name given to the stock location if none existed prior.  Why it didn't give it a stock location of 0 is unclear to me based on the code you have above... I'm guessing the code in the migration above never ran, because the table existed.

**Comment by objecttothis** [comment] 2019-07-11 09:22
In /application/views/reports/date_input.php on line 73 $stock_locations is tested to include it in the dropdown.  a var_dump of that variable with one stock location gives me

`<b>array</b> <i>(size=1)</i>`
`  'all' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'All'</font> <i>(length=3)</i>`

But if I add a second stock location I get the following var_dump
`<b>array</b> <i>(size=2)</i>`
`  'all' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'All'</font> <i>(length=3)</i>`
`  2 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'warehouse'</font> <i>(length=9)</i>`

With only one stock location that variable should be either 'All', 'stock' respectively or just 'stock' which is the name of the only stock location.

With more than one stock location it should be 'All', 'stock', 'location2' or whatever the other locations are named.  So, whatever code is populating the $stock_location variable is causing our problem, both with not all stock locations being visible in the dropdown when more than one stock location is available and in sending 0 when either 'all', nothing or 1 should be sent (1 is the id of the only stock location).

**Comment by dtomlins** [comment] 2019-07-11 09:48
On my migration attempt again, yes, the reports do not work under 3.3, tho they do under 3.2.3.
My migration is all the way from a 2.1  so locations did not exist.
I only have the 1 location for stock.  

It originally created apparently in  database/2.2.2_to_2.3.sql

This maybe could happen where location_id = 0, but unlikely. Enforced by the database.
   _location_id = 0 cannot and should never exist:_

So for longevity, the report code/restriction cannot assume or even expect '0'

Hope that helps some.
Dan



from the mysql 5.7 manual (the 5.5 manual is similar):
> https://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html
> Specifying **NULL or 0** for the AUTO_INCREMENT column
> In all lock modes (0, 1, and 2), if a user specifies NULL or 0 for the AUTO_INCREMENT column in an INSERT, InnoDB treats the row as if the value was not specified and generates a new value for it. 

That's "why".  For proof:
```
CREATE TABLE `ospos_stock_location_test` (   `location_id` int(11) NOT NULL AUTO_INCREMENT,   `location_name` varchar(255) DEFAULT NULL,   `deleted` int(1) NOT NULL
DEFAULT '0',   PRIMARY KEY (`location_id`) ) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
insert into ospos_stock_location_test (0,'testloc',0);
mysql> select * from ospos_stock_location_test;
+-------------+---------------+---------+
| location_id | location_name | deleted |
+-------------+---------------+---------+
|           1 | testloc       |       0 |
+-------------+---------------+---------+
1 row in set (0.00 sec)
```
PS
On another mildly related item (data assumption)   We create our products outside of
ospos, and "insert" them into the ospos_items table with sql.   Another list/report dependancy
seems to require a "dummy" transaction in the ospos_inventory table to be able to find or
report on any items created this way.  It seems a waste to have 60,000 dummy transactions to
search through that are not used otherwise.  I'll modify my code to create them, but it doesn't
make me happy :(

**Comment by objecttothis** [comment] 2019-07-11 09:54
I'm glad someone could duplicate the issue. I think this will be something with the logic in get_allowed_locations(). I'm almost there. I just need a little more time with the code after lunch.

**Comment by SteveIreland** [comment] 2019-07-11 17:33
I tried to play games once with a zero key in an auto increment field (for obvious reasons) and was burned by it.  I don’t think it was permitted by the particular flavor of the database I was using. So I don’t do that anymore.

**Comment by daN4cat** [comment] 2019-07-11 17:48
@dtomlins on the unrelated issue, the filter by transaction date allows people to search which items were changed during a period of time. Now somebody could argue that's not only required and maybe the time filter in items could be disabled and enabled only if required. That will save the join and time filtering latency.

**Comment by dtomlins** [comment] 2019-07-11 18:23
@daN4cat on the unrelated, I agree on the filtering IF required.  I'll look again later (after 3.3 likely).  Looking for transactions within a timeframe is very useful, but looking to receive or edit a product (without the null transaction present) is where I found it.  Or actually couldn't.  That is part of why I stalled upgrading until I could handle all the quirks.  Lots in the new I want, but a bunch of coding to make things work (taxes, rewards, discounting and sale schemes and restrictions I've been using for years against 2.1.x to integrate) and coding against a moving target is much more difficult while trying to operate.

**Comment by odiea** [comment] 2019-07-11 19:04
@daN4cat . I will take responsibility for the Date Time filter in Items. Years ago I was hoping to use ospos in her thrift store. The Items module was more like an Inventory Module and her help would not have been able to add items then print the barcodes as it was. You added the Date Time  filter which was helpful but she noticed other issues like not being able to put tags on sale for date periods. So she never used it.

**Comment by objecttothis** [comment] 2019-07-11 19:07
OK, I finally have gotten to the bottom of the issue... I think.

In the Stock_location model the get_undeleted_all() function is being called by the get_allowed_locations() which is where the "stock" location is now showing up in the query.

`	public function get_undeleted_all($module_id = 'items')
`	{
`		$this->db->from('stock_locations');
`		$this->db->join('permissions AS permissions', 'permissions.location_id = stock_locations.location_id');
`		$this->db->join('grants AS grants', 'grants.permission_id = permissions.permission_id');
`		$this->db->where('person_id', $this->session->userdata('person_id'));
`		$this->db->like('permissions.permission_id', $module_id, 'after');
`	$this->db->where('deleted', 0);

`		return $this->db->get();
`	}
The location stock isn't showing up because in the database in the permissions table the module that is being passed into get_undeleted_all (in this case is "sales") has a location_id of NULL.

I'm not sure I completely understand the permissions table, because there is also a grants table.  The permissions table doesn't seem to be something that can be altered from the application.  Grants, seems to be alterable through the employee interface, but I don't see where to alter the permissions table.  I also don't understand why "sales" is being passed through as the module_id for a stock_location on a report, but I'm sure someone can explain it to me.

Assuming sales is what should be passed through, we need to figure out how the location_id got changed.  On my 3.2.3 database the location_id is NULL for everything except the items_stock permission_id.

**Comment by dtomlins** [comment] 2019-07-11 20:02
@odiea putting items on sale for time periods is one of my to-redo's.  When date specified, the filter in items is great too.  /d

**Comment by objecttothis** [comment] 2019-07-11 20:03
The code above is generating the following SQL:
`SELECT *`
`FROM 'ospos_stock_locations'`
JOIN `ospos_permissions` AS `permissions` ON `permissions`.`location_id` = 'ospos_stock_locations'.'location_id'`
`JOIN 'ospos_grants' AS 'grants' ON 'grants'.'permission_id' = 'permissions'.'permission_id'`
`WHERE 'person_id' = '1'`
`AND  'permissions'.'permission_id' LIKE 'sales%' ESCAPE '!'`
`AND 'deleted' = 0 `

which gives me the data I would expect when I run the query manually... The problem is that when I do a var_dump of the result of get_undeleted_all() it comes up with an empty result!  It's midnight here.  Gotta go to bed.  I'll pick it up again in the morning unless someone else sees the cause before then.

**Comment by objecttothis** [comment] 2019-07-11 20:06
> 
> 
> @odiea putting items on sale for time periods is one of my to-redo's. When date specified, the filter in items is great too. /d

"Stay on target, Porkins.  Stay on target."  Gold star if you guess the movie without looking it up... but seriously, let's keep this thread to the original issue. ;)

**Comment by dtomlins** [comment] 2019-07-11 20:18
@objecttothis Running that query gets me an Empty Set.  

My basically default permissions location_id is NULL except:
  items_  items  2
  items_stock  items 1
  receivings_  receivings 2
  sales_      sales  2

I never had a location_id of 2


ospos_grants seems to be modified by assigning a permission to the office or the home group - IOW which menu it appears on.

**Comment by objecttothis** [comment] 2019-07-12 08:44
OK, sorry, I was looking at the wrong database up above.  

YREKA!!!! The problem is with the data after all.  Ready for my Sherlock Holmes presentation!?

Here is the permissions table on my non-migrated 3.2.3 database
![3 2 3 - One Stock Location](https://user-images.githubusercontent.com/17935339/61112623-51296980-a49d-11e9-8c43-fe83fcdcb2a8.jpg)

Here is the permissions table on my migrated 3.3.0 database
![Migrated - One Stock Location](https://user-images.githubusercontent.com/17935339/61112562-30611400-a49d-11e9-92b4-b3d0a01d8aa5.jpg)

You can see that in both databases sales_stock has a location_id of NULL, but it should be 1.  I haven't determined why the reports don't fail in 3.2.3 but do in 3.3.0, but I can tell you that if I set the location_id for the permission_id sales_stock to 1, reports in 3.3.0 work fine.  Since this was incorrect in 3.2.3 also, like @daN4cat suggested earlier, this was caused during the migration to stock_locations.

in line 8 of /database/2.2.2_to_2.3.sql you can see where "stock" gets inserted into stock_locations with proper values, but there is no insert into permissions at that point because the permissions table wasn't implemented until 2.3.1.

In 2.3_to_2.3.1.sql permissions gets created and then there is an "insert for existing stock locations".  The problem is that this insert is for "items_" . stock_location and there is no inserting of location_ for "sales_" . stock_location.

That insert statement appears in 2.3.1_to_2.3.2.sql with the IGNORE keyword.  This means that if the row already existed, it would not do the insert and the location_id never gets set.

But how could the row already exist, you ask!?  If you go back to line 38 on 2.3_to_2.3.1.sql, BAM! there it is `('sales_stock', 'sales'),` in the original insert after the permissions table was created, and it was created with a null location_id.  That in combination with our IGNORE keyword in 2.3.1_to_2.3.2.sql the value never gets updated from NULL.

thank you, thank you! [bow][bow].  I know, I'm awesome ;p

OK, but in all seriousness, the fix for 3.3.0 and future is a migration script that sets sales_stock and sales_receivings in the permissions table to the location_id of their location_ids in the stock_locations table.

Here is the only problem if we stop there: If we don't correct the bug in the previous migration scripts then if someone uses them but purposely does not migrate to the newest version of the application, they will be stuck with this problem.  If we want to make that an unsupported use of OSPOS, then no problem, we leave the bug in the old migration scripts and just have a new migration script.  If it is a supported use case to upgrade partially then we should both fix the old migration script and write a new migration script to cover people using the current version and people who are doing partial upgrades.

Since I'm not ever going to be doing a partial upgrade, I don't feel strongly about this.  Thoughts?

**Comment by objecttothis** [comment] 2019-07-12 08:51
Either way, I will get started writing the migration code to update the location_id on sales_[location_name] and receivings_[location_name].  It will need to be in the up() method because I need to use php to pull the name of the stock location with location_id = 1 just in case the user changed the name from "stock" to whatever they want.

**Comment by ekardian** [comment] 2019-07-13 06:12
i'm going to test it in a a real store with 2 stock, this sunday, from 3.2.3 - 4f5ad57 to 3.3.0

**Comment by objecttothis** [comment] 2019-07-13 06:53
> i'm going to test it in a a real store with 2 stock, this sunday, from 3.2.3 - 4f5ad57 to 3.3.0

Super.  It should work fine.  With two stock locations, the thing to look for is if, when in the datepicker for reports, the stock location dropdown options should be "All", then the names of each of your stock locations.

**Comment by daN4cat** [comment] 2019-07-20 18:32
I close this because it's fixed.

**Closed by daN4cat** 2019-07-20 18:32 UTC
Labels: bug
