### ISSUE TITLE
Server error when add a New Employee, and when make changes

### ISSUE THREAD

**Issue by julianishaqi** [opensourcepos/opensourcepos#1873] opened 2018-03-02 11:11 UTC
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.1     (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:    5.7.21  (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:  Ubuntu 16.04.4 LTS
- WebServer is: Apache/2.4.18 (     (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature
I have issue when editing/adding new employee, im getting  error: http://pos.juliemoda.com/employees/save/1 500 (Internal Server Error)
This is a whole new installation, i have followed the installation guide  here 
http://www.opensourceposguide.com/guide/gettingstarted/installation

Please advice

**Comment by mckaygerhard** [comment] 2018-03-02 17:52
yo must see logs at the apache winbuntu server in /var/log/apache2/error.log

also prevously enable loggin in application/config/config.php with level 4 and see error log ar the application/log/<date>.php

without those result here nothing to do!

**Comment by mckaygerhard** [comment] 2018-03-02 23:49
ummm seems duplicate of #1876 but those are on guindow, i must review this at night later...

**Comment by julianishaqi** [comment] 2018-03-05 09:15
I  have checked the logs in /var/log/apache2/error.log and couldnt find any errors there.
Enabled the loggin in application config, and tried to add an employee, still nothing in logs..

However, i deleted all ospos_grants keys in the database, and re created them to see that everything turn to work again.

Thanks for the help.

**Closed** 2018-03-05 09:21 UTC

**Comment by mckaygerhard** [comment] 2018-03-05 11:44
@julianishaqi great hear that!, noted its a 3.1.1 but in the 3.2.0 i not found that "import" feature.. maybe its a 3.1.1 problem only yet resolved.

**Comment by mckaygerhard** [comment] 2018-03-05 13:04
hi @julianishaqi the problem of "nothing" at loggin in application/log its due permission, i'll write that in a wiki instalation procedure.. must be writable by the webserver in our case its www-data user

**Comment by julianishaqi** [comment] 2018-03-05 13:11
Thank you for letting me know. I will keep that in mind for the next time. :)
