### ISSUE TITLE
Can't update an attributes after add it 

### ISSUE THREAD

**Issue by ahmed616** [opensourcepos/opensourcepos#2213] opened 2018-10-30 07:19 UTC
### Installation information

- OSPOS version is: 3.3
- OSPOS git commit hash is:  opensourcepos.20181025065633.master.9b6276
- PHP version is: 7.2
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: XAMPP 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue /
when add a new attributes with a drop list type add drop list for once the if i want to update a drop  list this massage appear and can't update again .

![untitled1](https://user-images.githubusercontent.com/44599622/47702185-d37e4000-dc24-11e8-89b7-84b184ac20b9.png)
![untitled](https://user-images.githubusercontent.com/44599622/47702188-d37e4000-dc24-11e8-870b-2ec492a7c0ca.png)

**Comment by jekkos** [comment] 2018-10-30 09:54
Duplicate of #2201

**Closed by jekkos** 2018-10-30 09:54 UTC
Labels: duplicate
