### ISSUE TITLE
Stock location and employee permission issue

### ISSUE THREAD

**Issue by livewirerules** [opensourcepos/opensourcepos#1689] opened 2017-10-23 18:02 UTC
### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Lets say i add 3 new locations as Location 1, Location 2 and Location 3 under the Configuration->stock
So i can add products with seperate quantities for each location. So i create an employee giving only access to that certain location to add new sales for the products in that location

### Actual behaviour
There are few issues in this
 1) I have 3 locations and when i create a new employee and try to give permission to the first location, its not available on the list. It shows only location 2 and location 3. So im unable to assign the employee to the first location

2) When i create an new employee with permission only to sale and location 2 (or any one location) and when he logs in to the sales panel, he is able to search and add products from other locations. 

3) On the sales panel it allows me to change the location through the drop down although i have only permission for one location

### Steps to reproduce the issue
Create new stock locations from the configuration and create a new employee with the sales permissions. Login with the user credentials to check the stock location from the sales panel

**Comment by jekkos** [comment] 2017-10-24 21:58
First I'd like to try and reproduce this one because afaik this should have worked in the past, so could be a regression

**Comment by SteveIreland** [comment] 2017-10-30 22:54
I think sub issue number 1 in this list is probably due to data corruption as a result of one of the issues that were fixed on #1691.  Resolution will require a little database cleanup - probably adding a missing `permission` record.

**Comment by ulingnoha** [comment] 2017-11-01 12:38
This problem only occurs when the name of the stock location contains spaces (eg, stock[space]1). Try with underscore (stock_1) but configuration can not be saved. Try again with a hyphen (stock-1) can be saved and all running normally.

**Comment by odiea** [comment] 2017-11-01 14:33
You will need to download and install the following. The issue was fixed with this version.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20171029075934.master.8b92d1.zip

**Comment by ulingnoha** [comment] 2017-11-02 07:24
yes, my test above uses that version

**Comment by odiea** [comment] 2017-11-02 10:38
I believe stock locations are soft deleted. So you might check your database and see if any of the locations you had issues with are already in the db. Stock locations are unique.

**Comment by ulingnoha** [comment] 2017-11-02 12:44
Thank you, trying to rename stock location again and working normally

**Comment by daN4cat** [comment] 2017-11-02 20:57
So, is it all fine? Shall we close?

**Closed** 2017-11-04 15:20 UTC
