### ISSUE TITLE
GetLock OPSOS Session

### ISSUE THREAD

**Issue by prince90617** [opensourcepos/opensourcepos#2165] opened 2018-09-26 15:10 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

We have faced the issue of server getting hanged by numerous processes of mysql running ‘GET_LOCK’ In OSPOS. 
![img_26092018_185210_0](https://user-images.githubusercontent.com/15924634/46128290-a9fe7d00-c250-11e8-8091-dea29edd33b6.png)

**Comment by mckaygerhard** [comment] 2018-09-26 15:30
its a mysql consecuence.. can be reproducible but at minor scale does not affects..  i recommended to take attention

**Comment by prince90617** [comment] 2018-09-26 15:40
@odiea : this query runs when user trying to logging into the ospos. What it does , It actually creates lock for the session of that user.
Let me add the code snippet

protected function _get_lock($session_id)
	{
		if ($this->_platform === 'mysql')
		{
			$arg = $session_id.($this->_config['match_ip'] ? '_'.$_SERVER['REMOTE_ADDR'] : '');
			if ($this->_db->query("SELECT GET_LOCK('".$arg."', 300) AS ci_session_lock")->row()->ci_session_lock)
			{
				$this->_lock = $arg;
				return TRUE;
			}

			return FALSE;
		}
		elseif ($this->_platform === 'postgre')
		{
			$arg = "hashtext('".$session_id."')".($this->_config['match_ip'] ? ", hashtext('".$_SERVER['REMOTE_ADDR']."')" : '');
			if ($this->_db->simple_query('SELECT pg_advisory_lock('.$arg.')'))
			{
				$this->_lock = $arg;
				return TRUE;
			}

			return FALSE;
		}

		return parent::_get_lock($session_id);
	}

the above code actually runs the get_lock query.

**Comment by odiea** [comment] 2018-09-26 15:59
Thanks for the explanation. If the developers have time to deal with this I am sure they may look into it. It might be helpful to get the installation information filled in and not just the issue.

**Comment by mckaygerhard** [comment] 2018-09-26 16:15
sorry i forgot to put the reference, here: https://mariadb.com/kb/en/library/get_lock/

**Comment by prince90617** [comment] 2018-09-26 16:18
These are the server Details
Apache version: Apache/2.4.29
PHP version: 5.6.30 
MySQL version: 10.1.26-MariaDB

And OPSOS  3.0.2

**Comment by SteveIreland** [comment] 2018-09-26 18:18
How many users do you have using OSPOS at the same time?

**Comment by prince90617** [comment] 2018-09-26 18:20
approx 3 or 4 user

**Comment by SteveIreland** [comment] 2018-09-26 18:51
Do they stay within the same browser tab to do their work or do they have multiple tabs going?

**Comment by odiea** [comment] 2018-09-26 20:33
This is beginning to sound like a CI issue.

**Comment by odiea** [comment] 2018-09-27 11:01
OSPOS uses the Code Igniter framework. When I searched this "protected function _get_lock($session_id)" on the internet there were multiple pages linking CI to this issue.  So this is my assumption.

**Comment by SteveIreland** [comment] 2018-09-27 11:08
It is to maintain the integrity of the transaction. For each transaction the session is locked and at the end of the transaction the session is released

This prevents the user from stepping on himself when running multiple browser tabs since the session is the same for each tab

**Comment by daN4cat** [comment] 2018-09-27 12:27
What is the problem we are trying to solve here, @prince90617 ? Instead of talking solutions, let's talk about the problem you need to solve.

**Comment by SteveIreland** [comment] 2018-09-27 17:58
He reported that "We have faced the issue of server getting hanged by numerous processes of mysql running ‘GET_LOCK’ In OSPOS."

With only 4 users I'm finding it hard to believe that the session lock is the source of the problem.

There must be something else going on that causing a loop.  Have you checked the PHP log and if so is there anything interesting being logged?

**Comment by mckaygerhard** [comment] 2018-09-27 19:27
its a mysql related problem, due too many request by too little packets.. i cannot explain too much but in a google search there's related workarounds

**Comment by daN4cat** [comment] 2018-09-27 20:38
Let's go one step back and focus on the use cases. Why do they need 4 users? What is the business problem they try to solve?

**Comment by SteveIreland** [comment] 2018-09-28 00:45
No no no no .... let's not go there.  :-)

**Comment by odiea** [comment] 2018-10-01 10:54
And who would do this in real Life??

**Comment by prince90617** [comment] 2018-10-01 10:57
if the keyboard is malfunctioning then this is the potential issue.

**Comment by SteveIreland** [comment] 2018-10-01 13:10
I might be wrong, but I don't think that would be something we could fix.  I'm pretty sure all of that takes place within the CodeIgniter domain and the fix would need to be to CodeIgniter.

**Comment by jekkos** [comment] 2018-10-01 14:02
Can be fixed by adding a delay to the jquery suggestion, feel free to make a PR to improve this.

**Comment by SteveIreland** [comment] 2018-10-01 14:13
I be wrong

**Comment by daN4cat** [comment] 2018-10-01 15:38
Buy a new keyboard....

**Closed** 2018-10-01 16:11 UTC
Labels: pending, question

**Comment by mckaygerhard** [comment] 2018-10-01 18:39
2018-10-01 9:10 GMT-04:00 Steve Ireland <notifications@github.com>:

> I might be wrong, but I don't think that would be something we could fix.
> I'm pretty sure all of that takes place within the CodeIgniter domain and
> the fix would need to be to CodeIgniter.
>
that's not at all ! seems its a input related implementation respect to
ospos.. as said by the reporter!
so i think we can introduced a kind of delay
