### ISSUE TITLE
eMail setting

### ISSUE THREAD

**Issue by mfofanagn** [opensourcepos/opensourcepos#2704] opened 2020-01-29 09:31 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is:  5.6.35
- MySQL or MariaDB version is: 5.7.21
- OS and version is:  windows server 2008
- WebServer is: apache 2.4.33
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Good morning

I use ospos 3.3.1 and I would like to setup mailing on sales invoices
I've tried sendMail and smtp without any success
After some researchs about the subject on github site, I got 2 possibles reasons:

 pdf management  issue
 hard coding mail setting in a php file for woraround

Could you guide me to that process ? or do you have any workaround?

Thanks in advance

**Comment by daN4cat** [comment] 2020-01-29 19:44
Duplicate of #2682 ?

**Comment by daN4cat** [comment] 2020-01-29 19:46
Read #2374?

**Closed** 2020-03-06 20:30 UTC
Labels: wontfix
