### ISSUE TITLE
Tax calculation issue after changing Tax percent 

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2889] opened 2020-07-12 21:33 UTC
Hello everyone,

Now I am using OSPOS v3.3.1

I created two sales for demo. The first one was with 5% of VAT with Amount Due ($0.00). I changed the VAT value to 7%, and I did another sale with new VAT percent.

If go back to check the receipt sale # 1, it show me Amount Due ($17.80).

Here is photos to show the problem

https://ibb.co/yYGRS1x

https://ibb.co/WDQfGWQ

**Comment by daN4cat** [comment] 2020-07-13 08:10
There was a problem with VAT calculation in 3.3.1. That's changed with 3.3.2, please test with latest master build.

**Comment by odiea** [comment] 2020-07-13 10:26
The latest Master is 3.3.1. The last Bintray unstable build is defective.

**Comment by jekkos** [comment] 2020-07-16 11:55
@odiea latest master seems fine no? I mean it does not have the issue on the demo anymore. @w002qaa any feedback here?

**Comment by w002qaa** [comment] 2020-07-16 19:43
Hello

Where I can download 3.3.2? 🤔

**Comment by jekkos** [comment] 2020-07-16 21:00
just fetch latest on [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/3.3.2#files).

**Comment by w002qaa** [comment] 2020-07-17 22:13
@jekkos  
I did test v3.3.2 and has the same issue in calculation of tax

**Comment by w002qaa** [comment] 2020-07-18 00:15
Check this link, please

https://drive.google.com/file/d/1_Qia-n1jnVYVmK301uOmSCaB5PqdtpIY/view?usp=sharing

It is video clear for you the problem for you ^_^

**Comment by objecttothis** [comment] 2020-07-20 10:56
@w002qaa The build you are using in the video is 2F00A6 which is a branch that has not been merged with the master and not rebased with the latest master, which means any changes to fix this issue that were made in the master may not reflect in that build.  Please download the latest master in BinTray (currently b65f68) and check to see if the issue still exists.

As a sidenote, this is why we provide a issue template, which you erased when you created this issue.  Knowing what build you are using to replicate the issue is very important.

**Comment by objecttothis** [comment] 2020-07-20 10:58
> 
> 
> just fetch latest on [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/3.3.2#files).

@jekkos I think he took your advice, but didn't know that he should only fetch the latest master.

**Comment by w002qaa** [comment] 2020-07-22 08:45
Hello 
I did fetch(b65f68) and has same issue.

**Comment by objecttothis** [comment] 2020-07-22 10:54
I was able to replicate the issue.  This issue does not happen if "Tax Included" is checked in Office->Configuration->Tax.  It may be an issue in the calculation for the view (views->sales->receipt).

**Comment by objecttothis** [comment] 2020-07-22 11:15
It appears that the data in ospos_sales_taxes is stored correctly.  This must be an issue in the Sales controller where it generates the data for the Receipt view.

**Comment by objecttothis** [comment] 2020-07-22 11:25
After doing more digging it appears that the behavior of the bug is a little more complex.  It appears to be affecting all receipts from before the change in tax percentage.  That tells me that likely the Sale_lib->get totals is calculating the total to send based on an items current tax_percent rather than the tax_percent from that particular row in sales_taxes.

**Comment by objecttothis** [comment] 2020-07-22 11:42
OK, here is where the bug is.  Sales->load_sale_data() calls 

`$tax_details = $this->tax_lib->get_taxes($data['cart']);` 

but get_taxes pulls the information about the current tax rate in the items table 

`$tax_info = $this->CI->Item_taxes->get_info($item['item_id']);`

This information gets sent back and used in the calculation of the amount due and total on the receipt.  What should be happening is that the tax information should be getting pulled not from the current tax rate on that item, but instead from the sales_taxes table where the tax rate at that time was stored.  Most people won't run into this bug because they either have "tax included" checked or they aren't changing the tax percentage of item.  Nonetheless, the business logic needs to get reworked for generating the receipt so that it pulls the tax rate from the sales_taxes row that matches the sale for which the receipt is generated rather than the current number.

**Comment by objecttothis** [comment] 2020-07-22 11:46
I haven't spent as much time around the tax issues @daN4cat or @SteveIreland would either of you be up for giving a go at this one?

**Comment by daN4cat** [comment] 2020-07-22 14:59
I'm sorry but I can't help this time. I haven't touched any code for some months now.

**Comment by objecttothis** [comment] 2020-07-22 17:41
> 
> 
> I'm sorry but I can't help this time. I haven't touched any code for some months now.

Understood.  Sorry that you haven't been able to get your hands dirty in the code.  

My vote is that unless someone wants to address this bug now, that we punt it for 3.4.0 since nothing seems to be in the way of 3.4.0 and this bug is not a common use case.  That and 3.3.2 is 7 months overdue. @jekkos, @opensourcepos/org thoughts?

**Comment by jekkos** [comment] 2020-07-22 22:25
@objecttothis thanks for sorting this one out already. I might want to try and give it a closer look if I find the time before beginning next week. Otherwise postpone and release?

**Comment by jekkos** [comment] 2020-07-22 22:26
@objecttothis If you want you can do the release draft already? Otherwise I'll have a look later on.

**Comment by SteveIreland** [comment] 2020-09-10 15:03
I can take a look at this over the weekend unless someone would prefer to.

**Comment by jekkos** [comment] 2020-10-30 09:54
Was fixed already some time ago so will close

**Closed by jekkos** 2020-10-30 09:54 UTC
Labels: bug
