### ISSUE TITLE
Submit button not working on add new items

### ISSUE THREAD

**Issue by whoami1904** [opensourcepos/opensourcepos#2024] opened 2018-06-12 09:54 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: 
- PHP version is: 5.7
- MySQL or MariaDB version is:  5.7
- OS and version is: Ubuntu 16.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

- I am facing issue about add new items. Now i can not add or update new items and it is not show error. I had fill everything and click submit button but it is still show me table of add new item with information that i filled before. But i can add new item by csv file :)
- This error appearance after i change date and time system on window machine that is open ospos website. I had change again already  but error still there. :(

**Comment by mckaygerhard** [comment] 2018-06-12 11:55
duplication of #2021 puff git are in 3.3.0 and 3.2.2 has still bugs

**Comment by jekkos** [comment] 2018-06-12 12:07
I've submitted a PR, can you check demo once done to see if fixed?

**Comment by mckaygerhard** [comment] 2018-06-12 12:11
@jekkos it's more complicated!~ at demo site add item are working but the add item has really 4 bugs, your pull request i reviewed and does only fix after 3.2.2 release, but the proble are in 3.2.2 release so the fix work only at demo but not at released 3.2.2

**Comment by mckaygerhard** [comment] 2018-06-12 13:51
unless @whoami1904 you are not using barcode seems the PR fixed that problem, i just tested the changes related in comment  https://github.com/opensourcepos/opensourcepos/issues/2021#issuecomment-396588289 and if you are using the barcode this can fix the problem but confirm if you can added a item but not using the barcode, if the item can be added without the barcode usage, the problem can be solved with the fix related

**Comment by mckaygerhard** [comment] 2018-06-13 12:55
@whoami1904 so then was fixed .. its the same as my bug issue reported as https://github.com/opensourcepos/opensourcepos/issues/2021#issuecomment-396588289 only happened at barcode check and now was fixed at commit https://github.com/opensourcepos/opensourcepos/commit/18352d83689dd56def6d0060eedaa3b3dcd3c50b please close this issue now

**Comment by mckaygerhard** [comment] 2018-06-13 13:59
i recheck the code agains 3.3.0 ad 3.2.2  maybe a misctake? what about try bintray binary ?

**Comment by daN4cat** [comment] 2018-06-13 20:21
Close as duplicate of #2021

**Closed by daN4cat** 2018-06-13 20:21 UTC
Labels: duplicate

**Comment by whoami1904** [comment] 2018-06-14 05:03
"application/views/items/form.php" after edited
![form](https://user-images.githubusercontent.com/39585711/41392406-847b0ff4-6fca-11e8-838e-ffd29f9ab534.JPG)

- When i input barcode and click "Submit". Textbox of barcode and item name has only change background to yellow color and not close and save item that i just input.
![add_item_4](https://user-images.githubusercontent.com/39585711/41392479-e3475fa6-6fca-11e8-8038-712111a6ad7e.JPG)

**Comment by daN4cat** [comment] 2018-06-14 05:57
Are you using 3.2.3?  I released it last night.

**Comment by whoami1904** [comment] 2018-06-14 06:36
Sorry, not yet. Let't me try.

**Comment by whoami1904** [comment] 2018-06-14 08:56
It's working. Thanks. Why i had edit "application/views/items/form.php" as you say but it's not working? Or which file do i need to edit?
- Anyway, thank for your support. <3

**Comment by mckaygerhard** [comment] 2018-06-14 13:27
please close the issue then!

**Comment by Sophat11** [comment] 2019-08-24 14:23
> * I discovery one thing, when i add item without barcode, it is success.
> 
> ![add_item_3](https://user-images.githubusercontent.com/39585711/41330156-ddabd344-6efb-11e8-8648-dcb9a256567d.JPG)
> 
> * And not working when i add barcode :(. It is nothing happens when i click "submit"
>   ![add_item_2](https://user-images.githubusercontent.com/39585711/41330171-f7440d26-6efb-11e8-9620-6a0fe7a9f70f.JPG)
> 
> After i edit "application/views/items/form.php" and click "new item" it show as below, background change to dark.
> 
> ![add_item_1](https://user-images.githubusercontent.com/39585711/41329934-b4f8fedc-6efa-11e8-938a-376b7d1fc095.JPG)

i got the same issue, i just replace folder "items" at \application\views\items with the original one. and working.

**Comment by SteveIreland** [comment] 2019-08-25 17:18
@Sophat11 if you are still having an issue please open a new ticket with the information about your configuration and installation.  I just tested your scenario in the latest 3.3 published version in the bintray and could not recreate your issue.  Everything appears to work fine.

**Comment by Sophat11** [comment] 2019-08-26 01:57
@SteveIreland i'm working on 3.2.2 and it's working fine now. thanks,
