### ISSUE TITLE
Summary_Payments Report error

### ISSUE THREAD

**Issue by loneknight16** [opensourcepos/opensourcepos#1896] opened 2018-03-20 08:58 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

Installation information
OSPOS version is: 3.1.1
OSPOS git commit hash is: 4f5ad57
PHP version is: (e.g. 5.5, 5.6, 7.0, 7.1) - 7.0
MySQL or MariaDB version is: (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) - 5.7
OS and version is: (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) - Ubuntu 16.4
WebServer is: (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) - Apache 2.4
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is: (e.g. WAMP, XAMPP) - LAMP

### Issue / Bug  

Hi there

I get this error when running a Summary_Payment report. This used to work but for whatever reason is now throwing this error. Same error remains when not selecting an item location. Any ideas? 

A Database Error Occurred
Error Number: 1054

Unknown column 'ospos_sales_items.item_location' in 'where clause'

SELECT `sales_payments`.`payment_type`, COUNT(sales_payments.sale_id) AS count, SUM(sales_payments.payment_amount) AS payment_amount FROM `ospos_sales_payments` AS `sales_payments` JOIN `ospos_sales` AS `sales` ON `sales`.`sale_id` = `sales_payments`.`sale_id` WHERE `sales`.`sale_time` BETWEEN '2018-03-14 00:00:00' AND '2018-03-20 23:59:59' AND `ospos_sales_items`.`item_location` = '1' AND `sale_status` =0 and `quantity_purchased` >0 GROUP BY `payment_type`

Filename: models/reports/Summary_payments.php

Line Number: 25

**Comment by loneknight16** [comment] 2018-03-20 11:42
note sure if i can combine, one other issue i noticed is the date format reverts back to american even after changing the format to dd/mm/yyyy under configuration.

**Comment by daN4cat** [comment] 2018-03-20 12:20
The database date and time is fixed to one format and has nothing to do with the representation that is localised.

WRT stock location issue it was probably fixed in 3.2.0.

Try the latest from bintray as it's pretty stable and close to be released.

**Comment by daN4cat** [comment] 2018-03-20 20:31
BTW that error means the database table was modified. Have you upgraded and then went back to 3.1.1?

**Comment by loneknight16** [comment] 2018-03-21 10:24
Thanks. I managed to do the date change via reportico. Would have been nice to do that in the OSPOS reporting section.

I'm running version 3.1.1 and dont recall going back to this version. Will try 3.2.0

**Comment by jekkos** [comment] 2018-03-21 23:19
You have to run upgrade scripts one at a time.. I agree it's not the best experience if you're a few version behind but ok, it's what we have currently.

**Comment by loneknight16** [comment] 2018-03-22 01:45
Which script you are referring to? database.sql? Upgrade notes says you dont need to run this from 3.0 onwards.

**Comment by daN4cat** [comment] 2018-03-22 04:54
From 3 you don't need to run any upgrade. But if you started to upgrade your database from older version you need to update up to 3 using scripts.
Your problem points to something like upgrading from  some version 2 or manual change of the database tables.
It cannot be that a table is missing if you have done upgrades properly or you didn't touch the database.

**Comment by loneknight16** [comment] 2018-03-22 05:11
I will screendump the exact error. Sorry it didn't say it was missing, it said the table already exists when I went to import my data from a backup.

**Comment by loneknight16** [comment] 2018-03-24 00:44
ok so I installed  3.2.0 - 4f5ad57 from bintray. I was able to launch the site without having to re-run the database schema - meaning it worked with the older 3.1.1 database. This is a good start however the error still remains as below...

Error Number: 1054

Unknown column 'ospos_sales_items.item_location' in 'where clause'

SELECT `sales_payments`.`payment_type`, COUNT(sales_payments.sale_id) AS count, SUM(sales_payments.payment_amount) AS payment_amount FROM `ospos_sales_payments` AS `sales_payments` JOIN `ospos_sales` AS `sales` ON `sales`.`sale_id` = `sales_payments`.`sale_id` WHERE `sales`.`sale_time` BETWEEN '2018-03-18 00:00:00' AND '2018-03-24 23:59:59' AND `ospos_sales_items`.`item_location` = '1' AND `sale_status` =0 AND ( `sale_type` =0 OR `sale_type` = 1 ) GROUP BY `payment_type`

Filename: models/reports/Summary_payments.php

Line Number: 25



I also noticed a warning... which was there earlier. sockets mod is installed and enabled in php.ini.

A PHP Error was encountered
Severity: Core Warning

Message: PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_sockets.dll' - /usr/lib/php/20151012/php_sockets.dll: cannot open shared object file: No such file or directory

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by odiea** [comment] 2018-03-24 01:14
This only appears to happen when you select a stock location but it works fine when you select all. Happens on both Xampp and lamp servers. A Linux server does not include the Windows .dll files.

**Comment by mckaygerhard** [comment] 2018-03-24 01:29
dll in a linux server? linux don use "dll" (dinamic linkied libraries) linux uses "shared object libraries" with ".so" extensions..

**Comment by mckaygerhard** [comment] 2018-03-24 01:30
commonly in windows work do the same: "_redownload and reinstall and if after restart if dont work call technichs_"

**Comment by odiea** [comment] 2018-03-24 01:59
As usual worthless comments.

**Comment by mckaygerhard** [comment] 2018-03-24 04:05
lest make a study of my comments respect the recent issues, seems your responses are "fill the boxes" wheantime my responses are "do this and this" and user said "thanks" @odiea

**Comment by loneknight16** [comment] 2018-03-24 04:29
Odiea, you are right. Issue only occurs when stock location is select.

**Comment by daN4cat** [comment] 2018-03-24 06:08
@loneknight16 @odiea thanks for the investigation, I'll try to find the time over the weekend to fix this issue.

**Comment by loneknight16** [comment] 2018-03-24 08:39
Thanks daN4cat. 

I've also managed to modify the code slightly to display the dateformat in non-american style for the detailed_sales.php report using DATE_FORMAT. 

Do you have any tips on how I can modify the the getSummaryData(array $inputs) function in this file to show up total credit_card and cash sales? I figured I need to do something similar to the getData(array $inputs) in the Summary_payment module, is it possible to pull up this information in any other easier way? This is the only customisation I need right now, I wont be needing Reportico if I can get this to work. 

Appreciate your time. Thank you

**Comment by odiea** [comment] 2018-03-24 11:25
@daN4cat This probably isn't the way you would do it. After I changed the following line (355) in controller/reports the issue went away. It does not appear that transaction summary depends on stock location.
```
		$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'sale_type' => $sale_type, 'location_id' => $location_id);
		$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'sale_type' => $sale_type, 'location_id' => 'all');
```

**Comment by daN4cat** [comment] 2018-03-24 18:34
Fixed and in master.

@loneknight16 I don't understand your fixation with changing the date and format in the tables.
Again, the format displayed has nothing to do with the format saved in the database.
Change the Locale time format in Store Configuration to set what you want.

**Comment by daN4cat** [comment] 2018-03-24 18:35
@odiea if you could test a bit more that would help so we close even this bug. Thanks for the help in advance.

**Comment by odiea** [comment] 2018-03-24 19:02
This is what i get now after the update. All and locations appear to be working properly.
![2018-03-24 13_00_23-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/37867827-86914472-2f63-11e8-89eb-8b0a798218f9.png)

**Comment by loneknight16** [comment] 2018-03-24 21:47
"Change the Locale time format in Store Configuration to set what you want."

I've done this already and unfortunately this does not change the display format that shows in the report.

**Comment by daN4cat** [comment] 2018-03-24 21:54
@loneknight16 I use the non US one and all looks fine to me. Can you please show a picture where it's not right in the reports?

**Comment by loneknight16** [comment] 2018-03-24 21:58
I don't know what you mean by Non-US but below is the configuration screenshot following the report output.

![image](https://user-images.githubusercontent.com/36788866/37869370-7be128ce-300a-11e8-84d6-00f64f52dacf.png)


![image](https://user-images.githubusercontent.com/36788866/37869386-a2b38cda-300a-11e8-817d-e796055720fb.png)

**Comment by daN4cat** [comment] 2018-03-24 22:10
OK, got what you mean. That's like that because the sorting won't put things in the right order.

Probably there is a means to fix the sorting, but I don't have time to fix that.

That doesn't follow the US format, neither the EU/UK one. It's a way to keep things sorted.

**Comment by loneknight16** [comment] 2018-03-24 22:12
@daN4cat ok no problem. i think i've fixed it for myself by using date_format on the sql query which fetches the data. I think it also sorts it properly. Can you please look at the count issue noted above in case if you've missed my edited post.

**Comment by daN4cat** [comment] 2018-03-24 22:31
I'll check tomorrow the count issue. The db query is returning more than needed, I will need to think about how to avoid that.

**Comment by daN4cat** [comment] 2018-03-24 22:34
And I'll check the date issue too, see if that can be fixed. I might remember something old about the sorting that probably was fixed.

**Comment by daN4cat** [comment] 2018-03-24 22:36
I can see that in Transactions the date is correct, so it's indeed a report issue. I'll fix that.

**Comment by odiea** [comment] 2018-03-24 23:18
@loneknight16 Could any of your modifications be causing this issue? Can you try an unmodified version and see if you get the same results. Don't want @daN4cat chasing his tail.

**Comment by loneknight16** [comment] 2018-03-25 05:50
results above were from the latest build (3.2.0 - 4f5ad57) with no modifications.

**Comment by odiea** [comment] 2018-03-25 11:28
Not as severe as your display is. Thanks

**Comment by daN4cat** [comment] 2018-03-25 11:41
@loneknight16, I've just checked the date story and it's exactly as I remembered. If you click on the sorting arrow you can see that in a format like dd/mm/yyyy it will sort in the wrong way.
You will see something like 01/03/2018, 22/02/2018, 25/02/2018, etc. So it's not right. I'm trying to find a way of sorting properly not changing the database query.
Also the Reports are loading all the data and not paginating like the other tabular views (e.g. Transactions / Takings from sale). That was something that didn't happen and having that would make the sorting work properly as with the current method it sorts only the current page.

Maybe I could print with the correct date but remove the date sorting as that would make more sense.

**Comment by daN4cat** [comment] 2018-03-25 13:01
OK, I fixed the date format in the reports and removed the sorting because as it is at the moment it does not make sense to have it.
One day we need to refactor this part and use server side pagination using the same approach in Transactions view, so we can even support search and date range directly in the report itself skipping the intermediate filter window.
One day not now.

I'll move to Summary payments and fix that issue now.

**Comment by daN4cat** [comment] 2018-03-25 13:46
Sorry but I cannot reproduce the count / total amounts issue with the Summary payments report.

Here what I have tested (details and summary to compare):

![image](https://user-images.githubusercontent.com/636048/37875705-04f284fc-303b-11e8-88b7-d183e5da038e.png)

![image](https://user-images.githubusercontent.com/636048/37875735-3a7631be-303b-11e8-9872-d3597bd43eb5.png)

**Comment by daN4cat** [comment] 2018-03-25 18:59
@odiea do you see any issues with this?

**Comment by odiea** [comment] 2018-03-25 19:30
Only when I go back 30 days.
Takings displays 62 cash sales
Detailed Transaction displays 64 for cash
Summary Payments displays 68 cash transactions

**Comment by odiea** [comment] 2018-03-25 19:36
As far as the Total amount goes summary shows 2036.91 and detailed shows 2036.93

**Comment by daN4cat** [comment] 2018-03-25 20:07
ok, it's probably requiring sales with multiple items. I bet that's the issue.

**Comment by daN4cat** [comment] 2018-03-25 20:46
The fix should do.

However I'm still not sure why we want location in this case because it makes the matter very complicated in my opinion. You care about the payments not the location of the stock.
Anyway, it's counted properly now and the location is checked only on the first item sold in each sale.
Sorry no other solution than that.

**Comment by odiea** [comment] 2018-03-25 21:03
Works great as far as I am concerned.

**Comment by daN4cat** [comment] 2018-03-25 21:04
Good, @loneknight16 please test by I close this for now.

**Closed by daN4cat** 2018-03-25 21:04 UTC
Labels: bug

**Comment by loneknight16** [comment] 2018-03-30 09:34
Perfect! Everything works as expected. Thank you both.
