### ISSUE TITLE
Multiple price list

### ISSUE THREAD

**Issue by pmuruaga** [opensourcepos/opensourcepos#1651] opened 2017-09-28 03:16 UTC
The purpose of the enhancement I would like to see on OSPOS, is that the user can choose different pricelist. So the product must have n prices, for example 3 prices. It can be helpful for a business that for different clients uses different pricelists. So, i.e. Product #1 have a cost of $20 - and have Price 1: $25 - Price 2: $27 - Price 3: $30.
Then the user, on the sale screen can choose to sell using pricelist 1, 2 or 3... Or also on the customer configuration you can choose which is the default pricelist for the customer...
I expect the community to implement it, I would like to help but I am new on OSPOS.

**Comment by daN4cat** [comment] 2017-09-28 06:03
Already discussed, search open and closed issues as this is a duplicate.

**Comment by daN4cat** [comment] 2017-09-28 06:43
Duplicate of #1017

**Comment by izeblood** [comment] 2020-01-07 01:18
> The purpose of the enhancement I would like to see on OSPOS, is that the user can choose different pricelist. So the product must have n prices, for example 3 prices. It can be helpful for a business that for different clients uses different pricelists. So, i.e. Product #1 have a cost of $20 - and have Price 1: $25 - Price 2: $27 - Price 3: $30.
> Then the user, on the sale screen can choose to sell using pricelist 1, 2 or 3... Or also on the customer configuration you can choose which is the default pricelist for the customer...
> I expect the community to implement it, I would like to help but I am new on OSPOS.

As of this moment, you can use multi location in which: Every location has different quantity and prices: ex. stock1, stock2, stock3, It's just my own suggestion and opinion. who knows it can help...

**Comment by daN4cat** [comment] 2020-01-07 08:38
Good idea @izeblood 

I like how people find creative ways to reuse what's implemented to solve new use cases.

**Comment by WebShells** [comment] 2020-04-16 13:15
@izeblood @daN4cat Multi stocks doesnt offer the option to set multi prices, just different quantities can be set... I'll reopen this issue.

**Comment by WebShells** [comment] 2020-04-16 13:23
Duplicate, closed lol !

**Closed by WebShells** 2020-04-16 13:23 UTC
Labels: duplicate
