### ISSUE TITLE
Unknown 403 Forbidden

### ISSUE THREAD

**Issue by netdreamland** [opensourcepos/opensourcepos#2033] opened 2018-06-19 08:41 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.
- OSPOS git commit hash is: 
- PHP version is: 5.6
- MySQL or MariaDB version is: 5.7
- OS and version is: ubuntu 14.04
- WebServer is: Apache 2.2
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I have newly installed the package and set the permission 
my Apache config
<VirtualHost *:88>

        ServerName *
        ServerAdmin webmaster@localhost
        DocumentRoot /opt/openpos/public
        <Directory "/opt/openpos/public">
          Order allow,deny
          Allow from all 
          AllowOverride All
          Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/openpos-error.log
        CustomLog ${APACHE_LOG_DIR}/openpos-access.log combined
</VirtualHost>

When I tried to update the item, it showed the following error in the console. So that I could not update my items.
POST http://{mysite}/items/check_item_number 403 (Forbidden)
When click the link above, it's shown "TRUE"

**Comment by mckaygerhard** [comment] 2018-06-19 13:03
duplicate of #2021 and see #2021 and please close this issue

**Comment by netdreamland** [comment] 2018-06-19 13:07
Thanks, it closed

**Closed** 2018-06-19 13:06 UTC
