### ISSUE TITLE
CSV Item Import Update mode

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1412] opened 2017-07-22 21:39 UTC
### Enhancement

I need to add the capability to import an items CSV file (similar to the ones I used to originally populate the `items` table but this time it's to update prices (or any other attributes).

Primarily it is to add items missing in the original import and to update prices that weren't originally provided or that have changed.

So I'm modifying it to both add and update.  Since the vendors in question do not necessarily provide UPC number for all of the items I'm also modifying it to locate the item by item name (which will most likely be unique if the vendor doesn't provide a UPC code for it).

If it's a change to an existing item it will not update any tax information or stock location quantities.

Also, it will only update fields for which data is being provided.  It cannot be used to clear a field.  If data is not provided for the field the field is left untouched.

When done I will submit it as a pull request and you can choose to merge it or not.

**Comment by SteveIreland** [comment] 2017-07-23 13:24
As I was testing my changes it occurred to me that there is a requirement (which will be addressed in a future change) to identify what prices were changed so that price labels can be reprinted.  For now I'm just going to copy the `items` table to an `items_save` table so that I can run a query to compare price differences.

**Comment by SteveIreland** [comment] 2017-07-24 02:55
I thought I had it nailed, then during testing realized that I needed to make sure that the inventory records are being properly created when an item is being added.  So since a single upload can both add new records and update existing records I need to at least specify the location for the stock items to handle the situation if the row is for a new item.  If a quantity is specified then it should create the stock record with that quantity.  If a quantity is not provided (including zero) then the stock item should be created with a zero quantity.

**Comment by jekkos** [comment] 2017-07-24 09:45
Currently there's no constraint of having unique items per name, so how can you know which one to pick there?
Also you're right on inventory tracking, once an item is updated we  should indeed add records to that table to indicate the quantities changed.
Regarding item change history: I think it would be better to take that back to the drawing table, as right now there is already some sort of 'price and tax history' by copying fields into sales_items and receiving_items.

Adding a item history table should then replace those two as it kind of generalizes the idea. It'll be better to have one single source of truth on past values for the items instead of multiple. So in that case I'd replace these with a fk to this history table, but that would mean that we need to refactor quite a bit

**Comment by SteveIreland** [comment] 2017-07-24 14:06
Regarding your first question, I do not apply the update if there is more than one item with the same name.  I would have liked to have the vendor id (the company that packages the product) on the item file which would increase the changes of a unique item description per name/vendor combination.  But I gots what I gots, so it's a "make do" situation.

I consider the existence of price and taxes on sales_items as a "statement of record" related to the sale.  I don't believe it would be a good idea to remove those from those tables.

Over generalization can be a real performance drag - in addition to making SQL statements significantly more complex to maintain.

**Comment by SteveIreland** [comment] 2017-07-25 15:12
A pull request has been submitted for this enhancement.  No warranties are expressed or implied.  Buyer beware.  :smile:

**Comment by daN4cat** [comment] 2017-07-25 15:36
Do you check the Barcode before checking the name? Barcode is unique so more reliable than a name. Name should be a second choice.

**Comment by daN4cat** [comment] 2017-07-25 15:40
And I agree with jekkos, maintaining a central table with price history would be a better choice so we even avoid the problem of how many with an old price and how many with a new price in stock such any stock check will produce the right value.

**Comment by SteveIreland** [comment] 2017-07-25 15:43
Yes, the barcode is checked first and I use the item name only if I can't find an item with a unique barcode.

**Comment by daN4cat** [comment] 2017-07-25 15:49
Sounds good.

**Comment by daN4cat** [comment] 2017-07-25 15:54
With regards to database tables we need to rationalise a bit things going forward. There are two parts in this story, one is the domain modelling oriented data model mainly around basic notions in OSPOS like item, attribute, person. The other is more a dimensional model used for reporting and historical purposes. At the moment the dimensional model is achieved with temp tables that aggregate data from different sources. We could have that data stored in a table so the performance is better when we move from the now to the historical mode.

**Comment by daN4cat** [comment] 2017-07-25 15:56
However there is some historical data that is used in the "now" like this cost of items. That should stay in the domain model side of things.

**Comment by SteveIreland** [comment] 2017-07-25 15:59
I'm on board with the concept.

**Comment by SteveIreland** [comment] 2017-07-28 13:01
As it is now we have the supplier id on the `item` table which is necessary.  However for pricing updates it seems that I need the vendor id and the vendor part number.  That's necessary because not only is the bar code not always provided by the vendor, but the item name isn't always unique (which was a surprise to me but @jekkos had pointed out earlier).

Now I have already populated the vendor and the vendor part number into the custom fields so I can use that for my own purposes, but since the intent was to make this useful to the wider community it seems to me that it can only be useful if vendor id and vendor part number were made a permanent part of the database.

If the decision is to NOT add the vendor id and vendor part number then what I would publish would only be useful if the barcode/upc field is always populated.  It will only update using the barcode if the barcode is provided. If there isn't a barcode then it will update using a unique item description.  It there are two or more items with the same description then the change will be flagged as an error and ignored.  If there isn't an item  with that description then the item will be added.

Thoughts?

**Comment by daN4cat** [comment] 2017-07-28 21:28
@SteveIreland I would not add vendor id and vendor part (other attributes) because it's better to wait for the generic support for additional attributes.

So I would suggest to proceed without that addition and keep it as custom for your case.
Proceed with your recommendation.

**Comment by SteveIreland** [comment] 2017-07-28 21:47
Will do.   Although when the additional attributes becomes reality I would like to ask that there be a way to add features that can be depend on the existence of the additional attributes .... said another way I would like to see support for 'predefined additional attributes" that cannot be removed without some pain.

**Comment by jekkos** [comment] 2017-07-28 22:15
Yes I have that covered, work is there but not public yet. I need to rebase and fix one more bug but first want a 3.1

**Comment by SteveIreland** [comment] 2017-07-31 17:31
This issue is on hold until #68 is introduced.

**Comment by nenuchand** [comment] 2017-08-13 02:15
Quantities are always getting imported with 0 quantity  and  csv imported  items are not getting displayed in the Items list.  I have checked in the latest branch .

![image](https://user-images.githubusercontent.com/20229260/29245561-60c93668-7ffb-11e7-9021-67ae3ebd3539.png)

**Comment by SteveIreland** [comment] 2017-08-13 02:25
I don't believe the feature for updating items is included in the current master.

Are you referring to a new issue you've found when importing new items using the CSV import feature?

**Comment by SteveIreland** [comment] 2017-08-13 02:34
I just finished retesting it and it added the items as expected and updated the quantities correctly.

If you would like some assistance with this please open up a new issue providing a little more information about your environment and attach  your  CSV import and I'll take a look at it tonight if I'm still up or tomorrow at the latest.

**Comment by nenuchand** [comment] 2017-08-13 11:00
I have raised and issue with details on
https://github.com/jekkos/opensourcepos/issues/1469

**Comment by daN4cat** [comment] 2017-10-07 16:22
@SteveIreland any plan about this improvement?

**Comment by SteveIreland** [comment] 2017-10-08 03:04
Yes.  This is still pending the improved item attribute feature that @jekkos is introducing this release.

However, I did discover that the CSV files provided by my client's supplier were extremely poor quality and there should have been a more thorough impact analysis and a way to be more selective about what was being imported and a way to "undo" the import.  So when I work on this next time I'm planning on taking those lessons into consideration.

**Comment by daN4cat** [comment] 2017-10-14 12:31
Probably #1031 is connected to this.

**Comment by daN4cat** [comment] 2017-10-14 12:32
@SteveIreland shall we keep in 3.2.0 or move to 3.3.0?

**Comment by SteveIreland** [comment] 2017-10-14 12:56
I'm focusing on purchasing at the moment, so yes please .. definitely move it to 3.3.

**Comment by daN4cat** [comment] 2018-12-23 17:40
@SteveIreland what's the status of this? Should we move to 3.4.0?

**Comment by SteveIreland** [comment] 2018-12-24 17:13
Depends on the cutoff.  I'm working the the changes to tax configuration that @jekkos requested so I'm assuming that's more important.   Also, isn't there an open issue related to importing attributes (or has that been resolved)?

My preference would be to defer this to 3.4 since I think it might get a bit complex in order to maintain adequate software package flexibility.  I believe there is another issue where this is being discussed

**Comment by daN4cat** [comment] 2019-06-16 12:37
@SteveIreland, @objecttothis reworked the import of items CSV to include attributes support.
Is there anything more that needs to be done?

Is the update part the missing capability here?

**Comment by objecttothis** [comment] 2019-06-16 14:16
I also reworked the way that stock location quantities get imported.

**Comment by andriux1990** [comment] 2020-04-01 18:26
is there any progress with updating the products with import csv?

**Comment by objecttothis** [comment] 2020-04-01 18:46
The changes are finished and already merged into the master I believe. I don't think it's been released yet.

**Comment by andriux1990** [comment] 2020-04-01 20:00
> The changes are finished and already merged into the master I believe. I don't think it's been released yet.

... how would this be ... would you have to put the product id for it to be updated?

**Comment by objecttothis** [comment] 2020-04-02 12:28
Sorry, I misread your question. I thought you were talking about updating the import so that it didn't error on blank lines or missing fields that were not mandatory.  I understand now that you were asking about the ability to do a product update through csv import. It's a ways off I'm afraid unless someone else wants to implement it. I have some other very important tasks that have increased in urgency due to COVID-19.

**Comment by andriux1990** [comment] 2020-04-02 17:50
I understand, thanks for taking the time.
I have used csv imports lately and they are much better than before.

and everyone be careful with the coronavirus.

**Comment by objecttothis** [comment] 2020-05-06 09:46
@SteveIreland @opensourcepos/org I've been thinking about this a little, and there are a couple of ways that we could implement this.  IMO the most eloquent way to do this would be to add an item_id column to the generated item import csv.  When the parser comes across a row with the item_id filled in, it treats that row like an update.  Any elements in that row that are not empty, it updates with the filled in value.  

We need this to bulk update item attributes, so I don't mind doing legwork, but really want to make sure that we use the best design.  An alternative would be to have an entirely separate item update import in the view, but even that would be dependent on the item_id being specified.  The reason is that if duplicate barcodes are enabled, then you can't assume that the barcode field is unique.  From a database perspective, it isn't guaranteed to be unique either.

Consequently, there is another advantage to the first option, in that it would allow for mixed update/insert csv imports, which wasn't requested, but some may find valuable.

**Comment by objecttothis** [comment] 2020-05-06 10:57
@SteveIreland do you mind if I take this project?  Since the rework of CSV item import, there have been several changes that would have made previous changes.  I just read through the thread and you were the one putting all the work into this and I don't want to negate that, but I'd like to implement it and put the PR there so that it can get in place.  We have a more sudden and heightened need for being able to update an item than we did before since the meta-data we are storing in attributes for each items are now being pushed out through a 3rd party integration to update an eCommerce site.

**Comment by objecttothis** [comment] 2020-05-06 15:50
I've created a draft PR #2821.  The changes are much more straight forward than I had imagined.  I just need to get attributes updating tomorrow and then I can begin testing.

**Comment by objecttothis** [comment] 2020-06-15 11:36
@SteveIreland #2821 is ready for testing.  Want to give it a spin?

**Comment by objecttothis** [comment] 2020-07-27 10:31
@SteveIreland We are just about ready to merge #2821, but it would help if you could go to bintray and download the latest build of that branch and tell me if you see any problems and/or do a code review.

**Comment by jekkos** [comment] 2021-04-06 14:56
Duplicate of #3148

**Comment by objecttothis** [comment] 2021-08-05 12:14
CSV Item Import/Update via CSV is now in the master.

**Closed by objecttothis** 2021-08-05 12:14 UTC
Labels: enhancement
