### ISSUE TITLE
On sales page ( total )  and customer stats page ( total spent ) is shown as cash amount tendered which is not correct.

### ISSUE THREAD

**Issue by sky12ka4** [opensourcepos/opensourcepos#2419] opened 2019-04-02 22:01 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

this is applicable when cash is involved in payment.
In this issue (https://github.com/opensourcepos/opensourcepos/issues/1972 ) @truchosky  commented- ( https://github.com/opensourcepos/opensourcepos/issues/1972#issuecomment-386775673 ) is simailar to this but there is no reference of sales page where we select customer and there it shows total as amount tendered which is incorrect as it should show product purchase amount sum  and at customer page is also showing the same wrong info.
this is the case only when cash is involved as customer can tender more cash as compared to product total.

i have tried to fix it and got it correct also but wanted to know if this will not conflict anywhere else ( eg in reporting or somewhere else )
I have changed in the file : applications\models\customer.php file
in "public function get_stats($customer_id)" function 
"
SUM(sales_items.quantity_purchased) AS quantity,
					_SUM(sales_items.item_unit_price*sales_items.quantity_purchased) AS pricetotall_
				FROM ' . $this->db->dbprefix('sales') . ' AS sales
"
above i have added the middle line
and
"
$this->db->select('
						_SUM(sales_items_temp.pricetotall) AS total,
						MIN(sales_items_temp.pricetotall) AS min,
						MAX(sales_items_temp.pricetotall) AS max,
						AVG(sales_items_temp.pricetotall) AS average,_
                                                ' . "
"
above i have removed existing 4 lines with the above

by doing these changes i am able to get correct output,

guys let me know if there is a better way to achieve it.

**Comment by odiea** [comment] 2019-04-02 22:09
There possibly is but I see you gave us no information to work with.

**Comment by sky12ka4** [comment] 2019-04-02 22:19
> There possibly is but I see you gave us no information to work with.

what information do you need.
I have mentioned the file name where i have made the changes.
Problem which i was facing was wrong total was shown on sales page where we select customer and there it was showing total as wrong ( it was showing value as amount tendered which is incorrect when there product price is less than cash amount is given by the customer) 
I hope i have tried to explain the issue
do let me know if you need more information regarding the issue.

**Comment by odiea** [comment] 2019-04-02 22:22
Read the top of the form.

**Comment by sky12ka4** [comment] 2019-04-02 22:42
> Read the top of the form.

now i have updated it
please let me know if there is anything else required!

**Comment by odiea** [comment] 2019-04-02 23:00
Installation information
OSPOS version is:
OSPOS git commit hash is:
PHP version is:
MySQL or MariaDB version is:
OS and version is:
WebServer is:
Selected language is:
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is:

**Comment by odiea** [comment] 2019-04-02 23:03
Maybe one of the developers can help out with this if it is the unstable version .

**Comment by daN4cat** [comment] 2019-04-03 05:10
I didn't pay the last bill of my crystal ball and the license ran out...

**Comment by sky12ka4** [comment] 2019-04-04 20:38
> Installation information
> OSPOS version is: 3.3.0
> OSPOS git commit hash is: NA 
> PHP version is: 5.6.40
> MySQL or MariaDB version is: 10.1.38
> OS and version is: windows 10
> WebServer is: localhost (Apache 2.4.38)
> Selected language is: english
> (If applicable) Docker installation: NA
> (If applicable) Installation package for the LAMP/LEMP stack is : NA

I am currently using the latest version which i downloaded from :https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190327000845.master.2c4114.zip

I think this issue is also present in stable version 3.2.3

**Comment by sky12ka4** [comment] 2019-04-04 20:39
> Maybe one of the developers can help out with this if it is the unstable version .

issue is in both the versions

**Comment by SteveIreland** [comment] 2019-05-13 02:25
A pull request for a proposed fix will be submitted within the next few days.  It's already been coded up and tested but there are couple of things that remain.  Since this fix requires a small database change I need to put together a script that will migrate existing sales data.

**Comment by SteveIreland** [comment] 2019-05-13 03:27
Also, it is assumed with this fix that refunds due to over-payment will always be in cash.  So if they pay with gift card and you want to apply the fully amount of the gift card so that it can be closed out and then refund the difference in cash then that will also be possible.

The cash refund is only available as an option on the initial sale.  Adjustments to the cash refund amount will not be available with this pull request.

**Comment by SteveIreland** [comment] 2019-05-13 03:52
Originally if a payment was made with a credit card but it turned out to be an overpayment I was going to associate the refund with with the credit card.  But since this iteration is not going to support anything but cash refunds then I think it is going to be necessary to create a a cash payment type to insure that the refund is clearly identified as a cash  refund.  So on the "stat's" there will be two payment types listed, one is the the credit card payment and there will now be a cash payment type, but the amount will be negative because the payment amount (0) minus the refund amount will be a negative value.

If anyone has other thoughts about how this should be handled please say something.

**Comment by jekkos** [comment] 2019-05-13 09:46
Ok overpayment could be the case that a user actually wants some cash in return for an extra amount charged on the credit card. In that case it makes sense to handle this scenario, otherwise I'd consider this kind of situation to be a mistake and for the shopkeeper to correct it by reverting it (and paying back the amount overpaid).

**Comment by SteveIreland** [comment] 2019-05-14 03:22
Okay, I made the change to capture a cash refund for a credit card overpayment as a separate cash refund.  On Reports it will look like the following.  The cash transaction will be shown as a negative amount to indicate a refund.
![image](https://user-images.githubusercontent.com/23066623/57668572-c67bd980-75d5-11e9-8b6a-75cb282ac341.png)

**Comment by SteveIreland** [comment] 2019-05-14 03:32
The following example reflects the above transaction but is followed by a cash sale where the customer paid $20 but was refunded 9.40, so prior to this change Cash would have been 20.00 but now it reflects what was paid minus the refund which in this case is 10.60.

![image](https://user-images.githubusercontent.com/23066623/57668753-75b8b080-75d6-11e9-8152-560bceed1913.png)

**Comment by SteveIreland** [comment] 2019-05-19 01:56
A pull request has been submitted to address the cash refund issues.

The Customer stats issue appears to be a different problem and I'm happy to take a look at that over the next week.

**Comment by SteveIreland** [comment] 2019-05-19 02:51
Okay, looking at the Customer Stats panel I agree that it is totally based on payments which pretty much makes it useless in an invoice environment and inaccurate in a POS only environment where cash refunds are involved.

So the information displayed on the stats page include:
* Total Spent
* Maximum Spent
* Minimum Spent
* Average Spent
* Quantity
* Average Discount

Before I make any changes are we all in agreement that this should reflect the sales amount and not just the payments made?  Now that cash refunds are captured it is easy to report the net payment (tendered minus cash refunded - but that would still not pick up any invoice sales for which payment has not yet been made.

**Comment by sky12ka4** [comment] 2019-05-21 08:10
guys one more time i would like to brief my issue:
Total spent is shown incorrect as it adds the total money tendered ( in case of cash payment ) but does not deduct the change given back to customer.
eg:
product price = INR 50
Customer gave = INR 100
Cashier would give him back = INR 50

So here total spent would be = customer gave (INR 100) - Product price ( INR 50 ) = INR 50 ( Basically the product price always )
But this sofware directly adds what customer gives as total spent.


I hope this will add some clarity in my question  ( issue ).

**Comment by SteveIreland** [comment] 2019-05-21 10:23
Since there doesn’t appear to be a lot of interest in this customer stats view I will proceed with the change as @sky12ka4 has requested (now that the cash refund amount is being captured that will be easy to do).   I will just update the pull request with the change.

**Comment by odiea** [comment] 2019-05-21 15:29
I downloaded and Installed.
opensourcepos.20190519014926.track-initial-cash-refund.ebbcef.zip
The following was the Sale.
![2019-05-21 09_17_04-Window](https://user-images.githubusercontent.com/10962177/58109337-b2724200-7baa-11e9-9f76-a3c715269739.png)
The following is what the Customer Stats shows.
![2019-05-21 09_16_41-Window](https://user-images.githubusercontent.com/10962177/58109409-d0d83d80-7baa-11e9-8055-f3c9f29b1a10.png)
I take it this was not quite complete then?

**Comment by SteveIreland** [comment] 2019-05-21 16:34
I haven't touched the customer stats screen yet, so it would still show $2, but if nothing stops me I'm going to try to have the branch updated for the stats screen sometime tonight.

**Comment by odiea** [comment] 2019-05-21 16:41
Thanks for the Update and all the work you have done so far on OSPOS.

**Comment by SteveIreland** [comment] 2019-05-22 02:28
My pleasure.  The pull request has been updated to "fix" the customer stats panel.  Let me know if it's not what was needed.

**Comment by odiea** [comment] 2019-05-22 12:32
Downloaded it. Installed it and works the way it was designed to. Thanks. True totals will be a great new feature.

**Comment by sky12ka4** [comment] 2019-05-22 16:59
how can i merge the code with the existing code?
I am currently using 3.2.3 version.

**Comment by WebShells** [comment] 2019-05-22 17:10
@Sky12ka4 you can either apply the code manually or wait until our new release so you can download a stable version...

**Comment by nira168** [comment] 2019-05-26 08:15
After Modifying the code, I still found out the customer reward point still use payment_amount to calculate the point. May I know where should I change this code?

**Comment by sky12ka4** [comment] 2019-05-26 11:42
@nira168 whats your current version of open source pos and how did you modify the your code with the new one?

**Comment by nira168** [comment] 2019-05-26 11:48
@sky12ka4  Version 3.3.0
I modified follow  @SteveIreland. The customer stats is correct now, but the problem is customer reward point still use payment amount to get the percentage of point, not the actual amount pay

**Comment by SteveIreland** [comment] 2019-05-26 13:34
I'm not familiar with the customer reward program.  Looking at the code it is obviously payments based but I'm not clear as to why.  It seems to me that the customer reward program should be based on the sales amount

Someone else who understands the rewards program will need to direct what happens here.  
.

**Comment by odiea** [comment] 2019-05-26 14:26
I think it was due to easy access to the payment amount that all totals seemed to follow until now.

**Comment by SteveIreland** [comment] 2019-05-26 15:42
" ... until now."  ?

Is there an impression that I made it hard to access the payment amount?

From my viewpoint, the net impact of my changes on retrieving of payment amount is effectively replacing `payment_amount` with `payment_amount - cash_refund` in order to get a more accurate representation of amount paid.

But I agree with you that if you can assume a pure POS sales system where all sales are "paid in full" then it is hard to avoid going to payments to calculate the sales amount instead of trying to use complex SQL.

**Comment by odiea** [comment] 2019-05-26 15:49
No issue You were the first to implement a correct sales total. " Other than the takings view". Which is much appreciated by all.
Until now everyone just used the payments payment_amount to get totals and you decided to correct that issue. Thanks

**Comment by odiea** [comment] 2019-05-26 15:51
Now others are going to be requesting your fix in other things like Rewards.

**Comment by odiea** [comment] 2019-05-26 16:01
My apologies if you took it as a derogatory remark instead of the compliment it was meant to be.

**Comment by SteveIreland** [comment] 2019-05-26 19:36
I've been in the business long enough to know that there are often unintended consequences of my changes.  So I just wanted to make sure that I didn't step on my own foot (or someone else's).  Thanks for the clarification.

**Comment by nira168** [comment] 2019-05-29 12:34
Thanks @SteveIreland for fixing the customer stats issue. For customer rewards point, i found it in application\models\sale.php. As I subtract cash_refund in $total_amount, I will be able to get point based on sale amount. However, do I need to subtract all cash_refund in this function to avoid any conflict? Plus, I want to get point based on the sale_amount but not reward point that customer use. For example my item price is 20$, if customer  has exist point 2$, so what they actual pay will be 20$-2$= 18$, but the point based on total is item price 20$(10%)=2$, what i want is the actual point is 18$(10%)=1.8$ 
	public function save($sale_id, &$sale_status, &$items, $customer_id, $employee_id, $comment, $invoice_number, $work_order_number, $quote_number, $sale_type, $payments, $dinner_table, &$sales_taxes)
	{
		if($sale_id != -1)
		{
			$this->clear_suspended_sale_detail($sale_id);
		}

		$tax_decimals = tax_decimals();

		if(count($items) == 0)
		{
			return -1;
		}

		$table_status = $this->determine_sale_status($sale_status, $dinner_table);

		$sales_data = array(
			'sale_time'			=> date('Y-m-d H:i:s'),
			'customer_id'		=> $this->Customer->exists($customer_id) ? $customer_id : NULL,
			'employee_id'		=> $employee_id,
			'comment'			=> $comment,
			'sale_status'		=> $sale_status,
			'invoice_number'	=> $invoice_number,
			'quote_number'		=> $quote_number,
			'work_order_number'	=> $work_order_number,
			'dinner_table_id'	=> $dinner_table,
			'sale_status'		=> $sale_status,
			'sale_type'			=> $sale_type
		);

		// Run these queries as a transaction, we want to make sure we do all or nothing
		$this->db->trans_start();

		if($sale_id == -1)
		{
			$this->db->insert('sales', $sales_data);
			$sale_id = $this->db->insert_id();
		}
		else
		{
			$this->db->where('sale_id', $sale_id);
			$this->db->update('sales', $sales_data);
		}
		$total_amount = 0;
		$total_amount_used = 0;
		foreach($payments as $payment_id=>$payment)
		{
			if( substr( $payment['payment_type'], 0, strlen( $this->lang->line('sales_giftcard') ) ) == $this->lang->line('sales_giftcard') )
			{
				// We have a gift card and we have to deduct the used value from the total value of the card.
				$splitpayment = explode( ':', $payment['payment_type'] );
				$cur_giftcard_value = $this->Giftcard->get_giftcard_value( $splitpayment[1] );
				$this->Giftcard->update_giftcard_value( $splitpayment[1], $cur_giftcard_value - $payment['payment_amount']);
			}

			if( substr( $payment['payment_type'], 0, strlen( $this->lang->line('sales_rewards') ) ) == $this->lang->line('sales_rewards') )
			{
				$cur_rewards_value = $this->Customer->get_info($customer_id)->points;
				$this->Customer->update_reward_points_value($customer_id, $cur_rewards_value - $payment['payment_amount']);
				$total_amount_used = floatval($total_amount_used) + floatval($payment['payment_amount']);
			}

			$sales_payments_data = array(
				'sale_id'		 => $sale_id,
				'payment_type'	 => $payment['payment_type'],
				'payment_amount' => $payment['payment_amount'],
				'cash_refund'    => $payment['cash_refund']
				
			);
			$this->db->insert('sales_payments', $sales_payments_data);
			$total_amount = floatval($total_amount) + floatval($payment['payment_amount']-$payment['cash_refund']);
		}

**Comment by sky12ka4** [comment] 2019-05-29 21:41
Thanks a lot @SteveIreland for fixing this issue!
i still have one query:
when i asked this question about bug in customer stats, i mentioned a small fix for this which require small code change in the applications\models\customer.php file ( i have mentioned code in my original question).
So my query is how these two solutions ( one what i did and second what you did ) are going to impact on this project? ( like reporting wise or something else ).
when is executed your code and when i used mine i didnt see any difference in terms of UI and results shown.(Sales page and Customer stats page)

**Comment by daN4cat** [comment] 2019-05-30 04:54
With regards to reward payment, that was added long time ago by a contributor and it has been "kept alive" through the releases by me but without going deep into its real functionality.
Not sure that is really sounding give last year changes.

**Comment by SteveIreland** [comment] 2019-06-10 10:10
The original reported issue is resolved so I’m closing this issue. Please open a new issue if there is a different problem to be resolved. Thanks

**Closed by SteveIreland** 2019-06-10 10:10 UTC
Labels: bug, enhancement
