### ISSUE TITLE
how to solve quantity problems for stocks: ex.: I want to sell soft-drinks but instead of per bottle, i want to sell it by case. Ratio: 1 case of softdrinks=12 bottles

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#1919] opened 2018-04-02 09:00 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by izeblood** [comment] 2018-04-02 09:01
this issue is very common in a basic Point of Sale operation... PLEASE HELP.

**Comment by izeblood** [comment] 2018-04-02 09:04
IMPORTANT: In report module... it is important to view the stocks by: Per Case or Per bottles. if you have 300 bottle of softdrinks in your stocks..then you can also view it by Case which is 25 cases of softdrinks remaining....

**Comment by mckaygerhard** [comment] 2018-04-02 09:38
* umm do you see that do not fill the template issue?
* seems this issue are auto-solved using the item kit feature
* seems also you have defined two kind of units for the same article

due that reasons i dont think so some bondy take in consideration your issue and maybe will be closed

**Comment by izeblood** [comment] 2018-04-03 04:52
the item kit feauture CAN'T Solve the reporting problem..What if I want to know the stocks or items by CASE? or by BOTTLE? UMMM!??

**Comment by daN4cat** [comment] 2018-04-03 07:35
That means you need to implement the feature by yourself or find somebody to do for you.

**Comment by SteveIreland** [comment] 2018-04-03 13:44
Did you set up the item cost "per bottle" or "per carton"?  When you receive it how do you have the item configured?  Do you receive it "by carton" or "by case" or maybe even "by bottle"?

**Comment by izeblood** [comment] 2018-04-04 03:53
I set up the item cost per bottle.but when I used the item kit for bundled item to have it by case.. i can't generate report how many items remaining in case...only in by bottle..

**Comment by SteveIreland** [comment] 2018-04-18 13:06
Since this issue keeps coming up I thought I'd take a stab at it to see if a solution can be provided that meets most expectations without adding too much of a burden on the system.

**Comment by jekkos** [comment] 2018-04-18 17:01
Actually what you need is a 'unit' linked to the amount you're looking at. I did something like this in an old branch. But I guess indeed it involved adding some columns linked to item_quantities denoting a unit type.
Then conversions to one or another can be defined. 
Also see #140

**Comment by izeblood** [comment] 2018-04-19 01:54
@jekkos @ SteveIreland maybe the solution for this is to modify the item kits....and put some unit type in order to track the per unit item remaining in every sale being conducted.

**Comment by nerv55** [comment] 2018-04-19 02:47
@izeblood  what you need is **presentation** is producto attribut and there you can put all the presentation you want for example: soft drinks: per unit, six pack, carton, and so on, each presentation has his own barcode this way when you read it in sells form it read the quantity of presentatio+product code. but this is not implemented yet in current version. to implement this new table must be add to manage all the presentations per item.

**Comment by SteveIreland** [comment] 2018-04-19 02:56
There are probably a 1/2 dozen ways of doing this.  The approach taken will be intended to minimize the impact on the existing system.  Since this feature will be used by only a small percentage of the user community it's important to make it as invisible as possible to the majority of the users yet meet the requirements of those who need this feature.

**Comment by nerv55** [comment] 2018-04-19 03:04
@SteveIreland  to minimize the impact as you said, is to add another column to item table to put presentation pack quantity, but this has limitations you can only have one presentation per item.
in the report add another column to reflect quantity packs as result of **left in stock quantity /  pack quantity**, in sales form no need to change, all the sales will be by unit.

**Comment by SteveIreland** [comment] 2018-04-19 13:36
Not really.  To accomplish the reporting goals I will need to add three fields to the item table as well as to one or more of the sales tables (in order not to kill performance).   I'll flesh it out in the wiki tonight.  Not everyone wants to always sell by the lowest selling unit.

**Comment by daN4cat** [comment] 2018-04-19 17:29
We discussed the idea of having a recursive pattern where an item can have a field pointing to a parent item as an array field storing child items and so have a parent item owning child items.
That could solve all the issues having aggregations but being a sellable itself.
This would solve this issues as item kits.

Hope I could convey the idea.

It would require some rethinking of the domain model super item, sub items, attributes describing the item.

A bit of OO approach here....

**Comment by SteveIreland** [comment] 2018-04-19 18:12
I think I understand what you're saying, but each unit of packaging is essentially a separate item and the site might want to sell soft drinks by the carton, or break them down for "out of refrigerator" sales, thus selling it by the bottle.   Each method of packaging can have it's own unique UPC code and can be inventoried and sold separately.  Some companies may want to know how many of each they have and others may want to know how many of the lowest selling items they have.  So to maximize flexibility they should each be treated as an item.  This would also allow us the greatest flexibility for purposes of reporting.   I work in an environment where this is just the way things are so I'm intimately aware of all of the challenges  related to costing, pricing, inventory, receiving, etc caused by a multi-packaging scenario.

For the purposes of OSPOS I know I don't need to make the database as complex as the one I have to work with (you and jekkos would justifiably reject it).  I just want to make a low-impact database change that represents the parent (low-sell) - child (alternate packaging) relationships.

**Comment by daN4cat** [comment] 2018-04-19 20:09
The recursive model was exactly to have one parent item (carton) with child items (bottles). Both are sellable independently because having different UPC but they are connected.
So if you sell a carton you know 12 bottles are gone and deducting the quantity by virtue of the relationship. Something down that line that would need to be modelled a bit.

**Comment by daN4cat** [comment] 2018-04-19 21:38
Good point. I need to think about but I see the rationale.

**Comment by izeblood** [comment] 2018-04-20 04:26
@SteveIreland thank you for your idea...but one thing that i want to improve to the item and item kits since these two modules are related but can we modify the item kits in order to view and compare the how many  items being bundled from the item module.
![item_kits](https://user-images.githubusercontent.com/32444665/39030668-f3ea6d4a-4495-11e8-8111-94d9dcad2aae.jpg)

**Comment by izeblood** [comment] 2018-04-20 04:53
600 is in bottles and 500 is in kilos..

**Comment by SteveIreland** [comment] 2018-04-20 12:56
Kit's are not stocked and items have a 1 to many relationship with kit items so it cannot be used to properly extend the definition of an item.   So I don't plan, at this time, to touch kits.  With the proposed change you will have the "quantity per" and the ability to specify "BOTTLES" and "KILOS".

**Comment by SteveIreland** [comment] 2018-04-23 02:46
I started this over the weekend.  I've added the elements to the items table and added the required changes to configuration and item maintenance.  It seems to be working pretty well at this point.  There are a couple more improvements I'd like to make that should make it easier to manage multi-pack items but they are lower priority changes.

The reason I'm posting is to point out that I could drag this out forever since I don't have a deadline.  I'm anticipating a final completion in about a month but as soon as someone wants to join me in playing around with it then I can submit a pull request for it. 

My opinion is that this doesn't require any changes to sales.  You can sell 15 cartons of Coke and 4 bottles of Coke on the same sale with this approach.  What might be an interesting addition to sales is an automatic transfer of stock from one pack to a smaller pack when there is inadequate stock for the sale when the item being sold is the smaller pack.  Opinions are welcome.

What I haven't yet changed is any of the reports to take advantage of the change.  I think I'll go ahead and add a new option for the inventory reports to generate the report in low sell item units.  I will also include the new item pack name on the inventory reports as part of the item name if the system is configured to use multi-pack items.  Then someone can tell me what other changes need to be made.

**Comment by izeblood** [comment] 2018-04-24 05:32
I think this is one of the great modification/addition feature for this great OSPOS.

**Comment by SteveIreland** [comment] 2018-04-28 20:56
If no one has a strong opinion on or question about the above proposed change to the rendering of the item name I shall continue on

**Comment by daN4cat** [comment] 2018-04-29 05:41
Yes don't add more columns, your proposal is fine with me.

**Comment by SteveIreland** [comment] 2018-05-14 00:32
A preview pull request has been submitted for review and discussion. 

There are a couple of additional tweaks I'd like to make, but similar to the temporary items pull request I'd like to get some feedback before doing any more work on this.

To enable it go to general configuration and click on the Enable Multi-pack Items.

There are changes to item maintenance, receiving and sales and the inventory summary report.

**Comment by SteveIreland** [comment] 2018-05-14 00:50
There are three new fields added to the items table, the quantity per pack, the pack name, and the item_id of the low sell item.  The quantity per pack should be defaulting to a value of 1, the pack name defaults to a value specified in the languages file for default pack name, and the low sell item id either references itself (if the item is also the low sell item or it refers to the low sell item.

The quantity per pack is supposed to represent the number of low sell items that are contained in the pack.  For example if there is a carton of Pepsi, the pack name for the low sell item will probably be Bottle, and quantity per pack will be 1.  For the carton item the pack name will be Carton and the quantity per pack will be 6.

**Comment by SteveIreland** [comment] 2018-05-14 01:00
An existing field on the items table that is being used a little more in receiving is the receiving quantity (also known as the shipping pack).  Shipping pack is used when you receive the item in a higher pack and you do not want to keep inventory for the item in the pack that you receiving it from the shipper.

In receiving this is now a drop-down selection list.  It will either be the receiving quantity or 1.  This is intended to provide some flexibility when receiving an item.  Maybe you receive one shippers case but you really want to break it down in the same receiving transaction.  You can do that now by receiving whatever items according to how you broke it down.

You can also use receiving to break down a case to smaller inventoried units by entering a negative quantity for the item that you are breaking down and a positive quantity for the item that you breaking the case down into.  The net value of that receiving transaction should be zero if it's entered correctly and the items have been properly configured.

**Comment by SteveIreland** [comment] 2018-05-14 01:11
As mentioned earlier, if multi-pack items is enabled the pack name is appended to the item name wherever the item name is displayed (at this time this hasn't been applied to all reports, just the Inventory Summary report).

For example, if you keep inventory for bottles of Pepsi, cartons of Pepsi, and cases of Pepsi, you'll set up three separate items with the same name of Pepsi, however, the pack names will be Bottle, Carton, and Case.  For sales, receiving and reports the item name will be rendered for display purposes as "Pepsi | Bottle", "Pepsi | Carton", and "Pepsi | Case".

**Comment by SteveIreland** [comment] 2018-05-14 01:19
In item maintenance the low sell item defaults to the same item and is displayed as blank.  I thought that would be a clearer indication that the item is low sell or the only way the item is inventoried.

**Comment by SteveIreland** [comment] 2018-05-14 01:23
Where search suggestions is configured, selecting "Name" when multi-pack item is enabled will automatically insert the pack name after name.  You only select Name but when search suggestions are listed both the name and pack will be showing with the " | " delimiter.

**Comment by SteveIreland** [comment] 2018-05-14 01:39
The pull request does not include the temporary items feature but there are conflicts, so after one is merged the other will need to be rebased before merging.

**Comment by SteveIreland** [comment] 2018-05-14 21:29
One "nice to have" feature that might be interesting is the ability to enter a cost for a low sell item and have that cost (with the appropriate quantity per pack multiple) automagically applied to the higher sell items.   Thoughts?

**Comment by izeblood** [comment] 2018-05-16 14:29
I tested your code for this great modification but the sales module doesn't works. its error

**Comment by izeblood** [comment] 2018-05-16 14:48
I'd follow all the codes correctly but when I click the Sales Module...its down....can't load...

**Comment by SteveIreland** [comment] 2018-05-16 16:11
@izeblood Thanks for trying to look at it.  I'll see if I can replicate the issue tonight.

**Comment by SteveIreland** [comment] 2018-05-17 03:11
I downloaded the `multi-package-item-2` branch and built a new test environment from it and did not have any problems with the sales module.  

However, I did find a problem with the extended total amount on the default receipt. I'll be submitting a fix for that soon.  I tested item setup, receiving, and sales and no other problems were encountered.,  The instructions that @mckaygerhard provided a link for should help with providing sufficient information to chase down the exact issue.  (Particularly the last section on PHP errors.)

After downloading the branch I ran composer install, npm install, grunt --force, and devinstall.sh, removed the intermediate stuff and used that as my install. Did you follow those steps?

**Comment by SteveIreland** [comment] 2018-05-19 19:32
Hmmm ... no additional feedback.  I'm guessing that everyone is biding their time (like me) for the 3.2.1 release.
I wasn't able to replicate the extended total amount issues on the default receipt that I reported earlier but I did find a problem with the rendering of the item name on an invoice which I've fixed.  The fix will be included in the next update to the pull request after I've rebased it over the 3.2.1 release.

**Comment by izeblood** [comment] 2018-05-25 10:23
i need more time to study on the flow on the new modification on this OSPOS. but for this time..i'm busy solving some other issue...

**Comment by SteveIreland** [comment] 2018-05-28 00:45
I made some improvements this weekend to the pull request, 

I rebuilt a test environment environment for it and run through some basic tests .... it seems to be working.

I also uploaded a zip file for it that has been run through the composer, npm, grunt, and devinstall steps and then cleaned up.  It can be found at ...

https://dl.bintray.com/steveireland/opensourcepos/

If you try it please let me know if it works.  It was installed into a WAMP environment and should also work for a LAMP install.

**Comment by jekkos** [comment] 2018-05-28 07:26
Always funny to see the demo instance appearance changed every time I login to it

**Comment by SteveIreland** [comment] 2018-05-28 15:21
Well, I'm glad it didn't make it.   Although I think I could see some advantages to having that ability I certainly can see a lot of disadvantages.  However, it could be managed, I think, if I did NOT want it to impact the demo site by simply deleting the pull request before pushing anything to my fork.

**Comment by izeblood** [comment] 2018-05-29 06:00
@SteveIreland I try your uploaded zip file but when i test to transact in sales module while clicking complete button to transact it appears like this: This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by izeblood** [comment] 2018-05-29 06:56
@SteveIreland I tried your zip file but i don't see any option in sales module that declare an option if a customer buy with different units either by boxes, by pack, by case...what i observed is purely an individual stock type..

**Comment by SteveIreland** [comment] 2018-05-29 12:52
I'm glad the zip file worked for you. Did you check the box under general configuration to enable?

If so then you'll be able to configure the items appropriately.  Then when you go to sales and place and order for the items you'll be able to select the pack of the item to be ordered as shown below.

![image](https://user-images.githubusercontent.com/23066623/40659853-6ca19664-631d-11e8-8a64-172e7fbaad4d.png)

If that's not what you had in mind then please try to explain further what your expectations are.

**Comment by izeblood** [comment] 2018-05-30 02:30
Ok great. but i have few questions: In order for me to have multiple pack in the sale module, like per Bottle, per Carton, per Case, Should I add items in 3 different units? Can we merge this item to make it one? because the important things in this feature is to monitor how many items left or sold if customer buy the product using multiple packaging. Or maybe I'll not explore yet the exact output of your great modification of this OSPOS... thanks so much @SteveIreland .

**Comment by mckaygerhard** [comment] 2018-05-30 02:32
> Can we merge this item tomake it one?

err sounds confusiing

**Comment by izeblood** [comment] 2018-05-30 02:33
Another things is the sale module is down when i click complete button.

**Comment by izeblood** [comment] 2018-05-30 02:37
Yep... since the items are using the same Product Name...

**Comment by izeblood** [comment] 2018-05-30 02:47
![pos-2](https://user-images.githubusercontent.com/32444665/40695904-ef8559a2-63f5-11e8-8b1e-03519ce632f2.jpg)

**Comment by SteveIreland** [comment] 2018-05-30 02:53
As I mentioned earlier (somewhere), I wanted to add this feature without a major impact on the system. So this feature uses the database design that is there (and which is core to the reporting system).

I added the pack name, quantity per pack, and a reference to the low sell unit to the item.

If a customer walks up to the counter with a carton of coke (item 1) and a bottle he took out if the cooler (item 2) then you can sell 1 of the bottle item and 1 of the carton item.  Of course, this assumes that you are keeping an inventory of the number of bottles in the cooler and an inventory of the number of cartons on the shelf.  You might also stock the item by cases back in the back and inventory them by the number of cases.

Each of these items have the same product name which is why the pack name must be dynamically appended to the item name in order to distinguish between the two products.

**Comment by SteveIreland** [comment] 2018-05-30 03:02
No doubt that there will be refinements needed once more people get their hands on it and discover the warts. There are already a couple of things that I would like to add.  I find configuring the costs require a little more effort and attention than I like, so I would like to add the cost and price on one item and then have that automatically applied to the other items using the quantity per pack as a multiplier or divisor.  But in the real world that might not be appropriate or might be much more complex.

**Comment by izeblood** [comment] 2018-06-25 02:59
@SteveIreland another thing i that i found out is the type of item which has an special offer like for example: 3 bottles of coke is $10. in 30 bottles that is 100. Can the multi-pack feature solve this kind of scenario?thanks for your time...

**Comment by SteveIreland** [comment] 2018-06-27 12:29
Nope ... that would be stretching it a bit too far.  What you are asking for here is a new promotional pricing feature.  Kits could be used for it but I wouldn't wish that maintenance load on anyone.

The promotional pricing feature (which sounds like tier pricing) would need to be coded to recognize and handle the multi-pack scenario.

**Comment by izeblood** [comment] 2018-07-11 01:40
@SteveIreland ::::I'm just want to query also about stocks that has a decimal point..like for instance in kilos... if 1/2 that is .5 , 1/4= .25 , and 3/4 that is .75..but my question is the stock if you have an item in stocks that quantity is 10 and the customer buy 3/4 out of it.. the stock still remain as 10????? basically the exact quantity is 9.25....what can you say about this?...thanks....

**Comment by daN4cat** [comment] 2018-07-14 08:34
This is now in master, please take the latest code and test it.
If any issue @SteveIreland will fix it, if something is broken please commit the change directly to master.

**Comment by daN4cat** [comment] 2018-07-14 09:48
@SteveIreland got the first issue (remember I have PHP 7.1?):

From Register, search an item and nothing pops up, checking from the debug console:

```
A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: models/Item.php

Line Number: 680

Backtrace:

File: /<my path>/application/models/Item.php
Line: 680
Function: _error_handler

File: /<my path>/application/controllers/Sales.php
Line: 116
Function: get_search_suggestions

File: /<my path>/public/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: models/Item_kit.php

Line Number: 194

Backtrace:

File: /<my path>/application/models/Item_kit.php
Line: 194
Function: _error_handler

File: /<my path>/application/controllers/Sales.php
Line: 117
Function: get_search_suggestions

File: /<my path>/public/index.php
Line: 315
Function: require_once
```

**Comment by odiea** [comment] 2018-07-14 11:18
Low inventory report is not showing the Item name.

**Comment by odiea** [comment] 2018-07-14 11:59
Yes you did and it is working fine now so I tried the low Inventory report and I get the following result.

![2018-07-14 05_56_55-](https://user-images.githubusercontent.com/10962177/42724186-d45e8b14-872a-11e8-8b7c-ec124324cfb8.png)

**Comment by WebShells** [comment] 2018-07-14 12:06
@odiea mmmm its working fine in the demo server...

![demoo](https://user-images.githubusercontent.com/26513147/42724235-742185e2-8777-11e8-8103-d42f79cbbb66.png)

**Comment by daN4cat** [comment] 2018-07-14 12:22
PHP version on both sides?

**Comment by odiea** [comment] 2018-07-14 12:50
opensourcepos.20180714083408.master.8e6b33.zip Gave me the issue.
Did another download of the current version.
opensourcepos.20180714094359.master.674f14.zip is ok.

**Comment by SteveIreland** [comment] 2018-07-14 12:59
Wow  PHP 7.2 ...  I was only on 7.1.16, but it looks like I can bump it up as high as 7.2.4 so I will do that today retest and fix the reported issues.

**Comment by SteveIreland** [comment] 2018-07-14 13:00
And thanks for the merge!

**Comment by odiea** [comment] 2018-07-14 13:02
I lied. It may be another php issue.
Ok on xampp php 7.0.8 Mariadb 10.1.13 apache 2.4.18
Not showing on Wamp php 7.1.16 Mysql 5.7.21 Apache 2.4.33

**Comment by SteveIreland** [comment] 2018-07-14 14:20
The way the count() function is used throughout the system looks like it was broken in PHP 7.2. There may be other issues too.  I'll be doing the first wave of debugging with the multi-pack feature turned off and hopefully I'll be able to get to the multi-pack feature debugging tomorrow.  However, feel free to check out the multi-pack feature and let me know where you think it needs to be improved.

**Comment by daN4cat** [comment] 2018-07-14 16:34
@SteveIreland sorry for the inconvenience, a week ago I just fixed the item_kits form and didn't test more.
I've updated to PHP 7.2 probably a month ago.

So we have something to improve again to support PHP 7.2.

**Comment by SteveIreland** [comment] 2018-07-14 16:34
Pull request #2049 was just merged into master and should resolve the count function issues.

**Comment by SteveIreland** [comment] 2018-07-14 16:37
No problem, although I doubt most of the Web site hosting companies currently support 7.2 it is always good to be ahead of the game!

**Comment by daN4cat** [comment] 2018-07-14 16:37
And as you said it was always wrong. Indeed checking the code better I don't know how it ever worked...

Thanks for the fix. Testing.

**Comment by daN4cat** [comment] 2018-07-14 16:41
Yep works fine.

**Comment by izeblood** [comment] 2018-07-16 05:00
@SteveIreland can you provide the link of your multi pack so that i can test it?

**Comment by WebShells** [comment] 2018-07-16 05:10
@izeblood its in the master...

**Comment by izeblood** [comment] 2018-07-16 06:41
I got this::Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php .why?

**Comment by WebShells** [comment] 2018-07-16 06:51
Please check current issues for this type of errors, its because you cloned the repo directly from master, it doesnt have system folders...

**Comment by izeblood** [comment] 2018-07-16 06:59
what should i do?

**Comment by SteveIreland** [comment] 2018-07-16 12:45
Download the latest zip file from https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files

**Comment by izeblood** [comment] 2018-07-17 03:44
@SteveIreland kindly explain the quantity per pack and low sell item?

**Comment by izeblood** [comment] 2018-07-17 03:53
@SteveIreland when i change the quantity per pack into 12 , and pack name to Case since in every case is compose of 12 bottles but in sales it display only 1 item

**Comment by izeblood** [comment] 2018-07-17 03:57
@SteveIreland  For example: Coke|Case is different stocks in Coke|Each?

**Comment by izeblood** [comment] 2018-07-17 04:02
@SteveIreland waittt............... I already got it...thanks @SteveIreland .... I already understood your whole idea, the flow about multi pack--it is very useful and awesome...

**Comment by izeblood** [comment] 2018-07-17 04:11
@SteveIreland I used multi pack and I can trace now the quantity per case as well as the individual stock(each) but i cannot transact single bottle instead per case....

**Comment by izeblood** [comment] 2018-07-17 04:21
![askme](https://user-images.githubusercontent.com/32444665/42796253-79a397bc-89bb-11e8-900b-e0279a428308.jpg)

**Comment by izeblood** [comment] 2018-07-17 07:04
how to use low sell item?

**Comment by mckaygerhard** [comment] 2018-07-17 12:11
when explaint all of this requested by @izeblood please make a general explanation to post and write at the wiki @SteveIreland , thanks in advance

**Comment by izeblood** [comment] 2018-07-23 05:12
@SteveIreland is it possible to merge the quantity of the product using your multi pack feature using the same barcode/product id in different packages like; per each,per case,or per pack?

**Comment by SteveIreland** [comment] 2018-07-23 10:15
Technically speaking each pack should have its own unique barcode and barcodes should be unique. To me it only makes since to report the total of the low sell units in the inventory report. In sales we could report the total quantity available in low sell units

**Comment by SteveIreland** [comment] 2018-07-24 12:18
If you have in stock 5 cases of coke with 24 bottles per case and you also have 10 bottles of coke on the shelf and you sell 1 bottle of coke then you still have 5 cases of coke but now you have 9 bottles.

Yes, that is obvious .. but hang in there with me ....  and I am ignoring cartons of coke in this example.

If you have 0 bottles of coke on the shelf (the shelf has a spot for 10 bottles but it is empty), but you have 5 cases of coke in the back and you sell 1 bottle of coke then the way it is right now the inventory will go negative on the bottles of coke.  The expectation is that immediately following the completion of the sale you will use receiving to record the fact that you broke open a carton of coke and now you have 23 bottles of coke in inventory (10 bottles which you moved to the shelf to replenish the shelf and 13 bottles in the back found in a broken case).

I mentioned this earlier, but now is a good time to mention it again.  What I could do is generate an automatic case break when selling a lower pack and the inventory goes negative.  This would transfer at least one case of the higher pack item to the lower pack inventory.  There are a few other scenarios that complicate this but that's the essence.  If you think that would be helpful and not complicate things then I can add that to my "to do" list for this release.  The "complication" is that when more things happen automagically "behind the curtains" some users might get confused and frustrated.

**Comment by SteveIreland** [comment] 2018-07-24 12:32
To add clarity for drive by readers, bottles of coke and cases of coke are inventoried separately, so if I look at available inventory I see the total number of bottles that are not in closed cases (let's assume 14).  If I have 5 cases of coke then I also (in addition) have 120 bottles of coke in cases. So the total number of bottles of coke that I have is 120 + 14 = 134.

Another possible "feature" I could add is at the point of sale when we show the quantity in stock for a bottle is that the quantity available represents the total of the current pack item and the effective total of the current pack found in higher pack instances of the item.

For example on the register, for quantity on hand for a bottle of coke I could show 134 instead of 14

**Comment by SteveIreland** [comment] 2018-07-24 12:37
I think I'm going to tweak the system a bit so that if there is only a single pack of an item then the low sell pack name is optional.  Does anyone see a problem with that?

**Comment by mckaygerhard** [comment] 2018-07-25 12:33
i hope you doit @SteveIreland i dont think will be easy.. it's a complete inventory management rule related!

**Comment by daN4cat** [comment] 2018-11-25 18:04
@SteveIreland is this done? I vague memory that you implemented this feature.

**Closed** 2018-11-25 20:15 UTC
Labels: enhancement

**Comment by izeblood** [comment] 2018-12-05 03:40
the current development master is not working


Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30

**Comment by SteveIreland** [comment] 2018-12-05 12:01
The current development master works fine. You just likely missed a step that’s described in the wiki.

This is a closed thread (and a very long one).  Please don’t use it to post unrelated issues.

Thanks
