### ISSUE TITLE
Employee Permissions

### ISSUE THREAD

**Issue by MexasPT** [opensourcepos/opensourcepos#1799] opened 2018-01-22 12:19 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
- OSPOS version is: 3.0.2 e 3.1.1

###Question

Employee Permissions

I need to restrict access to employee reports.
I've been trying for over a month, but I can not restrain the employee from viewing only his sales.

Can you help me? Please!

Please....

**Comment by mckaygerhard** [comment] 2018-01-22 12:26
i think in ospos 3.0.X and 3.1.X the permission are very basic: can view all or cannot view all , no tonly his/her sales..

in the case to restrict the reports, what the exacts steps do you made for?

**Comment by MexasPT** [comment] 2018-01-22 12:35
I tried to make the reports show only the logged in user. But always unsuccessful ...

I have no idea what to change to implement this.
:(

**Comment by mckaygerhard** [comment] 2018-01-22 12:42
ok, but what are you doing to make "that", i mean what steps to reproduce by my or the side of the ospos developers.. 

do yo altered any sources? what and why?

have you already know how the permissions works?

**Comment by MexasPT** [comment] 2018-01-22 13:12
I try to altered the files in application/models/reports:
- Specific_employee.php
- Summary_employees.php
- Summary_sales.php

You just referred to version 3.0 and 3.1 ...
Does version 3.2 already enable what I want?

**Comment by mckaygerhard** [comment] 2018-01-22 13:29
in 3.2 you can made persissions to employees to view or not reports or sales , but globally, can view all or cannot view all sales or reports.. not only their own sales..

ok your changes must be exlicit, if you made changes, then only that logic are on your head, exposing that errors and where must be provided..  and take in consideration that here actually the developers are very complicated with current release.. so you must made specific questions about the code modification. not general questions

**Comment by daN4cat** [comment] 2018-01-22 14:03
Developers very complicated.... interesting.

**Comment by odiea** [comment] 2018-01-22 14:11
It appears he possibly did not use a translator for that post.

**Comment by mckaygerhard** [comment] 2018-01-22 14:20
i said that as i noted there's no much time to "take by the hand" to other in the code right? i made some months some questions very specific and a too complicated thins were posted.. that's why i post that i said

**Comment by mckaygerhard** [comment] 2018-01-22 15:15
hi @MexasPT in 3.2 there's a price filters, maybe this can help you in the permissions

**Comment by MexasPT** [comment] 2018-01-22 15:25
I just want to restrain the employee from viewing only his sales on reports.
:(
Does anyone help me to modify the files?
!girl in distress!

**Comment by mckaygerhard** [comment] 2018-01-22 15:39
well try to filter avery sale by his id, the sales table does not store thei id, so maybe a extra column with the id may help, so i recomended see my fork with extra id implementation, 

later one made the id storing each sale view/controler must filter by the employee.

i suspect do you want to made multi-store impelmentation

**Comment by MexasPT** [comment] 2018-01-22 15:55
No multi-store implementation...
The problem is the various vendors see the sales of each other in the employee report.

If it were possible to remove the combobox from the report public / reports / specific_employee and convert it into a textbox, they would have to know the id or name to view the report.

This way the list of all the employees was no longer ... how to do this? It's possible?

**Comment by mckaygerhard** [comment] 2018-01-22 16:15
so them more easyle, take the array that fill's the combo box, if the array its not the id of the admin remove all the elements and will with one only, the current employee.. also this can be a feature ... great idea!

**Comment by odiea** [comment] 2018-01-22 18:50
In Employee permissions have you removed his permission to see Employee and Employees Reports?

**Comment by MexasPT** [comment] 2018-01-22 21:50
I want them to access the reports, but only to them

**Comment by MexasPT** [comment] 2018-01-22 22:14
Hi @mckaygerhard 
Can you tell me how?

**Comment by mckaygerhard** [comment] 2018-01-22 22:29
ok i can tell you some tips and code parts but give me 36 hours please to sync my already  task

**Comment by MexasPT** [comment] 2018-01-22 22:33
ok.
:)
👍

**Comment by MexasPT** [comment] 2018-01-26 15:49
Hi @mckaygerhard
Can you tell help me now?

**Comment by mckaygerhard** [comment] 2018-01-26 23:08
yeah .. firts of all we got a controller, a model and the views (under employee directory), 

you basically onl y wants to an employee only can see their own things (sales or reports)

well , lets see tables, ospos_sales have a column named "employee_id" so in the model of the reports sales and in the sales summary report model, added a filter by the current id of the current employee session active. That's in general lines.

so in the controller, Reports, in the summary_sales you can see the filters as a array variable named "inputs" well here you must added the employee id also.. that's all.. easy..

**Comment by mckaygerhard** [comment] 2018-01-26 23:13
yeah .. firts of all we got a controller, a model and the views (under employee directory),

you basically onl y wants to an employee only can see their own things (sales or reports)

well , lets see tables, ospos_sales have a column named "employee_id" so in the model of the reports sales and in the sales summary report model, added a filter by the current id of the current employee session active. That's in general lines.

so in the controller, Reports, in the summary_sales you can see the filters as a array variable named "inputs" well here you must added the employee id also.. that's all.. easy..

i understand why @marcellusmontilla get laught of people about "complicated" or why @daN4Cat  are "too busy", i not so smart and take me 4 days to solve how do that, ok maybe its easy for them but not was for me or for you @MexasPT or for any that wantssome tips and ways to get into the code.. we are not developers but we wants to make some modifications as users... that's why private companies  always won over opensource solutions.. the support to the users..

**Comment by januaryramadhan** [comment] 2018-01-27 04:06
i have installing ospos from latest release then i upgrade it to newest
ospos master in github, but if i start ospos, it just show a blank page. im
using php 7.1 and mysql 5.7

**Comment by mckaygerhard** [comment] 2018-01-27 04:50
hi @januaryramadhan do you send a new (very popula now) issue about that (very popular) problem?
please fill a new issue, read carefully the (very complicated) template and do not mix things ..

if not, and you are agree that i said, can open it in other place and i'll try to help you ..

**Comment by daN4cat** [comment] 2018-01-27 15:36
@mckaygerhard, not sure what your concern is about @marcellusmontilla "getting laughed at", because if I look at #1753 and #1722 we answered his questions and I even removed something he spotted.

Again, bear in mind that we inherited this code from an original design made 8 years ago with no documentation at all, we all learnt the hard way, but we polished **A LOT** and added features.

With regards to open source, it leaves if people take and work on it, spending less time winging about it and do something about it. The so called "can do" attitude.

I didn't come here to "help" with this sitting and saying "can you do this for me?", "can you do that for me?", "it doesn't work".

I took and moved OSPOS with @jekkos and @odiea to the next level (3.x version, quite a lot of bloody work late at night taking time off my personal life!! 2 years now) and then thanks to @SteveIreland and @objecttothis and other few that contributed some features we added more to it.
@SteveIreland spent a lot of time to bring all the Tax feature to a good level and value, a great job and very tricky to get right. Also all the invoice feature and management.

And all of this free for you all to use but not to rebrand as yours as many do behind the scenes. And I know there are many. Selling it as it's theirs (because they spend the time hacking the footer not developing a feature at all), not even coming and paying a beer or say a thank you.

**Comment by marcellusmontilla** [comment] 2018-01-29 04:54
@mckaygerhard I apologize if my "side" reactions offended you in any way. To be honest about it, let me say that I always open all issues that you participate in. I find them amusing (and yes, I smile to myself). I don't really know what you understand about open-source and getting the benefits of someone else's work. For me, I'm just thankful for the hard work these developers have given to this project. I agree on you in some points that it is not the best work in github but it is polished over time like a diamond in the rough. I know you have the intent to polish this work and English makes it hard for you to communicate your point. I understand that you like the "inconvenient truth" approach but you might want to use better words. Again, my apologies.

**Comment by MexasPT** [comment] 2018-01-29 10:22
Hi @mckaygerhard
I basically  want to an employee only can see their own things (just in reports / specific_employee)
I try to change the code in Line 23:

`$this->config->item . "  $user_info->first_name $user_info->last_name" . ($this->input->get("debug") == "true" ? $this->session->userdata('session_sha1') : ""); ?>`

Can you tell me how to change it? 
I'm desperate!

**Comment by mckaygerhard** [comment] 2018-01-29 11:55
umm @MexasPT seems you not are very common to the source code.. to do not extend the planation i'll try to write to you a very basic changes and you made the rest..

respect "opensource" well my priofile talks by it selft.. i'm not developer but i help so much to mamny people and contribute with code..  so 

@daN4cat respect the "work" recommended to read https://www.google.com/url?q=https://www.chelipinedaferrer.com/2008/11/12/%25c2%25bfque-hace-que-un-proyecto-y-su-plataforma-de-desarrollo-fracase/&sa=D&ust=1516848082071000&usg=AFQjCNF5iqIWBpayW304CmS3QQVoxygTTQ too much work can be to the trask due  that misctakes: unflexible requeriments, no minimal documentation and no minimal organization, very present in ospos..

i offer many times the solution to the very common problems here.. we need ajust the documentation also we need to ajust to better the very complicated template of the issues.. for that there's a pull request, please analize it ..

also i try to colaborate with some corrections to spanish and russian translations as can all see it

**Comment by nerv55** [comment] 2018-01-29 14:45
@MexasPT  It's better for you to contact one of  main developers and pay him for the modification that you want, that way you spend less time asking around and more time doing business it's win-win situation, you win, your costumer win, the developer win. I'm sure for the right price they are willing to help you. in the end is all about the money.

**Comment by MexasPT** [comment] 2018-01-29 15:18
If it was to pay, I had not come here to discuss my problem, I would have gone directly to the developers and opted for a paid solution ... For some reason I support open source solutions ...

If my "problem" has a "simple" solution and someone is helping me, I appreciate and value those kinds of actions!
If @mckaygerhard wants to help me, it only seems good ... not only because he will spend his personal time to help me, but he will surely help many others in this situation and create a new functionality ...

**Comment by MexasPT** [comment] 2018-02-02 12:02
Hi @mckaygerhard
Can you give me a hand? 

I just want to change one thing: the specific report_employee!
What I have to change in the "specific_input" file so that the result is always the same as the logged-in user.

Please help me to change the file in question...

**Comment by mckaygerhard** [comment] 2018-02-02 12:35
sorry for late, was in a hurry, the file you said are not, you only wants to see own reports, so the query made by the model (see application/model directory reports and see each model) by example, if you want only sales of current employee, obviously first must be parsed from the controller `summary_sales` (please the id of the employee only) to the model and then in the model `reports/Summary_sales`  due you "added" also the id of the employee to the `$inputs` the parent select will be filtered by the employee, but if you wish to do more manually, erase the contents of the `_select` method and make your proper query, of course must be same columns of parent/original ..

recomended to added to the controller `$this->output-profiler(true)` (umm i dont remenber this exact line) to see all the "back" made things and ease the develompent.. (if you enable the profiler some jquery will not work, but its a crap)

**Comment by MexasPT** [comment] 2018-02-02 12:59
Hi @mckaygerhard.
How can i contact you ?

**Comment by mckaygerhard** [comment] 2018-02-02 13:20
i have added to a dummy project to see your mail in another way.. please repond the request of join to xmpp project in my namesapace of github..

**Comment by MexasPT** [comment] 2018-02-02 15:15
Added. :)

**Comment by mckaygerhard** [comment] 2018-03-05 15:23
hi @MexasPT i still working on that, but currently has some coding problems. i already know you are in hurry be patient.. its not difficult but i'm not a developer of js or jquery and i try to setup the UI enployyee view for right responsive ..

**Comment by mckaygerhard** [comment] 2018-03-20 18:34
hi @MexasPT sorry for late, i finished the CxC (account payable) .. the code need some improvements..

well i'll adopted this issue and added such funtionality, also due some behavior are not logic like the issue #1898 and #1894 (this last are from guindowser user puff)

i'll made now the code and made a pull request due i gain some experience in the code and try to do my best, the work will be in a specific branch named https://github.com/codeigniterpower/osposweb/tree/osposweb-feataccess

**Comment by mckaygerhard** [comment] 2018-03-25 05:58
hi @MexasPT i send you a email with details, please test and respond me with feedback about it in private email..

**Closed** 2018-04-14 14:30 UTC
Labels: enhancement, question
