### ISSUE TITLE
Login Form has a captcha with red text on Demo Server -BUG

### ISSUE THREAD

**Issue by rodigilbergonzalez-4th** [opensourcepos/opensourcepos#2138] opened 2018-09-13 13:38 UTC
![image](https://user-images.githubusercontent.com/6492544/45491795-97585400-b738-11e8-9388-db490a23a90a.png)

I don't this is an expected behavior, but if it does just ignore this issue

**Comment by SteveIreland** [comment] 2018-09-13 14:29
Reopened because #1443 should have completed the Captcha change and I agree that the "testing purposes only" shouldn't actually appear.  Will need to research and find out what's actually going on.

**Comment by SteveIreland** [comment] 2018-09-13 15:06
Okay, did a bit of research and realized that a site key is required for Captcha to work.  I'm guessing that @jekkos is installing a test only site key for demo, so this is the expected behavior for demo when the Captcha feature is enabled.  Closing ticket again since this is NOT an issue.

**Closed by SteveIreland** 2018-09-13 15:06 UTC
