### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2485] opened 2019-07-05 20:48 UTC
I think we currently only have 2 (or 3) remaining issues open to finish 3.3.0, so think we're almost good to go there. Might be better to release so we get more users using the software and then do fixes in case of critical issues.

**Comment by objecttothis** [comment] 2019-07-05 20:56
Agreed. On Monday I should be able to get to the bottom of the empty report problem.

**Comment by objecttothis** [comment] 2019-07-09 06:07
#2471 is a big enough deal that if it isn't isolated to my system, that we should not release 3.3.0 until it gets resolved.  I just need someone to duplicate the issue to try to confirm that this isn't isolated.  It only seems to affect migrated databases.  New database installs are fine.

**Comment by daN4cat** [comment] 2019-07-09 09:02
I've migrated my 1.1 database twice and work fine.

**Comment by objecttothis** [comment] 2019-07-09 10:13
wow, from 1.1 to 3.3.0.  Nice.  So, I'm guessing there are a few differences between 1.1 and 3.2.3.  Were you using any custom fields?  I don't think custom fields were introduced until 2.x.  I wouldn't guess that would make a difference since the reports don't draw from those fields.  If it's just my setup and no one else can replicate then let's release 3.3.0.  What I do know is that if there is a problem that is affecting more than just me, then potentially many people migrating from 3.2.3 will have a problem.

**Comment by daN4cat** [comment] 2019-07-09 10:49
I assume many already upgraded from 3.2.3 to 3.3.0 because we dragged this release for so long.
But we need to find a way to simulate your type of upgrade.
@odiea has custom fields, not sure he did any fresh reupgrade in recent time to check everything is fine?
But if nobody else can reproduce you really need to help here and find the root cause.

Yes I still have a 1.1 live and I'm waiting for 3.3.0 to be release to finally upgrade that old system.
I have 3 custom fields that were added before 2.x, so I brought that part of the code over and kept my 3 fields and not using the attributes because I have some custom business logic build around them.

**Comment by daN4cat** [comment] 2019-07-09 10:52
That to say that after 3 years of work on OSPOS I will finally migrate my system.
I'm doing dry runs to make nothing goes terribly wrong as you can't halt a running business.

**Comment by objecttothis** [comment] 2019-07-09 10:59
> But if nobody else can reproduce, you really need to help here and find the root cause.

Perhaps you aren't meaning it this way, but I'm reading this as you saying that I'm trying to pass the work required for figuring out what's causing this off on someone else.

I am committed to figuring out the source of the problem regardless of how the problem got started because it's preventing me from migrating my installs to 3.3.0.  It's just that someone else being able to recreate the problem is an important part of the equation.  If others have the same issue then I don't need to waste time looking at my FAMP stack and server hardening as potentially a cause and can spend my time looking into the code and database to find the source.

**Comment by objecttothis** [comment] 2019-07-12 11:11
OK, I created PR #2490 to correct the problem with empty reports.  See #2471 for more details.  Please see my comment on the PR before merging because we have a decision that needs to be made regarding what to patch and what not to patch.

**Comment by objecttothis** [comment] 2019-07-18 10:33
Also, I am traveling between now and October 15th and will have minimal time to make commits unless there is a bug I caused which is preventing 3.3.0 from releasing.

**Comment by daN4cat** [comment] 2019-07-18 15:47
Okidoki.

**Comment by SteveIreland** [comment] 2019-07-19 12:26
A couple of days ago I mentioned on another issue that when I downloaded and installed the latest version of OSPOS from bintray I stumbled across an issue with the display of items.  When I added an item it was not listed (although it was successfully written to the database).  I didn't have time to chase that issue down at the time.  But I'll try to replicate it this weekend and identify the source of the problem.  If someone already knows about this please let me know.

**Comment by jekkos** [comment] 2019-07-19 13:46
Hi Guys, also leaving on holidays next week, I had quite a busy week so not a lot of time to wrap this up. Indeed @SteveIreland this seems to be something we need to check first.

**Comment by daN4cat** [comment] 2019-07-19 13:48
Hope it's not related to the issue with %, right?

**Comment by ronaldhuynen** [comment] 2019-07-31 19:16
About the issue that Items are not added in the Items module:

I also installed the latest master from Bintray ( 3.3.0 - ac6d5e) and used a new and clean database.
After the install, I succesfully created and updated 6 different items. Everything worked fine. But after I created an Attribute Decimal type, the Item list was completely empty. When switching off the visibility of this Attribute Decimal type for the Item module (by updating this attribute in the Attribute module). the Item lists has all the items back again. The Sales and Receivings options can be set to visible without any problems. All looks good in the actual database. Looks like the filter of the Item list is not working properly in combination with the the Attributes types?

**Comment by objecttothis** [comment] 2019-07-31 20:41
> 
> 
> About the issue that Items are not added in the Items module:
> 
> I also installed the latest master from Bintray ( 3.3.0 - ac6d5e) and used a new and clean database.
> After the install, I succesfully created and updated 6 different items. Everything worked fine. But after I created an Attribute Decimal type, the Item list was completely empty. When switching off the visibility of this Attribute Decimal type for the Item module (by updating this attribute in the Attribute module). the Item lists has all the items back again. The Sales and Receivings options can be set to visible without any problems. All looks good in the actual database. Looks like the filter of the Item list is not working properly in combination with the the Attributes types?

Can you provide a screenshot of the problem?  It's unclear to me whether you are saying that the attribute you created (column) is showing up empty or no rows are showing up in the table at all.

**Comment by ronaldhuynen** [comment] 2019-07-31 21:58
My Attribute Decimal type is called 'Timebank.cc H'. 
Screenshots: first with the Attribute set to not visible, which makes all items shown in my list. 

![Screenshot from 2019-07-31 23-21-02](https://user-images.githubusercontent.com/53010464/62249272-4a31af00-b3ea-11e9-8894-85c4d7c0d777.png)

![Screenshot from 2019-07-31 23-20-34](https://user-images.githubusercontent.com/53010464/62249638-2cb11500-b3eb-11e9-972f-fbeaff51fba1.png)

Following screen shots: with the Attribute type set to visible for the Item module. This makes that only a few items are visible in the item list. 

![Screenshot from 2019-07-31 23-21-49](https://user-images.githubusercontent.com/53010464/62249661-35095000-b3eb-11e9-97d6-0b45544f96fb.png)

![Screenshot from 2019-07-31 23-21-16](https://user-images.githubusercontent.com/53010464/62249678-3f2b4e80-b3eb-11e9-901a-452338a78132.png)

I did not select anything in the drop-down filter. It's impossible to see any of the missing items by changing the filter / search options.

![Screenshot from 2019-07-31 23-33-00](https://user-images.githubusercontent.com/53010464/62250166-82d28800-b3ec-11e9-9374-cae041be56e5.png)

I did not yet discover any pattern in why certain items become missing when the attribute type is switch to visible. Removing the attribute type or changing the value to 0 does not have any effect.

**Comment by objecttothis** [comment] 2019-07-31 22:15
When Attribute Visibility "items" is checked I see that there are missing rows that should be there.  By any chance do those items not have a Timebank.cc H attribute value assigned to them?  If so, then it appears that the SQL looking up the results is omitting results without an attribute assigned that is marked as visible in items.  If this is true, then it is a bug that will affect any attribute at least of type Decimal which is selected as visible in the attribute visibility.  I'm on an extended business trip, so I can't look into it now, but I would suggest someone start there if @ronaldhuynen can confirm my suspicions.

@ronaldhuynen you might also want to type in an item name or barcode of an item to the filter that is "missing" to see if it shows up when you search for it or is missing in all cases.

**Comment by odiea** [comment] 2019-07-31 23:28
@ronaldhuynen . Will you please post your system info.

**Comment by ronaldhuynen** [comment] 2019-07-31 23:45
@objecttothis yes I can confirm your suspicions: All missing rows do not have an attribute Decimal type. When I assign an attribute decimal value higher than 0, the item will be shown in the item list. When I remove the attribute decimal value of an item, the item row disappears when I refresh the page. 
When I type in a barcode or item name of a missing item, the list is empty. 

I installed the latest master from Bintray ( 3.3.0 - ac6d5e) and used a new and clean database.

**Comment by jekkos** [comment] 2019-08-04 20:30
@ronaldhuynen I pushed a fix for this, can you try the latest build with your setup and see if it works?

**Comment by daN4cat** [comment] 2019-08-05 05:17
Good, hopefully we are now close to release.

**Comment by ronaldhuynen** [comment] 2019-08-05 09:31
@jekkos I tested your fix (version 3.3.0 - 0a2894) on my setup and yes: the item list now shows all items when the Attributes are switched on for the Items module.

1.
Unfortunately: I can not add any new Items. When I click on the New Item button, nothing happens. This is within the Items module, but also within the Sales module. The Add Item form does not show up.  Same result when I use a fresh and clean database: without any Attributes. When I then create a new Decimal Attribute and switch on/off visibility same result: no new Items can created.

2.
What I also noticed: When I switch off visibility for Items and Sales and Receivings, the setting is saved as everything on. When I switch off only one of the 3, it works ok. 

3.
It is possible for me to edit existing items. But when I update an item, I do not get the usual confirmation message, but this:
![Screenshot from 2019-08-05 10-42-57](https://user-images.githubusercontent.com/53010464/62452769-24513500-b771-11e9-9a76-fe152af82c2c.png)
The database is updated succesfully, and the item list is updated when I reload the Items module.

**Comment by jekkos** [comment] 2019-08-06 21:34
@ronaldhuynen 

For 2: I can confirm this is an issue, looking into it now.

For 1 -3: I woudn't know why that error would appear after the fix. I think it is rather due to a previous setup storing some preferences in the browser that are not applicable anymore.

Can you try to open a new icognito session and add an item again? The setup works fine on my side

**Comment by jekkos** [comment] 2019-08-06 22:20
@ronaldhuynen I have pushed a fix for issue number 2.

I also pushed another commit that fixes a warning that appeared in table_helper (I think this was reported by @odiea before).

**Comment by ronaldhuynen** [comment] 2019-08-08 14:55
@jekkos Yes your latest fix  worked on my setup!
I installed 20190806222050.master.8bca8f from the bintray with a new database. After 1st login I could not create a new Item, but then I tried again in incognito window and it worked.

I also tested it with Decimal and Text Attributes on various items and everything worked as expected. Item search on attributes too. Nice!

**Comment by ronaldhuynen** [comment] 2019-08-08 22:17
@jekkos But unfortunately after I loaded my slightly older (testing) database (3.3.0 ac6d5e) I could not update items anymore. After some tests with the latest and clean database (from 8bca8f) it turned out that:

- Attributes and item list work fine now.

- But when adding another location, existing items can not be created or updated anymore. The form shows, however I can not submit. To make it confusing: the first item could be created, but the second (3rd, 4th, etc) not anymore.

- When removing the extra location, reverting back to a single location, all works well again.

**Comment by daN4cat** [comment] 2019-08-09 06:36
It sounds @jekkos needs to test with multiple stock locations.

**Comment by jekkos** [comment] 2019-08-10 13:39
Hm indeed this wasn't tested before. I will try to have a look this weekend.

**Comment by daN4cat** [comment] 2019-08-10 21:12
Hopefully the last issue to fix for 3.3.0.

**Comment by jekkos** [comment] 2019-08-11 15:00
@ronaldhuynen I have tried to add a stock location and can add new items afterwards without any issues. Could you try to give me the error logging as currently I can't reproduce it. Thanks

**Comment by daN4cat** [comment] 2019-09-05 21:16
It looks like we need to give a kick to #2515 to get this release closed and out. Thoughts?

**Comment by jekkos** [comment] 2019-09-06 06:13
Yes I had a quick look some time ago but couldn't directly reproduce the issue. I'll have another look probably this weekend.

**Comment by jekkos** [comment] 2019-09-06 06:16
Also I might need to take a look at #2521

**Comment by daN4cat** [comment] 2019-09-06 09:28
Thanks, let's close this release. There is also the location issue, I pinged you in that.

**Comment by daN4cat** [comment] 2019-09-09 21:27
Hopefully #2522 is sorted.

**Comment by jekkos** [comment] 2019-09-25 06:41
To my knowledge there's still one issue to test and we're good to go for 3.3.0. I'd also like to mention that I'll be travelling through Asia october-november so I won't have time to do any bugfixes (as won't take a laptop with me). So it would be good if we can put this release to an end this or next week!

@daN4cat maybe I can consider giving you access to the weblate / demo server so you can intervene in case it's needed?

**Comment by daN4cat** [comment] 2019-09-25 08:30
We wrap up this weekend and release 3.3.0. After that we will put on hold things until next year. Any bug fix will be dealt for sure.

Yes, it would make sense to get access to those tools in case something falls over.

Can you please check if any translation needs a push? Although I understand everything is automatic.

**Comment by WebShells** [comment] 2019-09-25 09:49
Actually there are some ar strings i added lately, i can handle weblate and demo server part...

**Comment by jekkos** [comment] 2019-09-25 11:07
@dan4cat sometimes the push gets stuck due to wrong permissions on newly added files. I guess that should be solved by setting umask be in one way or another. I'll have a look on case it happens again.

So let's say no planned new features for upcoming 3.4, but that might not include plans of the other contributors here

**Comment by mckaygerhard** [comment] 2019-09-25 11:41
hi guys.. ok with release but there's still two issues heppened related to items screen, sorry for bad news from me!

**Comment by objecttothis** [comment] 2019-09-25 13:39
@jekkos at the end of October when I return I expect to finish the CLCdesq connector plugin. Is there a reason why that can't go into 3.4?

**Comment by daN4cat** [comment] 2019-09-25 13:42
@objecttothis it can go to 3.4 yes. But I don't commit any time on OSPOS past 3.3.0 until next year. I'll help with reviews where I can.
If I find some free time I might work on something.

**Comment by SteveIreland** [comment] 2019-09-25 15:52
So we are clear to submit pull requests as long as we don't expect them to be merged until next year.  That sounds fair enough.

**Comment by objecttothis** [comment] 2019-09-26 14:50
@SteveIreland I think if @jekkos is around and code reviews can be done on pull requests then pull requests can still get merged into the master.  If I understand correctly, @daN4cat is just taking a hiatus from committing time to opensourcepos minus code reviews if he can.

**Comment by SteveIreland** [comment] 2019-09-26 15:01
That's not my understanding.  I believe that the intent is to avoid merging any new features except serious bug fixes which would go out as 3.3.1.  But I could be wrong ... it's happened once before.  :-)

**Comment by objecttothis** [comment] 2019-09-26 15:26
You're probably right. I've missed large swaths of the conversation due to my travelling.

**Comment by jekkos** [comment] 2019-09-26 19:16
The time to check stuff will also be limited on my side. At least I wont be able to work on new features as I won't take a laptop with me. So it will only be an occasional check from my phone. After pushing 3.3 out we will probably have some time in which we'll have some feedback on bugs, etc..

**Comment by daN4cat** [comment] 2019-09-26 21:09
Also I'm not sure how far we can go with current OSPOS architecture.
The current approach is old fashion and we should have a clean API with a thick client and a mobile app.
Sale register is really ugly with complete page refreshes.
We have just done a face lifting with the migration to Bootstrap 3, but the rest is still old.

**Comment by objecttothis** [comment] 2019-09-26 21:13
I'm all for having a mobile app.  It's on my development list.

**Comment by WebShells** [comment] 2019-09-26 21:37
I agree @daN4cat alot of features and code improvements were applied, yet the main register architecture specifically is becoming somehow old with the refresh thing... @objecttothis a native mobile app with BT printing feature is on my list too, but that's only related to what we currently have... Nothing related to any performance improvements.

**Comment by daN4cat** [comment] 2019-09-28 19:55
I would say that we are ready to release.

Please check README.txt, WHATSNEW.txt and let me know if you are fine.
I'll prepare the release text, ready to publish it once we are fine with the preparation.

**Comment by daN4cat** [comment] 2019-09-28 20:39
Last touches and the text for the release is ready.

@jekkos have you checked weblate? Is everything right and submitted in terms of translations?

**Comment by WebShells** [comment] 2019-09-28 20:47
@daN4cat i am working on an auto installer for cpanel users, can we wait so we can include into this release? Since all people will be downloading stable releases, it might help lower installation issues for some unexperienced users... So if we can do the release by tomorrow it would be great... Will finish working on it with @Jekkos tonight...

**Comment by daN4cat** [comment] 2019-09-28 20:54
@WebShells the plan was to release tomorrow, latest Monday in any case.

**Comment by erastus** [comment] 2019-09-28 23:22
> I would say that we are ready to release.
> 
> Please check README.txt, WHATSNEW.txt and let me know if you are fine.
> I'll prepare the release text, ready to publish it once we are fine with the preparation.

Need to add WHATSNEW.txt fixed sales discount.

**Comment by WebShells** [comment] 2019-09-28 23:28
Added... 

> > I would say that we are ready to release.
> > Please check README.txt, WHATSNEW.txt and let me know if you are fine.
> > I'll prepare the release text, ready to publish it once we are fine with the preparation.
> 
> Need to add WHATSNEW.txt fixed sales discount.

**Comment by daN4cat** [comment] 2019-09-29 05:16
Note to myself: add new docker installation guideline.

**Comment by jekkos** [comment] 2019-09-29 09:00
Weblate is uptodate. All translations should be merged.

**Comment by daN4cat** [comment] 2019-09-29 12:36
> Note to myself: add new docker installation guideline, name of the logo designer in license file.

Done

**Comment by daN4cat** [comment] 2019-09-29 12:37
@jekkos @WebShells can we release? Anything else we need to wait? I know there is this cpanel thingy but I don't want to hold this release forever even considering that tomorrow is the last day of September and we are 9 months late compared to the initial milestone of end of 2018!

**Comment by WebShells** [comment] 2019-09-29 12:42
@daN4cat if you can have a fast look on the invitation I've sent, i guess if we edit minor things needs like an hour, we can merge and release... If not we can keep it for the next one supporting several installations scenarios, no problem 👍

**Comment by daN4cat** [comment] 2019-09-29 13:21
@WebShells I would keep it separate in your github space at the moment and we can reference it from the installation guideline.
In this way you can have a bit of more time to test it and if all fine we integrate it in 3.4.0.
I'm concerned that to test all of that might take time, with people asking questions and etc., so a release at the last minute is not the best option.

**Comment by daN4cat** [comment] 2019-09-29 13:23
You can make it part of opensourcepos space as separate repository, then reference it.
Please amend the .md files to contain reference to your new tool, I'm leaving now for few hours and I don't have the time to add the changes.

**Comment by WebShells** [comment] 2019-09-29 14:12
You are right, totally agree... Will add to installation section so we can test further and have several feedbacks regarding issues, etc... Will publish the file and ready for any changes/fixes.

**Comment by daN4cat** [comment] 2019-09-29 16:16
By the way, there is a bit of a circular dependency if you want to embed it in OSPOS. The release in bintray will not be valid until you tag the master version and your script depends on a specific release. So you can version all together because it's a chicken and egg issue.

Better to keep the installer separate unless you work out a means to solve that problem.

**Comment by WebShells** [comment] 2019-09-29 16:30
> By the way, there is a bit of a circular dependency if you want to embed it in OSPOS. The release in bintray will not be valid until you tag the master version and your script depends on a specific release. So you can version all together because it's a chicken and egg issue.
> 
> Better to keep the installer separate unless you work out a means to solve that problem.

@daN4cat that's why i edited the link to download from Github releases. The links of releases won't ever get expired i guess, and will be updated after every official release. This will fix the situation...

**Comment by WebShells** [comment] 2019-09-29 17:15
@daN4cat We can go forward with the release, from my side everything is set... @jekkos any editions?
@opensourcepos/org Thank you for all your hard work, commitment, and invaluable contributions to keep this project running... 
Moving to a next stage with more exciting features and additions for v3.4 !

**Comment by daN4cat** [comment] 2019-09-29 18:16
Sounds good, starting the release machine.

**Comment by daN4cat** [comment] 2019-09-29 18:32
Done, the new release 3.3.0 is now out: https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.0

Thank you all for the great work and we can now enjoy a bit of rest, or keep moving.
Before merging / changing anything we need to wait a bit of time and then the first step is to change the version in master to be either 3.3.1 (if bug fixes are required) or 3.4.0 if all if hunky dory and we can work on the next wave of new features.

With regards to the latter it would be wise to keep it short and add few features and release.
This release took long because of the big change related to Attributes and various testing and bug fixing. On top of that we had all the Tax theme and various other additions and fixes.

Hope we won't spend another year for 3.4.0.

**Closed by daN4cat** 2019-09-29 18:32 UTC
Labels: enhancement

**Comment by WebShells** [comment] 2019-09-29 18:38
@daN4cat please fix the release notes from "Fixes" Sale Discount to "Fixed"..
Thanks... Enjoyyyy your break, come back the soonest possible!

**Comment by daN4cat** [comment] 2019-09-29 18:59
Done
