### ISSUE TITLE
[bug] urgent System languaje broken setting, does not change

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1858] opened 2018-02-24 05:40 UTC
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted
- OSPOS git commit hash is: 
- PHP version is:      5.6
- MySQL or MariaDB version is: MariaDB 10.2)
- OS and version is:     Linux
- WebServer is:      Apache 2.4

### Issue / Bug  / Question / New Feature

In a fresh install from bintray, to check translations, i noted that in localization tab i cannot "Submit" and save the settings..

I mean, i choose only "Spanish" and no other change and push Submint and no message

i network with F12 in browser only the "localization chek" are in trafic

**Comment by jekkos** [comment] 2018-02-24 09:45
Looks like a key constraint violation to me? Maybe it's trying to add another entry instead of updating the existing one?

**Comment by mckaygerhard** [comment] 2018-02-24 17:01
i dont know the commit of a month ago does not have any problem, also i dont know if the duplicate entry its the root problem of the languaje settings problem..

i try to debug in the network stack in browsers and only have the check of the symbol.. no more request are done! when i hit the Submit button does not happen any thing

**Comment by mckaygerhard** [comment] 2018-02-24 17:13
@jekkos the duplicate insertions are nothig related to this problem, at the network stack i not see a request made when i hit submit, i try to debug in the network stack in browsers and only have the check of the symbol.. no more request are done! when i hit the Submit button does not happen any thing

**Comment by nerv55** [comment] 2018-02-24 17:15
Installation information

OSPOS version is: lasted
OSPOS git commit hash is:
PHP version is: 5.6
MySQL or MariaDB version is: MariaDB 10.2)
OS and version is: Linux Debian 8
WebServer is: Apache 2.4

Confirmed I just reproduced the error, I made a new download of the system and replace my current version, when I try to change the language it does not do anything at the moment of pressing the button submit

**Comment by jekkos** [comment] 2018-02-24 21:07
@mckaygerhard what http status code do you get for your request? Is it 500?
IN that case enable php error log and check further

**Comment by mckaygerhard** [comment] 2018-02-24 21:30
@jekkos there's no http error at all, only does nothing! i push "submit" and only the js check of valid locale are make !
 no error at the apache 2 and i set the codeigniter error log to 4 so if you dessire i check each bintray download until y get the version of ospos that are working..

**Comment by mckaygerhard** [comment] 2018-02-25 01:39
@jekkos the changes made after or on commit ee55be347d69ae6be09174b45ab25cdf6e0f8346 are the root cause.. i tested each bintray generated binary and all after that commit doesn work! 

for corrected usaje we must reverts the changes of ee55be347d69ae6be09174b45ab25cdf6e0f8346 until found a solution of the discution on #1694 respect validation and formats @nerv55

**Comment by daN4cat** [comment] 2018-02-25 14:03
I'm fixing this, I know what causes the issue.

**Comment by daN4cat** [comment] 2018-02-25 14:26
JQuery validator introduced a change with 1.15.0 in the way remote is handled.
I cannot get it to work properly so I'm forced to roll it back to version 1.14.0.

I also fixed one issue with the ajax response that was not set to json and therefore not working properly.

@jekkos if you find the time to understand what changed with that remote: in 1.15.0 would be good, but I could really not find any hint or simple way to get it to work.

**Comment by mckaygerhard** [comment] 2018-02-26 02:32
hi @daN4cat thanks for take care of this... issue #1858

**Comment by mckaygerhard** [comment] 2018-02-26 02:33
hi @daN4cat thanks for take care of this... issue #1858, but take care that the SQL duplicate advertise insertions are not related!

**Comment by jekkos** [comment] 2018-02-26 22:11
OK good that this was sorted out. Subtle regression like this might go unnoticed for some time. Just had a short look at jQuery changelog, there seems to be no notice of any breaking changes... so probably will need to dig into the code to know what is going oni.

**Comment by daN4cat** [comment] 2018-03-04 15:32
I close as I don't see any duplication of database query or else taking place.
Translations are fine.

**Closed by daN4cat** 2018-03-04 15:32 UTC
Labels: bug
