### ISSUE TITLE
LAN_IP/OSPOS/public/login error 404 Page Not Found 

### ISSUE THREAD

**Issue by sadiqtronics** [opensourcepos/opensourcepos#2676] opened 2020-01-11 13:59 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 
- PHP version is: 7.2.18
- MySQL or MariaDB version is: 
- OS and version is: Windows 10
- WebServer is: Apache 2.4.39
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
This may have been answered in another issue, but none of the issues was based on my platform, Windows 10, so pardon me if it appears like a duplication. My issue is that I am able to get to the login page of the web 
![Uploading Capture. 2.PNG…]()
server from a LAN device but upon inputting login details, the 404 error appears. On the localhost, the login works as expected. Please assist. I have searched everywhere with no solution
![Uploading Capture.PNG…]()

**Comment by MatteoGheza** [comment] 2020-01-11 17:52
Can you try with uplading a simple php file in root of web server dir?
`<?php
phpinfo();
?>`

**Comment by sadiqtronics** [comment] 2020-01-11 19:37
> Can you try with uplading a simple php file in root of web server dir?
> `<?php phpinfo(); ?>`

Did that with a test.php file set inside the www folder and still same error

**Comment by WebShells** [comment] 2020-01-11 20:12
@sadiqtronics i believe then the problem is in your environment setup... This doesnt look to be OSPOS related issue.

**Comment by sadiqtronics** [comment] 2020-01-12 08:07
> @sadiqtronics i believe then the problem is in your environment setup... This doesnt look to be OSPOS related issue.

Thanks for your feedback but how is that so? What other environment and I have set my WAMP server well. Should there be a parameter that limits login page from LAN that I am not seeing? Why is the 404 error appearing over LAN access and ok on localhost? That's what I need addressed. It may not be OSPOS related but clearly my intention is to have it work environment notwithstanding.

**Comment by OliviaMourning** [comment] 2020-02-12 00:36
I'm getting the same 404 error @sadiqtronics describes in a fresh local LAMP install. Only difference is, my environment is known to be good as I can successfully get to a php info page and see the extensions are loaded.

**Comment by daN4cat** [comment] 2020-02-12 05:39
Is the rewrite module enabled in Apache?
Are OSPOS folders assigned to the correct user and with the correct permissions?
If installed in a subfolder are the .htaccess files in public folder configured correctly?

**Comment by OliviaMourning** [comment] 2020-02-12 05:53
Rewrite is enabled, OSPOS were originally owned by root. I tried changing it to www-data then back to root, and it's installed in my web root (/var/www/html) with the defalut .htaccess (not modified for a subfolder install).

**Comment by daN4cat** [comment] 2020-02-12 11:07
Are you running code taken from a release package or Git repo cloning?
Also which version?

**Comment by daN4cat** [comment] 2020-02-12 11:08
Also have you checked the file and folder permissions? Not ownership I mean permissions.

**Comment by OliviaMourning** [comment] 2020-02-12 15:18
I'm running 3.3.1 from the release package (https://github.com/opensourcepos/opensourcepos/releases/download/3.3.1/opensourcepos.20191214181241.3.3.1.c786d4.zip), I'll have to check permissions when I am in the office at my computer later this morning.

**Comment by OliviaMourning** [comment] 2020-02-12 16:12
Permissions were set using "chmod -R 755 /var/www/html", same error. It almost seems like it's trying to find the directory /public/login rather than parsing it how CI should. I haven't used CI before, but I read up on it a bit before installing.

**Comment by daN4cat** [comment] 2020-02-12 17:23
And the database connection is fine?

**Comment by daN4cat** [comment] 2020-02-12 17:24
Are you running using http or https?

**Comment by OliviaMourning** [comment] 2020-02-12 17:51
Presumably it is, I used the root account as I am just testing it at the moment. Verified the credentials, db name, etc. are correct in /application/config/database.php. Currently using http. You can see it at http://oliviaa.fortiddns.com/public

**Comment by OliviaMourning** [comment] 2020-02-12 17:52
Also http://oliviaa.fortiddns.com/public/test.php to see my info.

**Comment by bamne123** [comment] 2020-02-12 23:40
I have used Local Docker Installation, I also face 404 for `http://localhost/public`.

**Comment by daN4cat** [comment] 2020-02-13 08:13
Docker local install takes some time to start up and run.

**Comment by daN4cat** [comment] 2020-02-13 08:19
@OliviaMourning can you please check Apache error log and see if it logs anything about the problem?
Also please make sure MySql/MariaDB is properly connected. Please search past issues because I remember similar problems due to database misconfig issues.

**Comment by OliviaMourning** [comment] 2020-02-19 22:09
@daN4cat No errors in the Apache logs, just verified the database credentials. It looks like it may be working after editing /etc/apache2/apache2.conf to set AllowOverride to All.

**Comment by OliviaMourning** [comment] 2020-02-20 06:56
@daN4cat So it looks like it should be working (no more 404), but the database migrations are failing now. Apache logs (I've tried logging in a couple times, waiting for each to finish completely before trying again) are here: https://pastebin.com/S61A9Mdt

**Comment by daN4cat** [comment] 2020-02-20 07:16
You mean database migration of an old database or new empty one?

**Comment by OliviaMourning** [comment] 2020-02-20 07:19
A new database, I just ran the database/database.sql to create the structure before attempting to login.

**Comment by daN4cat** [comment] 2020-02-20 07:40
Is the database user allocated to ospos granted of all the privileges like create and delete tables and etc.?

**Comment by OliviaMourning** [comment] 2020-02-20 07:45
Yes, I created a new user and allowed privileges to ospos.*

**Comment by daN4cat** [comment] 2020-02-20 14:09
This is weird... you sure all phone extensions are added?
Also make sure migration folder and sub folder are accessible to web server.

**Comment by OliviaMourning** [comment] 2020-02-20 14:45
I just double checked, and the only one that isn't there is openssl. I've tried installing it through apt-get but can't seem to find it. www-data has ownership of all files/directories in /var/www.

**Comment by OliviaMourning** [comment] 2020-02-20 17:41
I actually just deleted the whole database and ran the sql file again. It appears to be working now, not sure what went wrong but I'm guessing the initial database.sql import failed in some way originally. Thanks for the help!

**Comment by daN4cat** [comment] 2020-02-20 17:43
Great, I was really running out of suggestions...
I need to look up all these 4ex and 5ex issues and add them to the FAQ.

**Closed** 2020-02-20 17:43 UTC
Labels: question

**Comment by discapacidad5** [comment] 2020-03-09 23:32
> @ daN4cat No hay errores en los registros de Apache, solo verifiqué las credenciales de la base de datos. Parece que puede estar funcionando después de editar /etc/apache2/apache2.conf para establecer AllowOverride en All.

I want to inform you that I was looking for the same problem for many hours and this simple step solved all my problem.

**Comment by daN4cat** [comment] 2020-03-10 08:40
So it was the AllowOverride All issue ???

**Comment by discapacidad5** [comment] 2020-03-10 18:55
> So it was the AllowOverride All issue ???

I did several tests I installed several times even several versions have the tutorial do not specify that this should be done but it is important because otherwise you already passed the system after you put the password I show an error page in login So you left here a copy of the modification that must be done to make everything work.

`#nano /etc/apache2/apache2.conf`

CTRL + w   search  ` <Directory /var/www/>`

Replace the following code.

```
Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

```
for this other

```
Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

```
then restart Apache

`sudo /etc/init.d/apache2 restart
`

**Comment by daN4cat** [comment] 2020-03-11 11:47
Thank you for the clarification

**Comment by gengyunxiang** [comment] 2021-03-27 01:05
Nginx NOOOO!!!!
Apache OK!!!
Solve the login 404 problem ospos and opensourcepos

**Comment by lauragamarra** [comment] 2022-08-14 20:57
Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29 Servidor en localhost Puerto 80
tengo ese problema al iniciar en el navegador
