### ISSUE TITLE
Discount per item

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1824] opened 2018-02-10 23:42 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:3.2.0
- OSPOS git commit hash is: 
- PHP version is:      7.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Question / New Feature
 
Is there a way to show discount per item in quotes/invoices? In sale register there's only discounted total, but customers like to see discounted price per item, especially when we can make a discount for every item individually...

Thank you.

**Comment by odiea** [comment] 2018-02-11 21:40
It appears to me Quotes already has that feature.

![2018-02-11 14_38_39-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36078867-744c3348-0f39-11e8-9499-88a7bae279d9.png)

**Comment by dvidic** [comment] 2018-02-12 09:18
@odiea tnx for reply.
No it does not have that feature. You entered quantity 1, so of course you get discounted price per item. Try with quantity >1.

**Comment by odiea** [comment] 2018-02-12 15:55
If you want each item to be seen check item has serial number in Items.

**Comment by dvidic** [comment] 2018-02-12 22:33
That's not good solution because if item has serial item I can add only quantity 1 for each individual item.... Only thing I need is another column with discounted price per item...(discounted total/quantity)

**Comment by odiea** [comment] 2018-02-13 00:25
Good luck with this.

**Comment by dvidic** [comment] 2018-02-13 08:01
@odiea Yes, exactly that! How to get it?

**Comment by odiea** [comment] 2018-02-15 12:14
Try it and see if this works for you. application/views/sales/quote

[quote.zip](https://github.com/opensourcepos/opensourcepos/files/1727573/quote.zip)

**Comment by daN4cat** [comment] 2018-02-17 21:04
This is in master for invoice & quote, printed and email.

Please @dvidic and @odiea test and confirm it's all fine.

**Comment by odiea** [comment] 2018-02-17 22:14
I get the following errors when I try to send a receipt,quote or invoice. I do not know if this is the cause of my relay not working.
ERROR - 2018-02-17 14:21:37 --> Severity: Notice --> Undefined variable: tax_exclusive_subtotal C:\xampp\htdocs\featuremaster3\application\views\sales\quote_email.php 102
ERROR - 2018-02-17 14:24:16 --> Severity: Notice --> Undefined variable: tax_exclusive_subtotal C:\xampp\htdocs\featuremaster3\application\views\sales\quote_email.php 102
ERROR - 2018-02-17 15:05:43 --> Could not find the language line "sales_receipt_no_email (TBD)"
ERROR - 2018-02-17 15:08:11 --> Severity: Notice --> Undefined variable: tax_exclusive_subtotal C:\xampp\htdocs\featuremaster3\application\views\sales\quote_email.php 102

**Comment by daN4cat** [comment] 2018-02-17 22:25
Hmmm I'm now far from my laptop. @odiea do you have time to check the variables? I copied and pasted the code but forgot to check if tax_exclusive_subtotal is actually set in the controllers or else.

**Comment by dvidic** [comment] 2018-02-17 22:27
@odiea , @daN4cat discount per item shows up on quotes/invoices, but not in the register itself. Is that on purpose?

**Comment by odiea** [comment] 2018-02-17 22:54
It's in the controller under reload. The only place this shows is in  quote and work order email files.
![2018-02-17 15_53_10-search tax_exclusive_subtotal](https://user-images.githubusercontent.com/10962177/36346385-bba62b3e-13fa-11e8-9400-e1fd8db19e41.png)

**Comment by odiea** [comment] 2018-02-17 22:56
@dvidic Is there a way to show discount per item in quotes/invoices? In sale register there's only discounted total, but customers like to see discounted price per item, especially when we can make a discount for every item individually... That's why it was not placed in the Register view.

**Comment by odiea** [comment] 2018-02-17 22:56
Thanks for finding the Quote header saying Invoice. A task for tomorrow.

**Comment by dvidic** [comment] 2018-02-17 23:06
@odiea it's not just header, whole document sent on email is not quote....
as for discount per item in register, we can put something like this:
`<th style="width: 8%;"><?php echo $this->lang->line('sales_discount_item'); ?> </th> `

'sales_discount_item' currently does not exist in lang...

**Comment by odiea** [comment] 2018-02-17 23:12
No but this does "sales_customer_discount"

**Comment by odiea** [comment] 2018-02-17 23:36
Try this and let us know how this works. Thanks
[quote_email.zip](https://github.com/opensourcepos/opensourcepos/files/1734261/quote_email.zip)

**Comment by dvidic** [comment] 2018-02-18 00:14
Yep, it sends quote to mail...
TNX!

**Comment by odiea** [comment] 2018-02-18 01:37
@daN4cat  I downloaded a previous version and the issue was in it. I just never checked emailed items.
I don't think the copy and paste changed anything as far as this issue.

**Comment by daN4cat** [comment] 2018-02-18 09:24
OK, I took @odiea's file and committed to master.
Please check quote and invoice + respective emails are fine.

**Comment by daN4cat** [comment] 2018-02-18 09:26
@odiea is there any missing translation to fix?

_Could not find the language line "sales_receipt_no_email (TBD)"_

**Comment by odiea** [comment] 2018-02-18 12:29
Around line 800 in Sales controller this line exists. Maybe you can figure out what it is suppose to do.
```
public function send_receipt($sale_id)
	{
		$sale_data = $this->_load_sale_data($sale_id);

		$result = FALSE;
		$message = $this->lang->line('sales_receipt_no_email');

**Comment by daN4cat** [comment] 2018-02-18 16:17
That missing string hasn't been there probably at least three years.

**Comment by daN4cat** [comment] 2018-02-18 16:28
Fixed and in master

**Comment by daN4cat** [comment] 2018-02-18 16:29
Please test so we can close this one.

**Comment by odiea** [comment] 2018-02-18 16:49
Nothing in log file after sending an email receipt.

**Comment by daN4cat** [comment] 2018-02-18 17:18
I fixed work order too as it seems to me having the same issue.

@SteveIreland you probably need to review all these email changes to invoice, quote and work_order as there were some issues.

**Comment by odiea** [comment] 2018-02-18 17:24
can you revert this commit. Work orders email was ok and just needed the discount to show. Now the work order is showing it is a quote

**Comment by odiea** [comment] 2018-02-18 17:27
Or just leave it as it originally was and let @SteveIreland  change it if he feels it is necessary to show the discounted price..

**Comment by daN4cat** [comment] 2018-02-18 17:34
ok....

**Comment by daN4cat** [comment] 2018-02-18 17:36
revert even the tax_exclusive_subtotal?

**Comment by odiea** [comment] 2018-02-18 17:38
You could just change the quote to the following and all should be ok.
<div id="header"><?php echo $this->lang->line('sales_work_order'); ?></div>

**Comment by daN4cat** [comment] 2018-02-18 17:40
not sure I follow... line 21 in work_oder_email.php is already like that...

**Comment by odiea** [comment] 2018-02-18 17:42
You are correct. I guess I could not read this am

**Comment by daN4cat** [comment] 2018-02-18 17:44
I reverted the code logic. If @SteveIreland wants to make it consistent or not I leave to him.
In the end I don't need this and neither have time to test, so...

**Comment by daN4cat** [comment] 2018-03-04 17:14
This was fixed so I close.

**Closed by daN4cat** 2018-03-04 17:14 UTC
Labels: enhancement, needsowner
