### ISSUE TITLE
Tax not updating correctly when giving discounts v. 3.3.1

### ISSUE THREAD

**Issue by chrisvell88** [opensourcepos/opensourcepos#2883] opened 2020-07-07 07:38 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4
.Browser: Chrome
.Server Software: LiteSpeed
.PHP Version: 7.2.29
.DB Version: 5.5.5-10.2.31-MariaDB
.Server Port: 80
.OS: Linux nl-srv-web310.main-hosting.eu 3.10.0-962.3.2.lve1.5.26.3.el7.x86_64 #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64
- Selected language is: en-GB

- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi, 

I have set up Tax as inclusive from the System configuration, therefore items have price inclusive of tax. Tax is being calculated correctly however when giving lest say a discount both as an amount and even percentage, although the resulting total is calculated correctly, the tax amount is not being updated, therefore the item is appearing with the original tax amount. 

Ex: if item costs 100Eur with an 18% tax, there is 18Eur Tax...if you give a discount of 50%, it should be 9 Eur tax, but it is still displaying as 18Eur. Can you please look into this? 

ThanksT

**Comment by jekkos** [comment] 2020-07-07 08:22
If you are still on 3.3.1 I would say upgrade to latest master build from bintray to see if that fixes your issue. Some changes were done so it would be nice to hear if this resolves your issue.

**Comment by jekkos** [comment] 2020-07-07 08:23
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200705211435.master.0cb20b.zip

**Comment by SteveIreland** [comment] 2020-07-07 14:09
I'll now be retesting this scenario  for destination based included tax.  :-)

**Comment by jekkos** [comment] 2020-07-16 11:56
@chrisvell88 did you try with our latest version? The more regressions the stronger the case for unit tests..

**Comment by chrisvell88** [comment] 2020-07-16 11:59
Hi,

Yes we tried with latest version but still the same error

Thanks

**Comment by jekkos** [comment] 2020-07-17 07:49
Let's try to have this one fixed in 3.3.2..

**Comment by chrisvell88** [comment] 2020-07-17 07:56
Thanks a lot. Will await your response.

**Comment by SteveIreland** [comment] 2020-07-19 01:18
I replicated the given test scenario using the latest build in both non-destination based tax and destination based taxes:

- 1 item, $100 price with 18% tax and 0 discount results in 1 tax amount of $15.25

- 1 item, $100 price, quantity of 1, with 18% tax and 50% discount results in tax amount of $7.63

I believe that is correct ... but @chrisvelle88 believes the tax should be 9%.  However, that's not the the reported error.

I also tested in 3.3.1 to confirm that the reported issue existed there and it did.

**Comment by SteveIreland** [comment] 2020-07-19 01:20
So if someone who uses internal taxes can confirm for me that this simple internal tax calculation is correct I would appreciate it.

**Comment by jekkos** [comment] 2020-07-19 10:22
@SteveIreland Sounds ok to me. His description was that the tax amount wasnt reduced after discount. I briefly tried it myself and it seems fine indeed.

**Comment by jekkos** [comment] 2020-07-19 10:24
The tax amount in @chrisvell88 example is indeed incorrect for tax inclusive, but i would expect the absolute amount to be halved after 50pct discount. If that is the case then i guess it's not a bug.

**Comment by daN4cat** [comment] 2020-07-19 12:59
Unless there is a specific sequence causing that issue but it should be described in detail.

**Comment by SteveIreland** [comment] 2020-07-19 13:14
There was a sequence which I was able to replicate in 3.3.1, but it was apparently fixed since it was published.  I hope to do a bit more testing on discounts and destination based taxes later today (if I can make the time), but I believe this ticket can be closed.

**Comment by objecttothis** [comment] 2020-07-20 10:24
I'll close and then we can reopen if it turns out the issue isn't resolved.

**Closed by objecttothis** 2020-07-20 10:24 UTC
Labels: bug
