### ISSUE TITLE
how to fix 500 internal server error in new product,please reply me

### ISSUE THREAD

**Issue by thoubic** [opensourcepos/opensourcepos#1895] opened 2018-03-20 07:38 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by marcellusmontilla** [comment] 2018-03-20 07:45
You should attach a screenshot of how and when it happens. Internal server error can be caused by a number of factors in your server (not really with OSPOS).

Hint: please fill up the form, otherwise, this issue will be closed by the admins.

**Closed** 2018-03-20 07:58 UTC

**Comment by thoubic** [comment] 2018-03-20 09:03
this bug are attach,how to fix sir

On Tue, Mar 20, 2018 at 1:15 PM, marcellusmontilla <notifications@github.com

**Comment by thoubic** [comment] 2018-03-20 09:04
i send a  code,can u fix sir,please sir...

**Comment by mckaygerhard** [comment] 2018-03-20 09:53
@thoubic it's clear you come from guindows, and seems you not read and either follow the instructions..

1. you cannot send code to.. due if you made own modifications must read the wiki the part of developer
2. if you have a problem, must follow the instructions, do you read the requirementes in the issue template?

i mean we need some cupe of information from  you as you must follow some guidelines .. that's why this issue was "closed!

ESPECIAL NOTE: mails comes to you due are pure notifications, not a way to send and resolve the issue!

**Comment by thoubic** [comment] 2018-03-27 06:48
hi sir,

   how to add fields in side navbar, please rply me sir

**Comment by shifasiddeqque** [comment] 2018-03-27 07:18
you can add fields Here\application\views\partial/header.php
Cheers









Thanks & Regards
SIDEEQ SHAFI RATHER

**Comment by thoubic** [comment] 2018-03-27 07:31
Hi,

   All modules open for localhost but migrate with live server not opened
in new product and new customer (inspect show *500 internal server error)*

**Comment by daN4cat** [comment] 2018-03-27 12:58
Sorry, we run out of crystal balls and we forgot to pay the salary to the last fortune teller we had in our pay roll.

**Comment by thoubic** [comment] 2018-03-29 10:38
hi sir,

   i have add in header new transport module but not show in nav bar,how to
added in navbar new module
