### ISSUE TITLE
Fixed Discount bug on item kits

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3129] opened 2021-03-13 02:22 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
____________________________________________________
Fixed discount in item kits is not the same in sales module
If we add several items to an item kit, and we choose a fixed discount ..

For example.
If the sum of 4 items add up to $100 with a fixed discount of $5 in an item kits .. saved the total that shows us is $95

if we add this item kits to a sale .. $5 discount will be applied for each product, having 4 items .. the discount will be $20

**Comment by jekkos** [comment] 2021-03-15 09:19
So the discount should be multiplied by the weight of the quanitty / item count for each item here?

**Comment by jekkos** [comment] 2021-04-06 08:45
I confirm indeed that it applies the same fixed discount for every item. We don't have a notion currently of applying a fixed discount on a sale as a whole, so that might be the real issue here?

**Comment by andriux1990** [comment] 2021-04-11 09:29
Thank you very much @jekkos for your answers .. sorry for not answering your comments in time, I have been a bit inactive, the reason is because I have three serous detachments in the central retina of my left eye and one in the right

**Comment by SteveIreland** [comment] 2021-04-11 13:06
Oh my @andriux1990.  I've used a lot of excuses for slow response time but this one trumps all of mine.  I wish you well and hope you recover soon.

**Comment by SteveIreland** [comment] 2021-05-14 12:33
I didn't want this to go into the "won't fix" status and don't want it to be abandoned, so I'm assigning it to myself.

**Comment by jekkos** [comment] 2021-05-14 17:44
Thanks for picking this up @SteveIreland . Any idea how we should tackle this one? It might be easy to fix if we divide the fixed discount by the weighted number of items in the kit when it is added.

**Comment by SteveIreland** [comment] 2021-05-16 12:53
If the kit is priced at the kit level then discount should only apply to the kit itself.  That is a problem that I understand and can fix.  I just tested it and confirmed that it is an issue.  Unfortunately, when I tried to complete the sale an unexpected error popped up announcing that "the item unit price cannot be null" when attempting to add the sale item to the database. 

Then I tried a variation on the test with a discount percent (instead of a discount amount) on the kit then it crashed with an undefined price field error when I tried to add that kit item to the sale. 

This was from the latest snapshot of the master branch so I'll first need to first fix that before I can complete a test ... THEN I can work on this issue.   :-)

**Comment by SteveIreland** [comment] 2021-05-16 15:41
Has anyone ever thought about what should happen if the customer discount type  or the default discount type is not the same as the kit discount type?

I thought not since it was not touched during the addition of support for discount amounts.

Current (and flawed logic) is that if the kit discount was greater than the customer discount (which overrides the system default discount) then it will use the kit discount.  It was only comparing discount values and didn't pay attention to type.

Now that there are two different types of discounts then I'm leaning toward (and will code for unless told to do something else) applying the rule that if the kit discount type is different than the discount type established by the customer (or the system default) then the kit discount will take precedence regardless of whether it will ultimately be greater than or less than the previously established discount - otherwise I will compare the two values and will use the greater discount value.

**Comment by truchosky** [comment] 2021-05-17 16:53
sounds good to me

**Comment by odiea** [comment] 2021-05-18 15:45
@SteveIreland You may want to change the us English tax indicator lang in sales. $lang["sales_taxed_ind"] = "Sales tax ind";
back to $lang["sales_taxed_ind"] = "T";

**Comment by SteveIreland** [comment] 2021-05-22 14:52
I just now updated the wiki documentation to include the following comment about discounts.  That's not in the code yet but will be this weekend unless someone doth protest loudly.

Reference: https://github.com/opensourcepos/opensourcepos/wiki/Item-Kits

1.4 Discounts

Discounts can now be by percent or fixed amount and the discount is applied to each individual item added to the order. Sources for discounts from system configuration which means it is applied to every item added to an order, or from the customer configuration, or from the kit configuration.

When the discount is by percent then that discount percent is added to each item added to the order that is assigned a price. When the discount is by amount then the discount amount gets a bit squirrely. The assumption is that if the discount is by amount then it should NOT be applied to each item. Instead, the discount amount is applied to each item until the amount is depleted. So in effect it is spread across the items. This really only seems logical if you are pricing at the kit level because then the discount amount would be applied to the kit. If the kit price is essentially a charge for packaging then the discount amount might be greater than the price from the kit item. This will result in the discount amount for the kit item cannot be greater than the price so it will be the same as the price (essentially giving the item a zero price). The remainder of the discount amount will be applied to the next item. This is then repeated for the next item until the discount amount is fully depleted.

**Comment by SteveIreland** [comment] 2021-05-22 14:57
@odiea I've made the corrections to a few language files regarding sales tax indicator.  I noticed that a translator accidentally made that change (too easy to do) and a few others followed the pattern.  I took my best guess at trying to identify what the first character of the word "Tax" is in the other languages.   The changes are included in this branch I'm working on, so it will find its way up this weekend.

**Comment by SteveIreland** [comment] 2021-05-22 17:31
Okay, I've created a pull request for all of the changes, but subsequent testing introduced an interesting behavior that someone smarter than me needs to put some thought into.

The core of this issue was to avoid a discount amount entered at a kit level from being applied to every item in the kit.

So what happens if a you enter a fixed discount amount at a customer level?  Well NOW if you use a "quick entry" style kit that simply drops in a lot of items, because it is a "kit", the discount is given to the first item (and my go to other items given the logic that prevents the price from going below zero) but that's it.  The discount applies to the kit

Now to be honest I cannot imagine a "real world" scenario where a fixed discount amount is assigned a customer level - but people do crazy things.

But that is what will happen with the latest pull request.  I'll give it a day for feedback and then I'll go ahead and merge it.

I'll be happy to change the behavior if this isn't acceptable.

**Comment by odiea** [comment] 2021-05-22 19:09
No Bintray for me to download and test. Sorry

**Comment by SteveIreland** [comment] 2021-05-22 19:15
Yeah, I was wondering about that.  I assumed I missed the comment that told us what the replacement for bintray was.  I wasn't going to embarrass myself by asking.  :-)   So now I know there isn't one yet.  There README still says there is one.

**Comment by SteveIreland** [comment] 2021-05-22 20:07
@odiea 

If  you'd like to test this I uploaded a pre-built ospos to a OneDrive shared folder.  This is a zip of the one I was using for development (The only difference is that I reset the database.php configuration file).

The zip file is found at: https://onedrive.live.com/?authkey=%21AHnsYCtXBSoZgyQ&id=B67373CBA5E68CBF%2171035&cid=B67373CBA5E68CBF

I'll keep it there for a few days in case anyone is interested in testing it.  If you decide you want to take a shot at this and have any problems please let me know.

**Comment by odiea** [comment] 2021-05-22 23:45
Thanks @SteveIreland . I downloaded the file and will play with it when I can. But so far looks promising.

**Comment by jekkos** [comment] 2021-05-31 09:18
Fix in master now

**Closed by jekkos** 2021-05-31 09:18 UTC
Labels: enhancement

**Comment by erwinlagu** [comment] 2022-01-09 16:14
Sounds Great
