### ISSUE TITLE
Problems with reCaptcha

### ISSUE THREAD

**Issue by meierrom** [opensourcepos/opensourcepos#3863] opened 2023-11-10 08:05 UTC
Hi folks,

This morning, I did some tests using the demo version on https://demo.opensourcepos.org/ (3.3.9 - c00ff2).

I activated reCaptcha v3 which apparently doesn't work at all.

Then I switched to Challenge (v2) "I'm not a robot tickbox", which is also not working as expected. The problem is, that the user can simply click twice on the Go button and reCaptcha is bypassed.

Can somebody reproduce this?

Kind regards,
Roman

**Comment by jekkos** [comment] 2023-11-10 15:40
#1443 #1496

**Comment by meierrom** [comment] 2023-11-11 06:00
Thanks but I don't see these links being related to the issue.

**Comment by jekkos** [comment] 2023-11-11 14:17
Was recaptcha correctly configured for the demo server? If not then you might not be able to expect it to work properly

**Comment by meierrom** [comment] 2023-11-12 07:23
I just set it up again. Please check it out.

Please remember that it can easily be bypassed by clicking the Go button twice.

**Comment by jekkos** [comment] 2023-11-12 12:02
Last issue on recaptcha I found is #3207. @daN4cat are you perhaps still using it? I'll check it out later on.

**Comment by jekkos** [comment] 2023-11-18 11:55
On demo it seems I cannot login in at all when recaptcha is enabled. I did not try to click twice though.

**Comment by meierrom** [comment] 2023-11-18 13:26
Somebody may have hacked the site or something like that. This issue just
started a few days ago.

**Comment by objecttothis** [comment] 2023-12-12 08:19
@jekkos does the demo automatically refresh and rebuild on a schedule?

**Comment by jekkos** [comment] 2023-12-12 08:24
I would like to have the latest ci4 deployed on Dev again when a push is made.  Last time I checked there was an issue with the credentials config for docker, that will need to be sorted first. 

Plan is to wrap up my open change for the dev env and then take care of this.

**Comment by daN4cat** [comment] 2024-07-18 14:09
Still using it with 3.3.8 and working fine. It's v2 though.

**Comment by daN4cat** [comment] 2024-07-19 16:20
Something I forgot to add, make sure you add the host domain name of IP address to Google reCaptcha site. Without the login page will report an error.

**Comment by jekkos** [comment] 2024-07-19 19:35
@meierrom can you give that a try? I should also add your note to our docs somewhere.

**Comment by daN4cat** [comment] 2024-07-25 08:40
I close this with cannot reproduce. If still an issue, we can reopen it.

**Closed** 2024-07-25 08:39 UTC
Labels: bug
