### ISSUE TITLE
Struk Share by Whatsapp

### ISSUE THREAD

**Issue by cucu02** [opensourcepos/opensourcepos#3289] opened 2021-08-29 06:16 UTC
Hello, Ospos is a very interesting application. But I think with the addition of the option to send receipts to WhatsApp it will be even more stable. Save paper and efficient.

**Comment by jekkos** [comment] 2021-10-04 19:47
Duplicate of #3172

**Comment by jekkos** [comment] 2021-10-04 19:48
Which is another duplicate of #922

**Closed by jekkos** 2021-10-04 19:47 UTC
Labels: enhancement, needs owner
