### ISSUE TITLE
When i delete customers it delete from the software but not from database.

### ISSUE THREAD

**Issue by salarsheikh** [opensourcepos/opensourcepos#2783] opened 2020-04-07 12:14 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.1.9
- MySQL or MariaDB version is: phpmyadmin
- OS and version is: core m
- WebServer is: 
- Selected language is: codeignitor
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello everyone, I have found a bug in the OSPOS that is when i delete the customers it delete from the software screen and shows message that i is deleted but when  i goes to the database it is showing result in it.
I have tried manually but we have to delete first customer record then we can delete people record i dont know why?

Anyone can help me do this or guide me how to do this i want to try this by myself.

Thanks

**Comment by odiea** [comment] 2020-04-07 12:33
Yes Customer uses a soft delete. This means it is marked as deleted but not deleted from your database.

**Comment by salarsheikh** [comment] 2020-04-07 12:41
Why is it so?IS this a bug or it will should goes in this way?

**Comment by salarsheikh** [comment] 2020-04-07 12:45
If this is a bug Can u guide e how to fix that ?

**Comment by odiea** [comment] 2020-04-07 12:48
No it is not a bug. You can change this at your own risk.

**Comment by salarsheikh** [comment] 2020-04-07 12:53
okay can u guide me how?

**Comment by odiea** [comment] 2020-04-07 13:04
No it is not a bug. You can change this at your own risk.

**Comment by salarsheikh** [comment] 2020-04-07 13:06
i wanted to change on my pc can u guide me how?

**Closed** 2020-04-07 17:22 UTC
Labels: question

**Comment by daN4cat** [comment] 2020-04-07 17:23
It's called soft delete and it's normal practice to avoid having tables out of sync.
This is how the software has been designed.

**Comment by salarsheikh** [comment] 2020-04-08 14:18
Ok thanks :)
