### ISSUE TITLE
Subtotal error when Use Destination Based Tax

### ISSUE THREAD

**Issue by wduvan** [opensourcepos/opensourcepos#2771] opened 2020-03-26 15:54 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: b5265870be57f740cd210e327c8b78ae324a2156
- PHP version is: 7.3.12
- MySQL or MariaDB version is: 10.4.10
- OS and version is: Windows 10 Pro
- WebServer is: Apache 2.4.41
- Selected language is: English
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: N/A

### Issue / Bug  / Question / New Feature

Hi, my issue happens when I configure the system to use TAXES in config as "Use Destination Based Tax", this tax not discount of Subtotal, but when I use or configure to use normaly tax use this value its discount of subtotal, attached pictures...

The issue also happens in receipts..

Thanks

![CorrectImageProcess](https://user-images.githubusercontent.com/13259650/77666982-a932ce00-6f4f-11ea-97ef-e89dcb940722.png)
![InCorrectImageProcess](https://user-images.githubusercontent.com/13259650/77666987-aa63fb00-6f4f-11ea-80c0-6f27d907bea9.png)

**Comment by odiea** [comment] 2020-03-27 10:10
It appears that in 1 image you are using Tax included and not in the other image. So both appear to be correct.

**Comment by wduvan** [comment] 2020-03-27 15:42
In both images the system is configured including taxes, please try and tell me

**Comment by jekkos** [comment] 2020-03-27 15:55
no in the first you have `tax included` ticked, in the second image it's not ticked.

**Comment by odiea** [comment] 2020-03-27 16:23
In tax module under Tax Jurisdiction change that to tax included and see if that does it for you.

**Comment by wduvan** [comment] 2020-03-27 20:46
it's always been like this `Tax included`, pleas echeck the image...
![tax_included](https://user-images.githubusercontent.com/13259650/77799105-12930980-7042-11ea-8f3d-fe9d8efae52b.png)

**Comment by SteveIreland** [comment] 2020-03-28 02:04
I'll do some testing over the weekend to see if I can identify the issue.  I have a lot more time available while isolating in the house trying to dodge Covid-19.  ;-)

**Comment by SteveIreland** [comment] 2020-03-28 19:26
I've confirmed the issue and started working on a fix.  Why didn't the 5% tax show up in your example?  Is there something special about it or was it just not added to the item?

**Comment by wduvan** [comment] 2020-03-28 19:34
I don't add tax to item, only 19 for the example

**Comment by SteveIreland** [comment] 2020-03-28 22:44
Okay, I believe I've found and fixed. the issue.  You must be the first person on the planet to be exploring "destination based taxes" in an "tax included" scenario!

I'm going to run through various test scenarios for different tax configurations tomorrow to determine if I've inadvertently broken something else as a result of the change, but since it's actually a rather small fix I believe that's not likely, so I hope to have a pull request for this available by Sunday night.

I'll work with you to make sure its bug free before you use it in a production environment.

It requires a small change to Sale_lib.php and Tax_lib.php

**Comment by wduvan** [comment] 2020-03-29 14:46
Sup, thank you!!!

**Comment by SteveIreland** [comment] 2020-03-29 21:36
Unfortunately when I expanded my tests beyond just the sales component into the reporting area I found that the reports are also impacted and this raises the level of complexity of the change. I'm working on them now, but because the area of reporting is more complex I'll need to be much more careful and not rush it.  So I might not make the Sunday evening publishing deadline previously committed to.

**Comment by SteveIreland** [comment] 2020-03-30 03:34
Definitely not going to make it tonight but I'm making progress.  The Daily Sales and the Detailed Transaction reports seem to be providing valid data again, but there are more scenarios to be tested.

**Comment by SteveIreland** [comment] 2020-04-04 16:08
I submitted pull request #2780 for this.  It impacts tax calculations so someone might want to make sure I didn't break their sales tax calculations and sales reporting. 

If I did, please let me know and I'll apologize and make the necessary corrections.

**Comment by daN4cat** [comment] 2020-04-04 18:17
Hope this didn't revert the fixed I made to the tax included calculations because they were not right.

**Comment by SteveIreland** [comment] 2020-04-05 00:06
I also hope not ... tomorrow I'll look at history to find what it was you changed and confirm I didn't step on it.

**Closed** 2020-06-29 05:25 UTC
Labels: bug
