### ISSUE TITLE
PDF sent Invoices are not showing payments.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2634] opened 2019-12-22 18:08 UTC
OSPOS Installation Info: 3.4.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
» Browser: Chrome
» Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.2.4
» PHP Version: 7.2.4
» DB Version: 5.7.21
» Server Port: 80
» OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

When an Invoice is shown on the screen it looks like the following.

![2019-12-22 10_54_23-Window](https://user-images.githubusercontent.com/10962177/71325501-fe6fc700-24aa-11ea-8ebf-35335261ca01.png)

Ths issue is the sent pdf invoice is currently not showing that any payments have been made.

**Comment by WebShells** [comment] 2019-12-22 18:34
Man... The issue template is very nice 😂

**Comment by odiea** [comment] 2019-12-22 19:30
@WebShells Yes it is and thanks for doing it. I hope everyone will use it.

**Comment by odiea** [comment] 2019-12-22 20:32
Here is the modified version if some brave soul is willing to try it.
[invoice_email.zip](https://github.com/opensourcepos/opensourcepos/files/3992959/invoice_email.zip)

**Comment by SteveIreland** [comment] 2019-12-23 01:40
I noticed that a couple of years ago and just assumed that was by design .... apparently not.  :-)

I looked at the code and it looks good to me and I know you've tested it.  Would you like me to set it up as a pull request?   I'd be happy to do that.

**Comment by andriux1990** [comment] 2019-12-24 13:27
> Here is the modified version if some brave soul is willing to try it.
> [invoice_email.zip](https://github.com/opensourcepos/opensourcepos/files/3992959/invoice_email.zip)

Ok, I'm going to try it

**Comment by andriux1990** [comment] 2019-12-24 13:32
I have been wondering if it is possible that by saving an invoice or resivo in pdf, I can put the name of your default sales id.
Currently what he does is put the name of the page in this case open sourse point of sale.

if they were save with the id or name of the customer very easy to identify them in the storage of the device

**Comment by daN4cat** [comment] 2020-01-03 23:19
@SteveIreland do you want to set up a PR and get this in 3.3.2?

**Comment by SteveIreland** [comment] 2020-01-04 00:28
Yes, I'll take care of this ASAP.

**Comment by daN4cat** [comment] 2020-01-04 10:43
Committed to master as part of PR #2660

**Closed** 2020-01-04 21:14 UTC
Labels: enhancement
