### ISSUE TITLE
Mobile VIEW

### ISSUE THREAD

**Issue by simonaogstino** [opensourcepos/opensourcepos#1866] opened 2018-02-28 08:29 UTC
Hello Team,

is a mobile view available ?
if NO , is it possible to make one for those who want to use the system in an easy way on tablets and mobiles.

REgards
Simon

**Comment by WebShells** [comment] 2018-02-28 08:46
Hello @simon,
Actually the code so far can run on mobile/tablets yet it's not with the best responsiveness maybe it needs some time to release a full responsive theme now...

**Comment by simonaogstino** [comment] 2018-02-28 09:43
Hello,

Yes , it shows the same as the disktop view.

**Comment by daN4cat** [comment] 2018-02-28 09:45
It's in the TODO list since a long time waiting a brave developer to take, work on it and contribute.

This is how far we could get with the energy we had.

**Comment by mckaygerhard** [comment] 2018-02-28 14:23
just modification to the sales view css, no great "TODO" .. just a smart modification:

where the paid part are just below of the items list, making more responsive and usable the interface in the moviles (very few space and the inputs for paid are outside of the screen mobile)

**Comment by mckaygerhard** [comment] 2018-02-28 14:31
@simonaogstino  can be possible, as i explained, @daN4cat just modification to the sales view css, no great "TODO" .. just a smart modification, the problem jajaj its the very complicate developer tools choosen right? note that i can made it, in the css, and the view can be as:

HERE THE RESULTS IN DESKTOP AND MOBILE, my employees are good and happy:

![osposbelow-mobile](https://user-images.githubusercontent.com/1571724/36792901-45feacaa-1c72-11e8-82a5-cc29102b1c3e.png)

![osposbelow-desktop](https://user-images.githubusercontent.com/1571724/36792907-4a3eb634-1c72-11e8-90e6-cdbcdc68cc8d.png)

of course i not work with that complicated bowser npm nodejs etc etc i just use directly the files more easyle and can use directly the repository

**Comment by daN4cat** [comment] 2018-02-28 18:38
So we can close it's done, right?

**Comment by WebShells** [comment] 2018-02-28 18:47
I guess so... At least for the time being..

**Comment by mckaygerhard** [comment] 2018-02-28 18:52
no we cannot close it, the code and the changes are not doe in repository, and i cannot done that, due i dont know how to work tiht that complicated development setup, well @WebShells as your preferer

seems here its more the attention pay to close issues..

**Comment by mckaygerhard** [comment] 2018-02-28 18:57
the issue must be renamed to "fields sales in mobile view are outside of the box", and the solution its made the changes i proposed in the pictures! the changes does not affect the themes! ok

the code and the changes are not doe in repository, so how tis can be closed! ? and i cannot done that, due i dont know how to work tiht that complicated development setup

**Comment by mckaygerhard** [comment] 2018-02-28 19:12
that precisselly my point! if the development evironment were most easy to use, many more contributors can made more code and contributor on necesary issues.. currently i want to made many things but its so comlicated for me that i not are an expert!

that's made the project a project of few manpowers event a project of many contributors.. like M$ does to protect their coding!

**Comment by nerv55** [comment] 2018-02-28 19:33
This is the way it renders on my tablet.

![osposview](https://user-images.githubusercontent.com/26050096/36807788-84aa7cec-1ca2-11e8-87e5-24c9c0267a98.png)

I try to make a change in CCS and JS but as is minified, and I don't find documentation on the wiki.
I was unable to archive the display that I want. even when I Unminify the files, the code is huge almost 26000 lines. 
It will be helpful to have documentation of the function inside de JS and CCS, at least comments, to see what form section is affected by what style, and what JS function control the forms. or split file across more files. that way you don't have to be master in CCS and JS, to make changes to look and feel.
resuming simplified the things so others can contribute.

**Comment by simonaogstino** [comment] 2018-03-01 06:37
@NERV55 I have a client who asked me if possible to have a system with
mobile view , may I have the edited CSS file to test ?

Regards
Simon

**Comment by nerv55** [comment] 2018-03-04 03:41
@simonaogstino sorry for dekay, I was testing movile view. I don't touche the CCS file.

this is what i have so far.

![movileview](https://user-images.githubusercontent.com/26050096/36941845-d9ad2010-1f3a-11e8-9bad-62f39092a021.png)

Modification made in register.php  /application/view/sale  folder  

//////////////////////////////////////////////////// lines 107 to 118
		
			<tr>
			
			
				<th style="width: 35%;"><?php echo $this->lang->line('sales_item_name'); ?></th>
				<th style="width: 35%;"><?php echo $this->lang->line('sales_price'); ?></th>
				<th style="width: 10%;"><?php echo $this->lang->line('sales_quantity'); ?></th>
				<th style="width: 10%;"><?php echo $this->lang->line('sales_discount'); ?></th>
			
				<th style="width: 5%;"><?php echo $this->lang->line('common_delete'); ?></th>
			</tr>



 lines 138 and 139
Comment the echos

lines 179 to 192
comment the values corresponding to table header

**Comment by daN4cat** [comment] 2018-03-04 14:55
This discussion links to #593

**Comment by daN4cat** [comment] 2018-03-04 14:59
To make things properly responsive and work on many different devices and screen sizes you need to work on the bootstrap responsiveness, setting correctly the layout.

A quick win is always possible but the "TODO" I beforehand mentioned is the proper responsiveness of the UI.
The same at the time with #593, it seems a quick on and just add it. But when you test it you see that it impacts web browser and etc.

So it's either a proper job or it stays here as hack suggestions.

**Comment by nerv55** [comment] 2018-03-04 23:15
@daN4cat , yes this is just hack, for that reason you don't see this in pull request for merge, Of course you  are correct about it, but i'm not expert in bootstrap responsiveness I'm reading now to make changes in CCS but this take time

**Comment by jekkos** [comment] 2018-04-05 22:45
Closing this one as it's a duplicate of #593

**Closed by jekkos** 2018-04-05 22:45 UTC
Labels: duplicate
