### ISSUE TITLE
Add support for cash rounding to the nearest 5 cents.

### ISSUE THREAD

**Issue by chrishladky0075** [opensourcepos/opensourcepos#2922] opened 2020-08-14 17:01 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: unknown
- PHP version is: unknown
- MySQL or MariaDB version is: unknown
- OS and version is: ubuntu 18.04
- WebServer is: nginx
- Selected language is: english 
- (If applicable) Docker installation: no
- (If applicable) Installation package for the LAMP/LEMP stack is: unknown

### Issue / Bug  / Question / New Feature

issue relating to the rounding of the total, and change back items. Our province does not use pennies anymore, and we need the system to round the total and change back fields to the nearest 5 cents. please help.

**Comment by chrishladky0075** [comment] 2020-08-14 18:24
i just did a test on your 3.3.2 demo site and it still has this problem.

**Comment by SteveIreland** [comment] 2020-08-17 14:59
This isn't a bug but a new feature request.  However, I suspect that this is no longer needed since chrishladky stopped responding on another issue.   I would have asked if this was a cash only scenario, for which we DO have a cash rounding feature, but it doesn't include support for rounding to the nearest 5 cents.  I'm interested to know if there is any need for this anywhere else other than this unspecified province.

**Comment by chrishladky0075** [comment] 2020-08-17 15:05
Issue persists,  will explain more tomorrow when I can get at the system.

**Comment by chrishladky0075** [comment] 2020-08-18 14:17
This is an issue for all provinces in Canada as the penny was discontinued
a couple of years ago. I live in Manitoba. You're right, this probably
should be a new feature request.

**Comment by SteveIreland** [comment] 2020-08-20 12:33
Question:

If the payment is in cash then it will be rounded to the nearest 5 cents.  However, if the  payment is non-cash then does it still need to be rounded to the nearest 5 cents.

Last time I looked, our current cash rounding logic is dependent on the payment type selected being cash and it rounds to the nearest decimal setting.

**Comment by chrishladky0075** [comment] 2020-08-20 14:04
If debit or credit card, it does not round

**Comment by SteveIreland** [comment] 2020-08-28 02:40
I submitted a pull request for this, but for some reason the build is failing with an odd error message that I do not believe is related to the change.
``Service 'ospos' failed to build: Error parsing reference: "php:7.3-apache AS ospos" is not a valid repository/tag: invalid reference format`

Maybe someone has some insight into that.

However, this was a rather simple addition so if there is a need for this you can review the actual code changes and transfer those changes to your system.

**Comment by SteveIreland** [comment] 2020-08-28 02:49
Normally cash rounding is triggered when in localization configuration, the cash decimals is less than the currency decimals.  The original design would handle the situation where a cash payment was involved, the system would round the amount due, dropping decimal positions to the right of the currency decimals.   With this change, if the currency decimals is the same as the cash decimals AND the cash rounding code is HALF FIVE, then apply cash rounding to round the number to the nearest 5 cents.

**Comment by chrishladky0075** [comment] 2020-08-28 13:12
Thank you I will check it out when I get some time early next week!

**Comment by chrishladky0075** [comment] 2020-09-04 00:06
Can you send me a link to the new code?

**Comment by chrishladky0075** [comment] 2020-09-04 15:21
perfect, thanks

**Comment by SteveIreland** [comment] 2020-09-05 18:34
The link to the bintray zip file is https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200905182155.feature_cash_round_to_mult_5.e15166.zip

**Comment by chrishladky0075** [comment] 2020-09-05 20:34
Thank you

**Comment by chrishladky0075** [comment] 2020-09-09 14:56
works perfectly, thank you so much

**Comment by jekkos** [comment] 2020-10-28 12:29
Not sure if there is a bug in this change or if it's something else causing the issue described in #2975. Let's try to reproduce and fix (if needed)?

**Comment by SteveIreland** [comment] 2020-10-28 15:56
Okay, will do.

**Comment by jekkos** [comment] 2020-11-07 18:48
I'll close this one again let's stick to the discussion in #2975

**Closed by jekkos** 2020-11-07 18:48 UTC
Labels: enhancement
