### ISSUE TITLE
PHP 8.0 error when loading https://localhost/poss/public/index.php

### ISSUE THREAD

**Issue by harshasuraweera** [opensourcepos/opensourcepos#3051] opened 2020-12-22 13:57 UTC
- PHP version is: 8.0.0

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language, and steps to reproduce the bug.
![errors](https://user-images.githubusercontent.com/54607738/102895984-ae478e00-448b-11eb-9091-34842a46425f.PNG)

**Comment by odiea** [comment] 2020-12-22 14:19
Are you using PHP 8 if so downgrade to a 7 version?

**Comment by daN4cat** [comment] 2020-12-23 12:00
PHP 8.0 is not supported yet. It will requires changes for sure, starting from Code Igniter.

**Comment by harshasuraweera** [comment] 2020-12-23 12:06
> You are  using PHP 8 so downgrade to a 7.3 or 7.4 version?

It worked thank you. 🙂

**Comment by harshasuraweera** [comment] 2020-12-23 12:07
> You are  using PHP 8 so downgrade to a 7.3 or 7.4 version?

Solved with 7.4 Thank you

**Comment by daN4cat** [comment] 2020-12-23 12:24
Please leave it open because OSPOS and CI3 don't work with PHP8.0 at the moment: https://github.com/bcit-ci/CodeIgniter/issues/6006

**Comment by daN4cat** [comment] 2020-12-23 12:26
I set OSPOS version 4 because that means we need to swithc to CI4, Bootstrap 4 and who knows what else (e.g. Angular/React/View Frontend, REST API)... 

Wonder if it would make sense to change framework to do all those changes because the upgrade to BS3 and CI3 meant a lot of work!

**Comment by odiea** [comment] 2020-12-23 16:41
I found this on the CI4 site.
Codeigniter 4.0.4 does not support PHP 8 The community are working on update will should likely be Codeigniter 4.1 and all php8 error is getting fixed.

**Comment by daN4cat** [comment] 2021-01-02 21:07
I was still on PHP 7.2 and upgrade to PHP 7.4 and my installation is faster now. I can't imagine how faster it would get once @objecttothis improvements are merged in.

**Comment by objecttothis** [comment] 2021-01-03 17:51
> 
> 
> I set version 4.0.0 because that means we need to swithc to CI4, Bootstrap 4 and who knows what else (e.g. Angular/React/View Frontend, REST API)...
> 
> Wonder if it would make sense to change framework completely to do all those changes because the upgrade to BS3 and CI3 meant a lot of work!

I looked at CI4 and according to them it will me a large rewrite of the code base.

**Comment by daN4cat** [comment] 2021-01-03 19:04
> > I set version 4.0.0 because that means we need to swithc to CI4, Bootstrap 4 and who knows what else (e.g. Angular/React/View Frontend, REST API)...
> > Wonder if it would make sense to change framework completely to do all those changes because the upgrade to BS3 and CI3 meant a lot of work!
> 
> I looked at CI4 and according to them it will mean a large rewrite of the code base. That would not be a bad time to look at other frameworks.

Indeed, I wouldn't consider migrating to CI4 without having reconsidered the whole story here.
Maybe we should start writing down a vision about an OSPOS 4, what would be an ideal target here for a newer and better version?

**Comment by jekkos** [comment] 2021-01-03 19:51
I think that it would be a complete rewrite indeed, probably we could keep the database model to make it backwards compatible (or just evolve that further).

**Comment by jekkos** [comment] 2021-06-23 19:48
From this conversation I thought that upgrading to CI4 would be impossible. There is however an upgrade guide and it seems to be a bit of work, but still doable

https://codeigniter4.github.io/userguide/installation/upgrade_4xx.html

**Comment by objecttothis** [comment] 2021-07-02 19:55
> 
> 
> From this conversation I thought that upgrading to CI4 would be impossible. There is however an upgrade guide and it seems to be a bit of work, but still doable
> 
> https://codeigniter4.github.io/userguide/installation/upgrade_4xx.html

I had also thought that CI4 would involve quite the rewrite since he changed the way many of the functions were called.  I'd say that if it's doable we should consider it, but it sounds to me like it would be quite the task.

**Comment by objecttothis** [comment] 2021-08-10 09:02
> 
> 
> From this conversation I thought that upgrading to CI4 would be impossible. There is however an upgrade guide and it seems to be a bit of work, but still doable
> 
> https://codeigniter4.github.io/userguide/installation/upgrade_4xx.html

@jekkos I just commented on #842 regarding this but after reading the documentation on this, I don't think it would need a complete rewrite, but it does appear that there are syntax changes to the ways that different MVC elements are referenced that will touch almost every Controller, Model and View.  Like I said in my comment there, I would be willing to tackle the upgrade.

**Comment by objecttothis** [comment] 2021-09-14 10:47
I'm assigning this to myself because I think it will be resolved by #842.

**Comment by bhojkamal** [comment] 2022-09-01 05:55
Can we make it to support at least 8.0? It it good to have support on 8.1 too. 
Thanks.

**Comment by objecttothis** [comment] 2022-09-01 07:46
This is resolved in the switch of the codebase to Code igniter 4.x. I am returning from travel in the next few weeks and will resume working on this changeover but without help it's going to be fairly slow.

**Comment by jekkos** [comment] 2022-09-01 22:19
I wanted to take some time to look why the build on the branch is not working, so we can deploy it and give it a spin..

**Comment by jekkos** [comment] 2022-09-01 22:19
> This is resolved in the switch of the codebase to Code igniter 4.x. I am returning from travel in the next few weeks and will resume working on this changeover but without help it's going to be fairly slow.

Glad to hear you will be back btw!

**Comment by bhojkamal** [comment] 2022-09-02 05:06
If I get free time, I will try my best to give hand.  Thanks.

**Comment by mfonhof** [comment] 2023-05-21 10:21
What is the status on this issue?

**Comment by objecttothis** [comment] 2023-05-21 10:37
It is already fixed in the next release which migrates the code to CodeIgniter 4.x. That project is still under way. You are welcome to help speed it along by helping to test or contribute code changes.

**Comment by mfonhof** [comment] 2023-05-21 11:33
I have Mint 21.1 / Cinnamon. Can you use that?

**Comment by SteveIreland** [comment] 2023-05-21 13:43
Nope.   I prefer Chili 5.1 and Paprika 2.0

**Comment by objecttothis** [comment] 2023-05-21 13:56
> Nope.   I prefer Chili 5.1 and Paprika 2.0

@SteveIreland those are Linux distributions. Spices are nice too though 😂

**Comment by objecttothis** [comment] 2023-05-21 13:57
> I have Mint 21.1 / Cinnamon. Can you use that?

Any OS is fine as long as you can run the appropriate AMP stack on it.

**Comment by mfonhof** [comment] 2023-05-23 04:57
Ok. How do i start to help?

**Comment by objecttothis** [comment] 2023-05-23 05:39
You'll need the code on your local branch which you can get by cloning or checking out the ci4-upgrade branch. Then you need to build the code which I believe @SteveIreland placed a build.md file in the branch showing instructions. From there you need a working Apache, MySQL (or MariaDB), PHP install. With that you should be able to start testing. You can follow the pull request at #3592 and report problems through issues.

**Comment by daN4cat** [comment] 2023-06-06 19:45
It looks like what I need to read to refresh my dev env to the latest and greatest.

**Comment by VonHirsch** [comment] 2023-06-19 12:10
This is encouraging!! as I'd like to install laravel/breeze alongside ospos for registration, password reset, email verification, and password confirmation etc.  I'm working on a consignment module atm, and will try to help test the upgrade branch when I can.  Very glad this epic project is still active =)

**Comment by objecttothis** [comment] 2023-12-12 08:12
This is resolved in ci4-branch and will be released with 3.4.0. That version is PHP 7.4-8.2 compatible and 8.0-8.2 supported.

**Closed by objecttothis** 2023-12-12 08:12 UTC
Labels: enhancement, pending

**Comment by engehab87** [comment] 2024-02-25 08:26
when will 3.4.0 be released?

**Comment by objecttothis** [comment] 2024-02-25 09:12
> when will 3.4.0 be released?

3.4.0 is building and running. Devs need to now regression test to see what is still broken then fix those things.

You can see the list of issues that need to be resolved here: https://github.com/opensourcepos/opensourcepos/milestone/17

@jekkos is it possible to have a 3.4.0 demo build for people to test then they can see the current status and report bugs to reduce the time devs need to do that.

It's difficult to give a release date because it depends on devs putting time into it. I only have parts of two days that I can work on it. One dev is moving to another country and another has a separate full time job. If others want to help with contributions that will speed things up.

**Comment by owlbrudder** [comment] 2024-02-25 09:15
I am at the airport now waiting for my flight. Should be back in harness on
Tuesday if my computers survive the trip. 😁

**Comment by jekkos** [comment] 2024-02-28 10:21
Latest 3.4 is up at dev.opensourcepos.org

**Comment by jekkos** [comment] 2024-02-28 10:23
@engehab87 if you want to help out, then test the instance at dev.opensourcepos.org and report back any issue encountered

**Comment by engehab87** [comment] 2024-02-28 14:16
is it possible that i could install it on my localhost? would help me faster to test in non internet locations.

**Comment by owlbrudder** [comment] 2024-02-28 17:57
Yes, certainly. It is an open source application on GitHub. If you go to
https://github.com/opensourcepos/opensourcepos and follow the
installation instructions, you can run it on your local machine. I have it
on two machines including a 20 year old laptop running Linux. It works
perfectly well and allows the system to be used with no internet connection
required.

**Comment by owlbrudder** [comment] 2024-02-28 18:16
Yes and I am running 3.4.0 on my local machines. I am a contributor to the
project, so I have to have everything local.
