### ISSUE TITLE
Invoice Number format in register page

### ISSUE THREAD

**Issue by hopto2021** [opensourcepos/opensourcepos#3398] opened 2022-01-09 08:46 UTC
#Question 

hello everybody,

 i have question i am using latest version 3.3.6 and also i tried that on version 3.3.4 when i create new invoice i can change the format in invoice settings in configuration page and works fine but when i tried to change the format in register page in "Invoice Number box"
![11](https://user-images.githubusercontent.com/96849459/148675172-f3fb7dbe-ba29-4ea2-8b7d-d33a49be268b.png)

invoice number become text is it designed like that on register page accept only text ? when i put {YCO} the invoice number become "{YCO}" not number but if i put it in configuration page it's works fine

Regards

**Comment by jekkos** [comment] 2022-01-09 16:28
might be related to #3388

**Comment by jekkos** [comment] 2022-01-09 16:30
@hopto2021 so the generation works fine if you set the format in the config section? I'm not sure that if you add a variable itself in the field, it is then properly replaced. 
But you do confirm the numbers are generated.

**Comment by SteveIreland** [comment] 2022-01-10 01:46
As far as I could tell, the field on the register was intended to allow a manual override to the invoice number.  I never thought this was a good idea but wasn't prepared to make any changes there.  The system always returns to the configuration to retrieve the rules for generating an invoice number.  If a value is entered into the invoice number field on the register then that entry becomes the invoice number even if it looks like another token. 

The token that is displayed on the register was intended to indicate how the invoice number is to be generated. At least that was my assumption of why it was there.  Didn't make sense to me, but I left it as it was when I added new options to the invoice number generation.

**Comment by hopto2021** [comment] 2022-01-10 06:58
> @hopto2021 so the generation works fine if you set the format in the config section? I'm not sure that if you add a variable itself in the field, it is then properly replaced. But you do confirm the numbers are generated.

yes in config section works fine but if you change anything in "Invoice Number field" on register page it will not replaced with number

**Comment by hopto2021** [comment] 2022-01-10 07:07
> As far as I could tell, the field on the register was intended to allow a manual override to the invoice number. I never thought this was a good idea but wasn't prepared to make any changes there. The system always returns to the configuration to retrieve the rules for generating an invoice number. If a value is entered into the invoice number field on the register then that entry becomes the invoice number even if it looks like another token.
> 
> The token that is displayed on the register was intended to indicate how the invoice number is to be generated. At least that was my assumption of why it was there. Didn't make sense to me, but I left it as it was when I added new options to the invoice number generation.

i think it will be better if it's become something like this you know the rule and the next number
![11](https://user-images.githubusercontent.com/96849459/148728516-6f2ee889-dc84-42a5-8485-08bd7556aecc.png)

**Comment by SteveIreland** [comment] 2022-01-10 14:36
I like the suggestion.  However, the next invoice number to be assigned can only be "here is what it's going to be if nothing else happens between now and when you click on (submit)".  Because some countries require the invoice number to be sequentially assigned, that assignment MUST take place when the user actually commits to completing the sale.

**Comment by SteveIreland** [comment] 2022-01-14 12:50
@jekkos I am going to submit a pull request this weekend to drop the token display.  I don't believe the display of the token provides any value to the sales clerk and the admin already knows which token is being used.  Instead I'll take try to modify the token to do a "read only" in order to be able to display what the next invoice number is likely to be and display that.  If the user doesn't change it to something else then, on update, we'll call the token to get the actual invoice number to use.  If the user does change the invoice number then the manually entered invoice number will be used

Is that okay with you?

**Comment by jekkos** [comment] 2022-01-14 20:28
resolving the variable value when the page is loaded might indeed be a better user experience

Mind that it might only give issues when you suspend a sale. So in that case you would put aside the resolved number for that moment in time and if other sales are completed before,  then you won't be able to complete it. I think it's good if we accept this side effect.

**Comment by SteveIreland** [comment] 2022-01-17 02:05
I've completed the coding for this  but I'm out of time to submit the pull request so I'll do that at the first opportunity.  So far the tests look good, but I'd like to run through all of the token possibilities so testing will take a bit of time.

**Comment by SteveIreland** [comment] 2022-01-24 00:53
Pull request #3408 was submitted to address this issue.

**Comment by SteveIreland** [comment] 2022-01-28 19:36
Pull request approved and merged.

**Closed by SteveIreland** 2022-01-28 19:36 UTC
