### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#2834] opened 2020-05-20 09:34 UTC
This is a placeholder to consider GitHub action as CI/CD pipeline.

**Comment by daN4cat** [comment] 2020-05-20 09:40
Or Azure Pipelines given there are 10 free pipelines that can be used in GitHub.

**Comment by jekkos** [comment] 2021-04-06 14:58
Duplicate of  #3110

**Comment by jekkos** [comment] 2021-08-14 21:11
I might have overseen this, but it seem that travis-ci.com only offers a non renewable set of credits. You basically need to move to their paid plan to have the credits renewed..

I think currently the only option is to move to github actions now. Unless we can find 70$ a month in extra funding to pay for travis plan.

**Comment by BudsieBuds** [comment] 2021-08-16 21:03
So the [Always Free banner on their website](https://www.travis-ci.com/plans) doesn't apply for this project?

> ### Free for Open Source
> Free for open source. We love the Open Source Community, and to show how much we love it, upon validated request placed with our Support Team you may receive free OSS credits for your public builds.

**Comment by jekkos** [comment] 2021-08-19 15:06
Indeed it wasn't 100% clear to me how to apply. I emailed them asking for extra credits so let's wait for this first.

**Comment by jekkos** [comment] 2021-10-02 11:46
I'm not sure but I think the unstable draft releases are only visible to contributors. It's not ideal as it stands, the fact that I need to tag a release in order to get the files in there.

I might look into pushing the zip to another repo so it can be downloaded from there.

**Comment by jekkos** [comment] 2021-10-02 11:50
Using draft releases for unstable builds does not feel like the best solution.

I think github packages might be a better solution for unstable builds. It's 500MB max for the free plan, but it will support version tagging out of the box.

**Closed** 2024-01-02 16:56 UTC
Labels: enhancement
