### ISSUE TITLE
Fiscal Printer

### ISSUE THREAD

**Issue by rmuni77** [opensourcepos/opensourcepos#2313] opened 2019-01-16 17:45 UTC
Hi,
We would like to use OSPOS, however our requirement is to integrate with fiscal device which is specific to country Bulgaria. I would be needing the support in this regard. Please let me know what additional information you may need and also what could be the cost.
Thanks,
Ramesh

**Comment by odiea** [comment] 2019-01-16 18:12
Duplicate of #2304

**Closed by odiea** 2019-01-16 18:12 UTC
