### ISSUE TITLE
Permission not updating for stock locations with two word name

### ISSUE THREAD

**Issue by MJPfuzzy** [opensourcepos/opensourcepos#1911] opened 2018-03-29 11:15 UTC
### Background information

After a successful installation onto a riasbury pi 3, found the system too slow for multiple users so moved it to a windows server environment running a virtual Linux environment on it and upgraded to the latest version.

Everything worked fine until we had to change a users permissions so they could do receiving and limit locations. I applied the changes, click update systems confirms updates are saved. log back into the user you changed systems says user has no permissions for that operation.

log back in as Admin, go to permissions all permissions have been removed. do it again, system confirms changes. go in again just to check, permission have not changed.

If I change anything on a employee or create a new one the same issue occurs.

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is:  4f5ad57
- PHP version is:       7.1.10
- MySQL or MariaDB version is:      MariaDB 10.1.28
- OS and version is:       Windows Server 2012
- WebServer is:      Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:  

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

We are unable to change new or current employees access permissions, including password. If I do either all permission are lost even thou systems confirms changes have been update. this happen even if you change the users password all access are reset and cannot be changed.

Users that have not yet been modified can still work as normal adding items, selling and receiving.

Just don't change anything others wise all lost.

**Comment by mckaygerhard** [comment] 2018-03-29 15:32
hi @MJPfuzzy please can you feedback with:

1. enable debug in browser, hit F12 and go to network tab, repeat the process ntil the "save" and see if a 500 or 404 or imilar was happened (maybe paste image), in my case i only see if are do in a complete linux environment, but for rest of developers that information it's required and may help
2.  do the proper logs files:
a.- go to application/config/config.php and raise log_threshold =0 to 4 and paste the resulting contents (or attach) of the php file generated in application/log
b.- go to the webserver log error.log file and paste the contetns of the las 80 lines or attached only with last 80 lines

also please check if write directory/file permissions are right..

**Comment by daN4cat** [comment] 2018-03-30 08:02
Do you have the same problem with admin user?

**Comment by allenftan** [comment] 2018-10-25 13:29
Hi,
I've experienced this problem and this is how to recreate it... also tried it on your demo https://demo.opensourcepos.org/login

1. Create more than one "Stock Location" on Configuration Tab/Option
- The stock location names must have "space" in it to recreate the bug
   "Location One" - will cause permissions not to properly update
   "LocationOne" - no issues in updating permissions

2. Update an Employee's Permission tick ANY STOCK LOCATION/S under ITEMS, RECEIVINGS, SALES

**Comment by SteveIreland** [comment] 2018-10-25 13:33
I'll check this out tonight to confirm that  if it's still happening in the latest master branch,

**Comment by SteveIreland** [comment] 2018-10-26 01:04
I've confirmed that this is still a problem in the master branch.  The fix will be included in the next push of India GST, but the fix is rather simple (requiring only that we play some games with the location name since the location name is also used as an HTML id value).

It only requires a change to 1 or 2 lines in 3 files:  .../controllers/Employees.php, ... /views/employees/form.php, and .../models/Stock_location.php.

**Comment by SteveIreland** [comment] 2018-10-26 01:12
I would also like to thank @allenftan for nailing the test scenario.  That makes it a heck of a lot easier to fix the problem when I know exactly what the problem is..

**Comment by SteveIreland** [comment] 2018-10-26 01:39
I went ahead and pushed it "as is" so that the commit that includes the corrections for multi-word location names is separate and easily reviewed.  It is found at ...

https://github.com/opensourcepos/opensourcepos/pull/2202/commits/ce5a75d6a408862ca721e8e98e55e427178f44c6

I normally merge commits before pushing so this won't stay separate for long.  So if you want to apply the changes to your site ... have fun.

**Comment by SteveIreland** [comment] 2018-10-26 01:55
I should also point out that I thought it would be a good idea to uppercase the first letter of each word of the stock location for the permission maintenance.  

This might not work for your environment.

Instead you can specify a language variable that tells the system what to actually use for the  location name.

**Comment by SteveIreland** [comment] 2019-03-17 19:30
I believe this issue is resolved.  I just tested it in master and it still seems to be working.  So I'm closing it.  If someone objects please reopen with an explanation of what you are seeing.

**Closed by SteveIreland** 2019-03-17 19:30 UTC
