### ISSUE TITLE
Cannot get new stock locations to show after deleting a previous stock location.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1691] opened 2017-10-23 20:29 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:You are using Open Source Point Of Sale version 3.2.0 - 4f5ad57. Please visit the website to learn the latest information about the project. 
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:  XAMPP

### Expected behaviour
Delete a Stock location then create a new location.

### Actual behaviour
Deletes a stock location ok. Creates a stock location. The new stock locations does not show in employee permissions so they do not show anywhere.

**Comment by jekkos** [comment] 2017-10-25 07:06
I just did some quick testing and found some regressions in permission tab

- stock permissions should be selected as children from their parent 'module' permission. When parent is not selected then stock permission should be greyed out
- allow sale / delete in sales and sale in receivings should be split up over different stock locations, see #1689

**Comment by jekkos** [comment] 2017-10-25 07:15
@SteveIreland Perhaps you missed that there's this possibility of having multiple stock locations? Would be nice if you could take a look at it anytime soon.

**Comment by jekkos** [comment] 2017-10-25 07:19
I also think that the way this is modelled now might not be the best. We should allow permissions to be hierarchic in the datamodel as well. I think right now some kind of workaround was used to indicate that a stock permission belongs to a certain module (using just the name). I kind of reworked that datamodel in the #150 branch in which it would be easier to handle a situation in which you have multiple levels in the hierarchy for each module.

MIght not be the easiest task but we need it in order to work with existing functionality. I'll try to dig up that code to see if we can rework this part based on that. Could turn out to be a bit more work than expected.

**Comment by jekkos** [comment] 2017-10-25 07:25
On the other hand, does it make sense to add this grouping to the permissions tab? Is there a usecase in which you would allow someone to access employees only through one group and not through the other? In the end you just see the same thing but reach it in a different manner.

I suppose a way to configure what is in the group was needed, but conceptually it's something that sits on to of the grants you have for different modules. So if a user doesn't have access to employees he can't change the way he sees the modules grouped over home / office. I would expect the grouping to be left to the user and to be configurable in any case. 

Or am I missing something?

**Comment by SteveIreland** [comment] 2017-10-25 10:31
@jekkos I will take a look at this tonight. I wasn’t paying close attention to this because I didn’t think I had touched stock locations - but I can go crazy sometimes

**Comment by marcellusmontilla** [comment] 2017-10-25 12:04
@SteveIreland Can I also suggest to include renaming the permission_id when location_name is updated?

**Comment by SteveIreland** [comment] 2017-10-25 14:12
You can ... hopefully I will understand when I take a closer look at the issue.

**Comment by jekkos** [comment] 2017-10-25 16:19
Hmm maybe let me dig up that branch and see if we can make this a bit better

**Comment by SteveIreland** [comment] 2017-10-26 03:45
I was able to recreate this issue and  I don't see an obvious problem.  The stock location table is being updated as expected.  When a deleted the permissions and grants table are being updated as expected. 

There is definitely a problem that needs to be fixed in the auto-creation of grants and permissions for a new stock location.  The group needs to default to the group of the core grant for that employee.  So I'll make that correction this week.  I don't think that the main problem here but will chase that down unless @jekkos wants to rework this area.

And yes, if the location name changes the permissions and grants definitely need to be recreated with the new names..

**Comment by daN4cat** [comment] 2017-10-26 05:46
So changing a name of an existing stock location forces you to refresh the permission grants, is that what you are saying? Not sure that's a good user (admin) experience, but I understand the current way is limiting access by key name.

**Comment by marcellusmontilla** [comment] 2017-10-26 06:51
Not really refresh permission grants, just rename the specific permission_id (or maybe replace, i don't really know how it's done). In config, the admin is allowed to change the text of the stock location (maybe it should not be allowed, but it is). When he submits, stock_location is renamed but permission_id is not. Hence, permission label is not consistent with actual stock location and permission is/can't be granted to new stock location.

**Comment by jekkos** [comment] 2017-10-27 08:01
@daN4cat I started rebasing some older branch'es commit with some rework I did on this part earlier ago. I think in that situation stock location permissions were not dependent on their location names, but need to double check. I'll make an example build once done because last time I rebased was not long after 3.0.0, so might need to do some testing to see if all behaves well.

It would allow you to run multiple stores using just one installation, while having the ability to manage stores and their stock locations from the application itself.

**Comment by SteveIreland** [comment] 2017-10-27 14:00
Paid work has consumed all available time for the last couple of days so I' had limited time.  But I just wanted to point out (just in case someone else jumps in) that part of the issue is that I wasn't aware until this week that renaming a stock location triggered a permission rename ... so that section of code wasn't taking into account the new menu group on the grants (that also had to be renamed).  

Just making a note here .... for the record.

**Comment by daN4cat** [comment] 2017-10-27 20:54
3.2 waits any issue fix.

**Comment by SteveIreland** [comment] 2017-10-28 14:22
I think the foreign key constraints are also playing a role in this failure.  Can I remove the foreign key constraints on grants and permissions?

**Comment by SteveIreland** [comment] 2017-10-29 02:38
A pull request has been submitted for this.

**Comment by SteveIreland** [comment] 2017-10-30 18:15
Has anyone confirmed if this is working for them now?

**Comment by odiea** [comment] 2017-10-30 18:56
This appears to be working properly now.

**Comment by daN4cat** [comment] 2017-10-30 19:28
Good, I close

**Closed** 2017-10-30 19:28 UTC
Labels: bug
