### ISSUE TITLE
Infinite loop in  /config

### ISSUE THREAD

**Issue by ThorvaldVerlaeckt** [opensourcepos/opensourcepos#1668] opened 2017-10-06 08:36 UTC
When you go to /config you end up in a infinite loop.
You load Sale_lib in your constructor, then in sale_lib you load tax_lib and in tax_lib you load sale_lib again...

**Comment by daN4cat** [comment] 2017-10-06 09:44
Which version?

**Comment by ThorvaldVerlaeckt** [comment] 2017-10-06 10:02
Latest

**Comment by daN4cat** [comment] 2017-10-06 10:23
And what about the issue template information?
Do you expect us to have a crystal ball?

**Comment by ThorvaldVerlaeckt** [comment] 2017-10-06 11:00
### Issue / Question / Bug

When you go to /config you end up in a infinite loop.

### Installation information

- OSPOS version is: latest 
- PHP version: 7.1

### Expected behaviour
The config page should load

### Actual behaviour
The config page does not load

### Steps to reproduce the issue
Try to load the config page

### Reason of the bug

![2017-10-06 12_56_09-opensourcepos_sale_lib php at master opensourcepos_opensourcepos](https://user-images.githubusercontent.com/13762966/31275008-c6205ca2-aa95-11e7-8d77-9f2160119e27.png)

![2017-10-06 12_57_05-opensourcepos_tax_lib php at master opensourcepos_opensourcepos](https://user-images.githubusercontent.com/13762966/31275019-d3a021a0-aa95-11e7-8aca-f39b89647165.png)

**Comment by jimktrains** [comment] 2017-12-22 04:51
For anyone stumbling across the same issue:

I am using a slightly modified Dockerfile.dev and docker-composer.yml. For some reason, the migrations weren't listed as up-to-date, but when run they errored (as shown in the error logs and by run the sql files directly against the database).  My (probably no ideal) solution was to update the ospos_migration table directly, dump the database to database/database.sql and rebuild everything. 

I'm not sure why this manifested like this, though.

**Comment by jimktrains** [comment] 2017-12-22 06:06
Incase anyone else comes across this:  I accidentally did a composer update and used 3.1.6 instead of 3.1.5.

**Comment by daN4cat** [comment] 2017-12-22 06:19
3.1.6 is causing issues

**Comment by daN4cat** [comment] 2017-12-22 06:19
Is it due to this bug?

**Comment by daN4cat** [comment] 2017-12-22 06:36
@SteveIreland you need to check this issue. I don't remember why I closed this but it was a mistake. Cross reference is not right and I need to check if it's the reason why the upgrade to CI 3.1.6 doesn't work.

**Comment by jimktrains** [comment] 2017-12-22 07:03
@daN4cat I'm happy to provide any help I can. I havn't been able to trigger it since downgrading.

**Comment by daN4cat** [comment] 2017-12-22 12:53
So the issue is upgrading to CI 3.1.6, right? It should be easy to fix and then I can upgrade CI. You can't open Sales register, that's the problem.

**Comment by jimktrains** [comment] 2017-12-22 15:03
Being unable to go to the register was a constant issue. I feel like some others popped up randomly, looked the POST/login route.

**Comment by daN4cat** [comment] 2017-12-22 20:31
I'm fixing this issue and upgrade to CI 3.1.6

**Comment by daN4cat** [comment] 2017-12-22 20:58
Fixed and in master

**Comment by daN4cat** [comment] 2017-12-22 21:00
Thanks @jimktrains for bringing this up to my attention, I don't know why I closed this in the first place. It must have been a pure mistake.
This was the root cause behind an upgrade to CI 3.1.6 that I attempted a couple of weeks ago but didn't have the time to debug.

**Comment by jimktrains** [comment] 2017-12-22 21:48
> I don't know why I closed this in the first place. 

Maybe because the original poster wasn't being helpful and there was no obvious way to replicate it. :)

I might have to dive in and figure out why this worked before. Maybe they changed when a lib is marked as loaded? Anyway, thank you for the quick update!

**Comment by daN4cat** [comment] 2017-12-23 22:02
If somebody else could confirm that latest master works fine I can close this issue.

**Closed** 2017-12-31 15:37 UTC
Labels: bug

**Comment by mckaygerhard** [comment] 2017-12-31 16:18
wow! closed but nobody confirms and i have a strange redirects closed ,more are closed. pufff

**Comment by jimktrains** [comment] 2017-12-31 23:09
@mckaygerhard Sorry, I didn't post on here.  Yes, updating did fix this issue.

This issue didn't cause redirects.

**Comment by mckaygerhard** [comment] 2017-12-31 23:22
thanks @jimktrains at least one not close close close and close, i feel inside the novel 1984 "hello big brother"

**Comment by jimktrains** [comment] 2017-12-31 23:30
As a non-maintainer this doesn't feel like 1984 to me. The OP wasn't helpful and provided no way to better understand or reproduce the issue. I failed to publicly confirm the issue. Maintainer closed it as it was resolved.

**Comment by daN4cat** [comment] 2018-01-01 00:48
Thanks @jimktrains to second confirm it's fixed. Happy 2018... sorry no 1984.
