### ISSUE TITLE
Tax included error when paying with gift card

### ISSUE THREAD

**Issue by ackuan** [opensourcepos/opensourcepos#1720] opened 2017-11-19 21:06 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
*system using latest version of Docker to implement OSPOS local install
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:  
- MySQL or MariaDB version is:   
- OS and version is:   Ubuntu 16.4
- WebServer is:  Apache 2
- (If applicable) Installation package for the LAMP/LEMP stack is:   n/a

### Expected behaviour
We expect for the gift card payment to behave like any other payment type even when "tax included" is checked.

### Actual behaviour
"Tax included" is checked in Sales Configuration section. When implementing a sale with a gift card, the sales tax gets added despite the "tax included" setting. The total is calculated properly, but the "payments total" and the "amount charged" are wrong.
![giftcarderror](https://user-images.githubusercontent.com/12613413/32995481-fec5a506-cd42-11e7-9432-8f932703646f.png)

### Steps to reproduce the issue
Make a gift card $10
Make an item $2
Have store configured with tax included
Charge customer $6 worth of $2 item
Use gift card as payment

**Comment by jekkos** [comment] 2017-11-19 21:20
Weird behavior.. need to check whether I can reproduce

**Comment by daN4cat** [comment] 2017-11-19 22:14
@SteveIreland maybe you want to look into this?

**Comment by SteveIreland** [comment] 2017-11-20 04:46
Yes.  I'll take a look at this.

**Comment by SteveIreland** [comment] 2017-11-22 04:33
A pull request was submitted for this issue.

**Comment by daN4cat** [comment] 2017-11-22 20:09
@SteveIreland, merged and thanks for the fix!

**Comment by daN4cat** [comment] 2017-11-22 20:10
@ackuan please test the latest code and see if everything works fine now.

**Comment by odiea** [comment] 2017-11-22 20:22
@daN4cat The issue is on 3.1.1. Will this fix that version?

**Comment by SteveIreland** [comment] 2017-11-22 20:29
Nope, but the correction is trivial so a simple copy and paste will do the trick unless there is a desire to republish 3.1.1 with a correction

**Closed** 2017-11-22 20:38 UTC
Labels: bug

**Comment by odiea** [comment] 2017-11-22 20:40
Yep. That's what I do to test it in earlier versions.
