### ISSUE TITLE
The installation is not correct, check your php.ini file

### ISSUE THREAD

**Issue by quocnho** [opensourcepos/opensourcepos#1592] opened 2017-09-14 07:38 UTC
Hi all,
I have already installed ospos in to localhost (xampp: php 7.11). 
Login: http://localhost/public/login with admin/pointofsale

it say: The installation is not correct, check your php.ini file

I have tried my best to config php.ini. Who can figure out me the way to resolve this issue?
(Please note that PHP needs to have `php-gd`, `php-bcmath`, `php-intl`, `php-sockets`, `php-mcrypt` and `php-curl` installed and enabled.)
Please tell me detail how to install and enable: php-gd`, `php-bcmath`, `php-intl`, `php-sockets`, `php-mcrypt` and `php-curl`?
Thanks so much!

**Comment by daN4cat** [comment] 2017-09-14 07:56
What's the error log saying?

**Comment by daN4cat** [comment] 2017-09-14 08:57
Also you are not providing any information about your installation. So I close this issue.

**Comment by odiea** [comment] 2017-09-14 20:21
@daN4cat it looks like we lost the Close button?

**Closed** 2017-09-14 20:53 UTC
Labels: pending

**Comment by odiea** [comment] 2017-09-14 20:55
It looks like I lost the close button. So I guess it's up to you 2 now.

**Comment by daN4cat** [comment] 2017-09-14 21:33
@jekkos ?

**Comment by Praveenkanaujia** [comment] 2017-09-19 08:03
Hi all,
I have already installed ospos in to localhost (xampp: php 7.11).
Login: http://localhost/public/login with admin/pointofsale

it say: The installation is not correct, check your php.ini file

please suggest me how could it done ?

**Comment by daN4cat** [comment] 2017-09-19 08:59
What's error_log saying? Check in your public folder

**Comment by Praveenkanaujia** [comment] 2017-09-19 09:13
now its worked thank you..

**Comment by RAZA-ABBBASI** [comment] 2017-09-20 05:11
@Praveenkanaujia how you solved your problem, i am facing same issue.
can you guide step wise please ?

**Comment by Praveenkanaujia** [comment] 2017-09-20 17:32
@RAZA-ABBBASI Please use updated file of open source name of (opensourcepos.20170909085348.3.1.1.76a002).

**Comment by Sunyodi** [comment] 2017-10-09 10:30
@Praveenkanaujia.
I face the same problem with updated file of opensourcepos. Please indeed your help on solving this error

**Comment by odiea** [comment] 2017-10-09 12:22
Related to Issue #1607

**Comment by RAZA-ABBBASI** [comment] 2017-10-09 15:34
@Sunyodi i did follow instructions in this link 
http://www.opensourceposguide.com/guide/gettingstarted/installation
and successfully installed OSPOS. The key (i was missing) was to install/enable ALL REQUIRED MODULES, and it will run smoothly.

**Comment by matthias1984us** [comment] 2021-10-06 11:31
First off let me introduce myself, long time user and developer just kept everything in house. When I came upon OSPOS it was in version 2 and a dead project. That does not appear to be the case any more so I will be joining this community.

If you are using Ubuntu 20.04 LAMP stack with apache2 2.4.41 and php 7.4.3 I found enabling extensions in php.ini was not useful or working as designed. The root cause seemed to be with the php install.
for some reason the extensions are installed or found even after installing
when I checked the /var/log/apache2/error.log after enabling errors in php.ini I saw below error even with extensions installed
PHP required extensions: bcmath, intl, gd, openssl, mbstring, curl
I found the steps below which are a reinstall I gathered from this thread
https://computingforgeeks.com/how-to-install-php-on-ubuntu/
I interpreted myself and made my steps below which resolved. Please share for other LAMP stacks as needed. No one seems to have found this solution and there are a bunch of threads on this issue.
It appears apache needs to be disabled while php installs or there is issues?

sudo systemctl disable --now apache2
sudo apt-get purge php7.4-fpm
sudo apt-get install php7.4-fpm
sudo apt install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath
sudo systemctl enable --now apache2

**Comment by jsyl80** [comment] 2023-05-16 16:00
The installation is not correct, check your php.ini file.

is there anybody can help me, i am facing same problem in macOS Big sur
and xampp v-7.4.16 
Apache/2.4.46 (Unix) OpenSSL/1.1.1j PHP/7.4.16 mod_perl/2.0.11 Perl/v5.32.1

Database client version: libmysql - mysqlnd 7.4.16

Server version: 10.4.18-MariaDB 

OSPOS : opensourcepos.3.3.8.ffe492

I Checked Server Requirements in INSTALL Files and readme files unfortunately i couldn't find anything which one i skipped.   
 
mysql : 10.4.18-MariaDB <------------------ database version  is that ok?

i spend nearly 30 hours getting upset...!

**Comment by odiea** [comment] 2023-05-16 16:05
PHP version 7.2 to 7.4 are supported, PHP version ≤5.6 and 8.0 are NOT supported. Please note that PHP needs to have the extensions php-gd, php-bcmath, php-intl, php-openssl, php-mbstring , php-curl and php-xml installed and enabled.
