### ISSUE TITLE
categories and subcategories

### ISSUE THREAD

**Issue by asadjaved63** [opensourcepos/opensourcepos#68] opened 2015-05-06 01:33 UTC
Hello sir. Hope you will fine with your health and business
Sir, it is possible, make a system like Categories have different sub categories and all items have same item number.....

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=13244847)](https://www.bountysource.com/issues/13244847-categories-and-subcategories?utm_source=13244847&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jekkos** [comment] 2015-05-06 20:29
Yes I have a branch set up that will allow you to define quantities in 'units' for each item. In this case it could be used to assign different kinds of items all having the same item id, while keeping their current quantity stock counts separated.

Currently the implementation allows you to assign units to a specific category, but only by defining the data directly in mysql. Thus the main problem is that this functionality needs a configuration interface (so you can setup the units properly) and I have no funding to develop this functionality yet.

**Comment by asadjaved63** [comment] 2015-05-06 20:50
i will send you some coins if you develop it for me....

**Comment by asadjaved63** [comment] 2015-05-07 13:04
reply me .. waiting for your reply

**Comment by jekkos** [comment] 2015-05-08 07:23
I was thinking of making the UI so that one can create categories and units, and then develop something that allows a user to associate mutliple units with a category of choice.

This means that you will be able to add the different colors here, link them to eg category t-shirt, and then select the t-shirt category for a new item. Then all the associated categories will show up with edtiable quantities for that category. This is still quite a profound change and will take some time and effort so I might want to discuss the reward with you first.

**Comment by asadjaved63** [comment] 2015-05-08 11:23
This great idea. Many companies required same thing... one item have different categories and sub-categories like color, size etc, and have different quantity of sub-item..  , in my case one item have many sub-items(color and size) and all sub-items have own Quantity,, so I would suggest you Do something like that,, its very helpful to maintain stock  in the end of year and maintain profit and loss statement....if you develop it for me I will donate you some amount  on PayPal
![a02bdfb6-f3b9-11e4-882a-4ca5afff67dd](https://cloud.githubusercontent.com/assets/12225271/7535402/1e3327ee-f59e-11e4-86b2-cabe1f398839.png)
 ....

**Comment by asadjaved63** [comment] 2015-05-10 00:01
If I want to add one module like opening balance and closing balance,
expense, then what you would charge for it... please tell me?

**Comment by jekkos** [comment] 2015-05-11 12:15
This might be best implemented as a new report. What do you mean with closing balance? The amount of cash in the till? In this case it might be best to add something in the sales module that can track the amount of money in the till?

Please describe a bit further your requirements (just the flow of actions to follow, data to display, place to display it;) then we will be able to get a better view on what is needed here.

**Comment by odiea** [comment] 2015-05-13 14:06
What would be nice would be a screen at logon for the register that would ask for Opening cash. At the end of the day or Closing register a screen would ask for cash total credit cards and gift cards. The cashier would see just the Amount screen but an Admin or Manager would see the Total for Day report along with what the cashier added. Kind of a side by side view.

**Comment by daN4cat** [comment] 2016-04-03 21:57
Opening cash is covered in #440

**Comment by jekkos** [comment] 2016-05-19 11:05
I don't really know whether is realistic to include this in 3.0. Maybe we should postpone to a later date?

**Comment by daN4cat** [comment] 2016-05-19 15:38
The problem is that a 3.0 as it is is unusable for me without having proper additional fields.

So it's either I split and do my custom work but then I cannot spend time on the common part or we find a generic solution and I leverage that.

**Comment by daN4cat** [comment] 2016-05-19 15:39
I will think about...

**Comment by jekkos** [comment] 2016-05-24 06:48
Ok I'll try to design something for this part coming days..

**Comment by daN4cat** [comment] 2016-05-24 08:10
Can we first close bstables and charts? There are still some bstable issues open (in progress).

This is indeed the next big thing for me. We need to discuss a bit about how to implement so we cover various use cases from different people.

**Comment by jekkos** [comment] 2016-06-24 20:47
Any ideas if we want to include this feature in 3.0? Maybe we should just start stabilizing now and fix remaining bugs in bstables and leave this for 3.1.? It's already been some time since we released something and I think 3.0 

Also think the impact of starting something big like this will probably cause quite a setback for a possible next release date..  while at the same time most people are just using master version?

**Comment by jekkos** [comment] 2016-06-24 20:49
I don't mean to postpone this at all, actually I'd like to start working on asap as well but first close remaning issues and get 3.0 out of the door?

**Comment by daN4cat** [comment] 2016-06-24 21:02
I understand. We need to close bugs and security and maybe one bit or two and we are done with 3.0.

My problem is that without extra fields all the work I have done is unusable for me.

Maybe closed 3.0 I branch off and I add the fields I need just to migrate to the new.

Then if you work on this categories in a branch I can work on Mailchimp and other features that I can integrate in my fork.
I need to think about.

**Comment by jekkos** [comment] 2016-06-24 23:09
Yes actually I'd like to propose a 'feature freeze' for 3.0 any time now.. Otherwise we keep going ( which isn't bad anyway but we need to build something stable first).

Beside that the development for this part will probably happen in a branch at first (like we did with bstables) so we can keep minor fixes in master and have it ready for daily use and testing?

I'll try and see if I can find some time to design a bit the data model changes for this one.

**Comment by daN4cat** [comment] 2016-06-25 05:39
Ok, let's look at what is left to close.

**Comment by jekkos** [comment] 2016-09-16 17:44
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=13244847)](https://www.bountysource.com/issues/13244847-categories-and-subcategories?utm_source=13244847&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by daN4cat** [comment] 2016-09-16 18:54
I will share part of the cost because I need to add additional fields see #172 and #173.

#385 #140 #851 are similar but @salikur @asadjaved63 @walterhumphreys @dawzilla should share the cost here

**Comment by jekkos** [comment] 2016-10-22 20:39
![item_attributes](https://cloud.githubusercontent.com/assets/576234/19622357/6aa3ebd2-98a8-11e6-8136-172c1584c007.png)

**Comment by jekkos** [comment] 2016-10-22 20:42
I whipped up a simple ERD diagram for this change. Have to think a bit further how I will adapt the UI to make category CRUD as easy as possible. I'd prefer to keep these create/delete controls inside the item modal dialog.

**Comment by jekkos** [comment] 2016-10-22 20:42
Idea is that in the end the custom fields will disappear in favor for a more generic and extensible db layout.

**Comment by daN4cat** [comment] 2016-10-27 16:07
Agree and this is something I need.
Also sold item could contain some of the attributes that have a temporal factor in it. For instance season, expiry date, in case the same repeats and restock means new season or new expiry date.

**Comment by jekkos** [comment] 2016-11-03 14:43
Ok so temporal factor can be accomodated by using the attribute_type field which would be a date in that case. Also depending on the type we show a different kind of control like datepicker or combobox in the modal form. 

I propose to add some kind of module with table to manage categories. Each category will be a line and opening the modal would allow to add subcategories or just plain values. Subcategories will then use a fk to another attribute definition to denote it's parent entity. 

Once a category is selected in item form then a query will determine whether it has to show a subcategory field or just pop up the possible values for the category in case it has none. The intermediate attribute_links will have an optional fk to sales_items and receivings_items as well to register a selection history for items that were sold at a certain point.

I think at sale time we should thus always link the attribute for that item at that time and create a new record in attribute_links that freezes the attribute selection for that moment. This case seasonal data can be persisted. Constraint is that at least one of receiving_fk, sale_fk or item_fk should be not null. Will update the data model later on.

**Comment by jekkos** [comment] 2016-11-03 14:45
Also I had an idea to use react.js for this part but maybe we might be more consistent by just reusing bootrstrap tables for this story.

**Comment by daN4cat** [comment] 2016-11-03 17:48
I see, so is the idea to have a configuration tab view where we can add item attributes, type and UI control as a triple association?

With regards to the word "categories" I'm afraid I'm getting lost here because at the moment there is a field category in items and that to me is a way of defining a set, so you can group items (aggregation of items to a category class).

I see attributes as description of the item, a way to subclass it. Is that the intention here?

With regards to React, I would leave that to later when we make that switch for other parts. Something more for a 4.0.0. So better to reuse bootstrap tables indeed.

Yet about the UI part, how will the attributes be visible in Items view? As extra field in the same row or as a secondary row (like in Detailed Sale report)?
Same in Detailed Sale and Register reports.
I assume that Sale register stays as it is unless we want to add on the second line the attributes, but then it gets complicated even considering receipt and invoice parts.
Maybe we keep as first step as hidden to the customer the attributes otherwise you end up changing too many things.

**Comment by daN4cat** [comment] 2016-11-03 17:57
About the point of storing the Item snapshot at Sale time, your proposal sounds good.

However I was wondering if instead we should consider an item versioning schema?
I mean that everytime you change the item in any form it should be made persistent so when you check the historical in the Inventory Data tracking you can see not always the quantity but also what else changed as it's always marked as `Manual Edit of Quantity` with Quantity = 0.

Having that in place you just link the Sale transaction to the snapshot of the Item at the time.

But this change is a different story probably and we should change the way we track the inventory data but would be nice and adding full historical support.

**Comment by daN4cat** [comment] 2016-11-03 19:04
This is relationship diagram I mentioned above:

![ospos diagram](https://cloud.githubusercontent.com/assets/636048/19981090/57261b80-a1f8-11e6-888a-14af92ee8ed4.png)

**Comment by jekkos** [comment] 2016-11-03 20:33
Actually the idea was to have the category determine a set of attributes with predefined values linked to it. In that way a subcategory would be called an attribute but I guess it would be more clear to just use attribute as a generic term. In this case category field would be removed from items and replaced by an attribute definition of CATEGORY type. This type can have many other attributes of other types linked to it automatically.

This way of working will allow us to define a certain kind of 'template' for creating new items. For example when one adds shoe, one would like to have a fixed dropdown of sizes which are specific for shoes only. 

Also later on different quantity 'units' might be linked as attribute as well. Conversions could then be done between those quantities. In this case a simple link with item_quantities would suffice.

I see what you mean with the triple association and indeed thats how I see it as well. Only thing here is that both category and attribute will be saved in the generic three table structure I proposed earlier.

In terms of ERD diagram, I downloaded MySQL workbench which allows us to generate code for new tables easily? For UML only the website you proposed might be a good choice, I'll have a look if I find the time.

**Comment by jekkos** [comment] 2016-11-03 20:45
Item versioning might be an option but I think the impact for that will be huge. Fact is that we already have some kind of limited version of a history in terms of the sales and receivings_items, which copy the cost / unit price at receiving or sale time. Also items inventory kind of interferes with that idea. I guess a more generic item versioning scheme could probably replace the latter two, but that might be something for later.

Good point on the UI. I had some thought about already and as different items won't have similar attributes linked  to them, I think that we'd best stick with some  kind of detailed view. On the other hand I might want to think about a way to show specific attribute values in the upper row as some items have similar names but for example different sizes.

Same for the register, at first I would indeed not show anything extra there. But an extra config option in the attribute definition might determine whether some information is shown in an order line or not. This is also something I have now and which probably needs to be generified.

**Comment by daN4cat** [comment] 2016-11-03 21:53
OK, so the current category becomes an attribute and then it makes sense. Agreed.
I was confused by the ERD diagram as current category was left in Item.

Yes, the versioning would replace the copy of cost / unit price, and sale will just retain the concept of discount and pointer to correct version of item.
The inventory will be just based on the current version and historical will report any change.

Anyway, I agree it's a big change to consider later.

For the tabular view of Items my preference would be to show the attributes (season, colour, size + current category) I need in the primary row.

**Comment by jekkos** [comment] 2016-11-03 22:15
![item_attributes](https://cloud.githubusercontent.com/assets/576234/19987420/5eea76f4-a21b-11e6-9d8d-655f77879456.png)

**Comment by jekkos** [comment] 2016-11-03 22:15
Final version will look more or less like the image above here.. Indeed I forgot to remove category and custom fields.. they are gone now.

**Comment by jekkos** [comment] 2016-11-03 22:16
also in case we link with sale_items we need a combined item_id and sale_id. These tables have no unique id's of their own. This implies that item_id will be always required. The others are optional.

**Comment by daN4cat** [comment] 2016-11-04 15:44
NOTE: If you change tables please make deleted TINYINT(1) as the other booleans. Also supplier_id should be a INT(10) consistent with employee_id and customer_id. I had in mind to check and fix but since you are going for this change please fix those fields.

**Comment by jekkos** [comment] 2016-11-04 17:06
Some pk's are int(11) and soms int(10). I think all should be reviewed then. I noticed exact same thing once when I was migrating from an old ospos.

**Comment by jekkos** [comment] 2016-11-06 16:30
Ok I will proceed with regular and tedious javascript coding in that case.. think we will be happy one day to be able to work with a modular framework like reactjs.

**Comment by daN4cat** [comment] 2016-11-06 16:57
I understand, but it's better to make things in small step otherwise it becomes another 6/9 months story for 1 feature.... let's be agile/lean.

**Comment by jekkos** [comment] 2016-11-06 17:35
ok but maybe that would have been the point. A lot of complexity vanishes with concepts introduced by these new frameworks. The amount of boilerplate code is reduced dramatically and new features can be developed a lot faster. I found myself copying a lot of code without needing to change it profoundly, think one calls that `code smell`. I am sure there are better ways. Once things get a little more complex the time one needs to work on UI part increases exponentially. That's because there's no sound design concept for this frontend stack.

 I read that react is ideal to integrate in an existing application. Also I think the way we're doing frontend now, using jquery and manually binding event listeners to models etc.. isn't really the most efficient way of working.

But then of course there is the story of consistency.

**Comment by jekkos** [comment] 2016-11-06 17:37
anyway I'll just stick with it now and if there's ever a motivation for 4.0 then we can do revise all that ofcourse. On the other hand it's always nice to learn new stuff.

**Comment by daN4cat** [comment] 2016-11-06 18:32
Agreed.

Just to understand, is this something you plan to work now? As I'm undecided whether to wait for this feature or have an intermediate step to 3.0.1 before jumping to 3.1 with this.

**Comment by jekkos** [comment] 2016-11-06 19:46
I have sent you a mail with some explanations.

**Comment by jekkos** [comment] 2016-11-06 19:47
Lets try to deliver this one with 3.1 and push all other changes further.

**Comment by jekkos** [comment] 2016-12-28 18:56
Minimum PHP version will move to 5.6 in 3.1.

**Comment by jekkos** [comment] 2016-12-28 18:56
I used some 5.6 feature for the attribute flags (define array as const in PHP)

**Comment by nathanzky** [comment] 2018-01-10 13:54
Is this implemented on master or still need more work?

**Comment by SteveIreland** [comment] 2018-01-10 14:10
@nathanzky You are such a tease.  I saw this thread shoot to the top of the list and I got excited because I assumed that @jekkos was announcing that it was merged.  😉

**Comment by odiea** [comment] 2018-01-10 14:17
Don't hold your breath waiting for this to happen.

**Comment by nathanzky** [comment] 2018-01-10 14:44
@SteveIreland Sorry ... :)

**Comment by jekkos** [comment] 2018-01-10 23:08
@nathanzky current state of the branch is not complete and needs one extra functionality added before it can be considered done..

**Comment by jekkos** [comment] 2018-01-10 23:09
Any help there would be welcomed of course.

**Comment by SteveIreland** [comment] 2018-01-11 14:02
How can I help?

**Comment by jekkos** [comment] 2018-01-11 21:29
I can push this branch here.. however it needs some rebasing. Some discussion has been going on on what still needs to be done. Maybe if @daN4cat can grant you access to the original thread so it might be easier to catch up

**Comment by SteveIreland** [comment] 2018-01-11 22:19
Okay, let's do it.  I will probably be able to make some time to work on it.

**Comment by daN4cat** [comment] 2018-01-12 22:25
@SteveIreland you can see the code now.

**Comment by SteveIreland** [comment] 2018-01-13 00:58
I can?  What's the name of the branch?  The only unmerged branches that I seem to have visibility to are master, release/2.2.2, and gh-pages.

Do I need to do something to finish it out?

**Comment by daN4cat** [comment] 2018-01-13 10:38
@SteveIreland check your email, you should have got an invite....

**Comment by SteveIreland** [comment] 2018-01-13 19:37
@daN4cat I am now able to see it on github but for some reason I'm not able to fetch the repository to my my local computer.  Is there another setting?    When I clone the repository I am still only getting the master, gh-pages, and release/2.2.2 branches

**Comment by SteveIreland** [comment] 2018-01-13 22:55
Trying again .... I think I spotted what I was missing.

**Comment by SteveIreland** [comment] 2018-01-13 23:15
Okay I'm in.  I missed the part where you said I would be working against the daN4cat repository instead of the jekkos repository (even though it was right there "in my face" on the invitation).  -)

**Comment by SteveIreland** [comment] 2018-01-14 04:05
Odd.   I cataloged what is being changed to so that I could try to be slow and careful with this (as well as learning the approach to be used).

Because this was a bit different approach for me I thought I'd do a rebase.  It rejected it because of unstaged changes.  I tried to commit the changes and the only file that seemed to be uncommitted was LICENSE in the root folder but it gave me an index error.  Really weird ... I hacked around and finally got past the index error and was able to commit a change to the file.  But it continues to give me an unstaged changes errors even thought there aren't any uncommitted changes.  It seems that there is still something for me to learn here.

Another question I had since this was working on the daN4cat repository is that there didn't appear to be a way for me to check how many commits the master branch was behind the jekkos master branch.  Is this normal for the approach we're using for this?
```
C:\Users\steve\PhpstormProjects\opensourcepos-private>git rebase -i master
Cannot rebase: You have unstaged changes.
```

**Comment by daN4cat** [comment] 2018-01-14 08:14
Masters are the same.

**Comment by jekkos** [comment] 2018-01-14 13:28
@SteveIreland most of the code is condensed in one commit that sits on top of current master (which was lagging behind a bit last time I checked). So I think we should revert at least the category delete and then replace it with the option of grouping attributes. If not too busy maybe I can have a look at that one alright.

**Comment by daN4cat** [comment] 2018-01-14 18:12
@jekkos masters are in sync, branch rebased.

**Comment by januaryramadhan** [comment] 2018-01-21 04:12
i have installed a stable rellease for ospos, but when i want to upgrade it
to version 3.2. i have getting error with indonesian translation. anyone
can help me to fix it ?

**Comment by itskawsar** [comment] 2018-06-02 05:38
Are there any plan to make it public? :)

**Comment by SteveIreland** [comment] 2018-06-05 00:01
Congratulations on publishing 3.2.1!!!

Now that it is behind us I'd like to propose that we go ahead and merge this and multi-package and the debit management package and the soon to be re-released temporary item package so that we can spend a month of coding to work out any bugs in them.  Are they close enough to do that?

**Comment by mckaygerhard** [comment] 2018-06-05 12:38
the 3.2.1 are full of errors due CSFR simplification, please revised!

**Comment by daN4cat** [comment] 2018-11-25 18:00
This is in master and targetting release 3.3.0

**Closed** 2018-11-25 18:00 UTC
Labels: Epic, enhancement

**Comment by Giuliano69** [comment] 2024-09-15 21:19
I saw the dbase diagram and noticed NO subcategories in the layout.
Are they planned to be implemented in next release, or has the feature of subcategories been dropped ??

Just to highlight differences between subcategories and other product properties.
Subcategories are sub-nodes of a parent category. In a report the category can automatically be drilled down in all the own subcategories.
Other properties (size, colour, weight, ..)  can possibly belong to any  subcategory, with no special relation to any main category.

Taking as an example the famous AdventurWorks ERP database, properties like size, weight, can be implemented as specific filed in the table; category and subcategory are FK to  records in other tables.
Following this idea, subcategory should be defined in an external table, and forwarded with a FK...


BR
Giuliano

**Comment by jekkos** [comment] 2024-09-15 21:30
Which database diagrams did you check? They might be outdated. You can use item attributes to accomplish this.
