### ISSUE TITLE
Default register mode question

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3016] opened 2020-11-17 17:17 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Is there a way to set the default register mode in the sales module?  We switched it to return, ran a return but forgot to switch it back to sales.  I'd be nice to have it go back to sales by default.  

Thanks

**Comment by WebShells** [comment] 2020-11-17 17:21
Hello there, it's available there but i guess there is an issue with the functionality needs to be re-checked. 
You can set it there from the configuration section.

**Comment by odiea** [comment] 2020-11-17 17:33
@WebShells That appears to have gone missing in Configuration. What I ended up doing was to add the following line  in sale.lib in the public function clear_all() $this->clear_mode(); and it appears to work for me.

**Comment by WebShells** [comment] 2020-11-17 17:38
@odiea it's not there under invoice section in configuration anymore? it was there in 3.3.2, but as i remember it had an issue in functionality.

**Comment by odiea** [comment] 2020-11-17 17:43
@WebShells You are correct. I just looked in the wrong place for it.

**Comment by chunter2** [comment] 2020-11-17 18:52
I see it now.  I missed it because I disabled Invoicing and it's greyed out because of it.  It seems to be associated with Invoicing and maybe it shouldn't be?  Maybe that's what wasn't working before.

**Comment by chunter2** [comment] 2020-12-02 12:40
@jekkos Could you take a look at this?  I think this is a bug because disabling Invoicing shouldn't disable the Default Register Mode.  It should only limit what's selectable.  Maybe that option should go under General instead of Invoice.  

Thanks

**Comment by jekkos** [comment] 2020-12-04 23:20
@chunter2 I did a fix for this one. It should be on the dev server soon. Could you check if it works as expected? Thanks.

**Comment by chunter2** [comment] 2020-12-05 00:54
@jekkos I just tried applying your commit to my test system and it seems to work but maybe not the way I expected.  It only seems to take affect once I've done a sale or return.  For example, if I go and set it in config to Return and then go to the sales module it still shows as Sale.  If I choose Return in the sales module but then click on other modules and come back it stays on Return.  Same thing if I click on Sale.  It only seems to check that value after I process a transaction.  I have a feeling this is by design since you can start a sale, go to another module and come back to the sales module and what you had done before will still be there.  All that to say I think that's ok?  :)

**Comment by jekkos** [comment] 2020-12-05 09:43
Yes I think the mode is only set if there is no mode yet in the session, as you describe.. so indeed if you were in the process of adding items to the register, it should stay in that mode, and only select the default one after the session state was cleared. Does that make sense?

**Comment by chunter2** [comment] 2020-12-05 16:39
@jekkos Looks like this isn't working correctly.  The complete button won't show up when you add a payment for the full amount.  If you switch to return the complete button comes up and then you can switch back to sale and the complete button stays and you can finish the transaction.

**Comment by SteveIreland** [comment] 2020-12-05 19:40
I've confirmed this last issue.  It is behaving like an Invoice.  If a customer the "Invoice" button is presented.

**Comment by jekkos** [comment] 2020-12-12 16:20
Ok I was just thinking, does it make sense to have this feature in the end? I mean I think the default case here will always be doing a sales receipt no? I seldomly find myself selecting something else, and when I do then it's always for a one time occurence..

I feels that it would need some time investment to polish it otherwise.. as @SteveIreland points out the dropdown should be refreshed using ajax once invoices are enabled. So not sure what to do here.

@chunter2 maybe you can elaborate how you would use this as you were the one reporting the bug.

**Comment by chunter2** [comment] 2020-12-12 23:04
@jekkos I agree with your comment.  For my use-case it should always default to sales.  We just ran into a problem when we processed a return and then processed the next transaction assuming it was set to sale and it was still set to return.  The negative signs everywhere should have been obvious but were missed.  :)  I'm good with removing the option all together as long as it defaults to sale each time instead of what was processed last.  Does that make sense?

**Comment by SteveIreland** [comment] 2020-12-13 00:54
The "retain mode" option was intended to be a convenience for sites primarily use invoicing.   The client I was supporting at that time was about a 50/50 mix of POS and Invoicing.  They didn't complain about the behavior, but I don't think it would be a problem if the default was always POS.  After all, it is a POS system.

**Comment by jekkos** [comment] 2020-12-13 16:29
@SteveIreland Ok I see where this is coming from. In this case it might make more sense to stick to the last mode used within the session instead? We could opt to remove the clear in the sale_lib after a sale is completed so that in case you are doing a batch of invoices or something, you just stay where you left? I think that at least would make more sense then having an option in the config for this (I didn't even know it was there).

**Comment by chunter2** [comment] 2020-12-13 19:10
@jekkos I would vote with @SteveIreland to always set it back to sale by default.  That's what I was hoping that setting would do for me.

**Comment by daN4cat** [comment] 2020-12-17 16:28
I assume this is fine and close this.

**Closed by daN4cat** 2020-12-17 16:28 UTC
Labels: bug
