### ISSUE TITLE
How to add the shipping module to the bill

### ISSUE THREAD

**Issue by sagittariuskhanh** [opensourcepos/opensourcepos#1425] opened 2017-07-27 13:11 UTC
Hi 

I have some questions to ask

1. I want to add module shipping to bill . 

**example :** 

If bill shipped -> i check done -> done 

I want to manage the bill already shipped and paid . 

2. I want add column comment to report sale 

![image](https://user-images.githubusercontent.com/30499423/28671596-813492cc-7307-11e7-87cb-c28b0b4a67b6.png)

3. I want to customize the text on the home screen 

" Welcome to OSPOS, click a module below to get started! "

THANKS and best regards

**Comment by Aravindkrishna2010** [comment] 2017-07-27 13:30
**Only for Column name change**    --  Views/sales/invoice.php 
**Extra Column add** -- Views/sales/invoice.php(make UI change), controllers/sales.php( change this if you added new column that already not in ospos) and Models/sale.php( If result not happened, pass required column value with this model). 
** Dont forget to change table CSS in bill.

**Comment by sagittariuskhanh** [comment] 2017-07-27 14:22
I want change name column on " sales manager table " :(

**Comment by daN4cat** [comment] 2017-12-26 17:45
Duplicate of #872 and #592.

```
I want to customize the text on the home screen
" Welcome to OSPOS, click a module below to get started! "
```

It's not possible, please read the LICENSE.

**Closed by daN4cat** 2017-12-26 17:45 UTC
Labels: duplicate
