### ISSUE TITLE
MultiPrices for a product

### ISSUE THREAD

**Issue by pmuruaga** [opensourcepos/opensourcepos#1585] opened 2017-09-13 03:35 UTC
Is there a way to have multiple prices for a product, and choose the correct pricelist when selling?

I would like to have different prices for a product and depending on a customer or a selection when doing a sell I want to choose the price. Is there a way already implemented on system?

**Comment by daN4cat** [comment] 2017-09-13 06:01
Already discussed, search the existing issues.

**Comment by pmuruaga** [comment] 2017-09-14 20:09
Sorry I'm new on github and ospos, anyway I couldn't find anything like what I asked. This is a similar title: https://github.com/opensourcepos/opensourcepos/issues/642 but is not the same.

**Comment by bkrajendra** [comment] 2017-09-18 12:12
@pmuruaga i did raised similar enhancement earlier. its same as you requested. I'm also in need of multi price. One Item can have multiple identity in many cases, like input/output tax change, purchase price change, selling price change or change in size/qtty. In short this all relates to different version of same product (With same barcode). This is known as "batch" or "batch code" in accounting/crm systems. 
Some what like this.

![image](https://user-images.githubusercontent.com/994083/30541320-83db95ba-9c98-11e7-92bd-14793a7855de.png)

I guess we need something like this.

**Comment by daN4cat** [comment] 2017-09-28 06:42
Duplicate of #1017

**Closed by daN4cat** 2017-09-28 06:42 UTC
Labels: enhancement, needsowner

**Comment by izeblood** [comment] 2020-02-12 04:03
@daN4cat Is this request solved? @bkrajendra can you share some of your thoughts regarding this matter based on your presentation....

**Comment by daN4cat** [comment] 2020-02-12 05:35
No it's not implemented and this is a duplicate. Please leave a comment on the other issue.
