### ISSUE TITLE
Item Kit

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2414] opened 2019-03-26 00:11 UTC
The item kit has not received much attention. for example, it does not allow to put a single price to the kit. It only has a discount. also when adding the kit to the shopping cart, the kit disappears and only the items that make up the kit remain.

**Comment by SteveIreland** [comment] 2019-03-26 00:36
The kit is like a swiss knife.  It has several blades that  you can use or not.  The "problems" you are reporting are not problems but simply one or two variations of how it can be used.

If you want a price associated with the kit then you need to take it to the next level and create a kit item so that you actually have an item record that represents the kit.  The 'kit" definition then simply describes how the kit item is built.  But the price for the kit properly resides on item table.

**Comment by mckaygerhard** [comment] 2019-11-02 22:00
seems @andriux1990 the #2512 has the same feature request .. usage of a kit as a product right? hey @Hamzaqureshi401 maybe we can make some modifications .. now are 3 people wanted this!

**Comment by Hamzaqureshi401** [comment] 2019-11-03 03:39
Yes it should be developed i recently paid for item kit task and im using it now but the problem is i made modifications in ospos 3.3.0 mistakenly but i want it in latest ospos
![Screenshot_20191103-083811](https://user-images.githubusercontent.com/46222436/68080039-5d06b600-fe15-11e9-8076-2a829f9d4cfe.jpg) 
The items in the last im using as a kit

**Comment by Hamzaqureshi401** [comment] 2019-11-03 03:40
If u want some help i can do that thanks!

**Comment by mckaygerhard** [comment] 2019-11-06 03:09
@Hamzaqureshi401 i dont understand, you made it or not? i mean.. you already have that working (a kit as a special produc that contains others but showed and threated as new product??) ???

i dont understand the picture... can you elaborate it]]? and of course i want some help.. OR if you already have it and want to adapt to newer version .. i can made it! for free, show me your code and i'll adapt.. as i does in many wasy for ospos.. also i can makde some documetnation to the wiki too, (the wiki are structure by me)

**Comment by andriux1990** [comment] 2019-11-06 05:28
Hello @Hamzaqureshi401 you have modified the article kit, I have been trying to do this for a couple of weeks and I have not succeeded. I want to put a fixed price on each kit (since the item kit only adds the prices of your items and allows discounts) and this does not work on certain kits. and the other thing that when I add a kit for sale, it shows all the products that the kit contains. I am trying to show only the name of the kit and represent all the elements that compose it.

But those of ospos do not show importance. It's really ridiculous how the kit currently works. Ospos has for the restaurant tables and suppose you sell a pizza, create a kit that will be the pizza and the loads to the verta, and appear, so many pounds of arrina, pineapple, cheese, etc. And if they are two pizzas. how ridiculous does this currently work

**Comment by andriux1990** [comment] 2019-11-06 05:35
> If u want some help i can do that thanks!

If you can help us I would appreciate it. Thank you

**Comment by WebShells** [comment] 2019-11-06 07:33
@Hamzaqureshi401 modifications that werent done by the team cannot be updated by the team... If you paid for this to any party, please contact the developer back to apply the modifications on the updated release, unless any of contributors/collaborators is planning to apply it officially to the project.

**Comment by daN4cat** [comment] 2019-11-06 12:07
@andriux1990 this project proceed on a voluntary basis. Some of the contributors are interested in a set of features, others in another.
For instance tax module was relevant for @SteveIreland but not for me. We simply have a plain VAT system and that does for me.
And so on with other features like Mailchimp connector I added because useful for me.

I don't use items kit therefore I have no time to dedicate to it.

Open for owners and contributors to move it to the next level.

**Comment by SteveIreland** [comment] 2019-11-06 15:06
The item kit system is designed to handle different scenarios.  You break it you own it.  :-)  

You CAN assign a price to a kit, but because of the way pricing works in OSPOS it is necessary to create an item  (an "item kit") that represents the kit and to assign the price to that item.  The price from the "item kit"will be used for pricing the kit.

**Comment by mckaygerhard** [comment] 2019-11-06 19:56
hey i tryied and seems item kid ARE very broken.. please @SteveIreland  and @daN4cat take care of my explanations:

I have defined three item products into the item module:
1) id 1 item product "a" type item
2) id 2 item product "b" type item kit
3) id 3 product 'c' type item

Later defined a item kit id 5 into the item kit module and asociated the item id 2, but:

The behavior of the item kit for prices and presentations works well for opensourcepos 3.2.2 but in the last version there is no possibility to associate the item kit( the kit id 5) with a product type item (the item id 2)... so the pricing system does not work... 

secondly the inventory is not reduced... I have seen that very old versions reduce the inventory (or I'm confusing it with the phppos that if it does well)

**Comment by mckaygerhard** [comment] 2019-11-06 20:26
> The Inventory is not reduced unless it is displayed at the Register.

doe snto work! of course i complete the sale!

**Comment by adga137** [comment] 2019-11-06 20:28
I've done an installation I apologize, hello to everyone and I think something is wrong, because I do not see that reduces the inventory ..

**Comment by odiea** [comment] 2019-11-06 20:41
I cannot duplicate your issue. The following is beginning Inventory.
![2019-11-06 13_36_27-Window](https://user-images.githubusercontent.com/10962177/68336027-c519fe00-009a-11ea-97dd-6ffba9abfa1d.png)
This is the kit Sale.
![2019-11-06 13_37_01-Window](https://user-images.githubusercontent.com/10962177/68336098-ebd83480-009a-11ea-990b-746dda4a87fc.png)
The New Inventory for Garmin gps. The Inventory was reduced by 1.
![2019-11-06 13_37_38-Window](https://user-images.githubusercontent.com/10962177/68336138-03afb880-009b-11ea-8709-838a6c7a12d0.png)

**Comment by mckaygerhard** [comment] 2019-11-06 21:09
hi @odiea  you defined for printing "only kit" and for price "only kit" ? in the asociated kit item (not in kit itselft ) ? seem not? please describe your way to try to understand!

there's a language barrier here.. and please we MUST consider that of course are a open source project but things must be elabotated to propoerty understand!

**i could write documentation to wiki for end users!**

**Comment by odiea** [comment] 2019-11-06 21:11
The Inventory is not reduced unless it is displayed at the Register as my image shows. If it is just a kit id with no items displayed the magic for that has not been implemented.

**Comment by WebShells** [comment] 2019-11-06 21:54
> there's a language barrier here.. and please we MUST consider that of course are a open source project but things must be elabotated to propoerty understand!
> 
> **i could write documentation to wiki for end users!** REmenber i build the current wiki mayor pages!

Brace yourself *end users* 🤠Documentations are coming 😎

**Comment by SteveIreland** [comment] 2019-11-06 23:39
I'm not going to respond to the other noise on this ticket, but if there is a bug with item kit pricing then I'm happy to test and fix it - but only pure, unadulterated OSPOS.

**Comment by mckaygerhard** [comment] 2019-11-06 23:57
@odiea seem your screens shotw are not in sync.. i'll show you @SteveIreland  thanks to TAKE SEROUS right @WebShells ?

 At that time the available item types were either "standard item", "item kit". Subsequent to this we added support for 'items that allow entry by dollar amount' and 'temporary items'.

so the if you (as can see it in the image) configure as kit and show all the items.. and that are nto the only behaviour (i means.. @odiea  only show working things)

but in the second shot.. you can note i cannot choose the item as kit.. and in the older version (where i can) the stock are not affected!

are clear that a REAL team help among .. and here only i can se are "that's not my problem" maybe brave people must folk the project adn just use us!

![Captura de pantalla de 2019-11-06 19-34-48](https://user-images.githubusercontent.com/1571724/68347610-eba55c80-00cd-11ea-8036-ef119e1b06fc.png)

![Captura de pantalla de 2019-11-06 19-34-49](https://user-images.githubusercontent.com/1571724/68348126-789ce580-00cf-11ea-9757-87310e115a7d.png)

**Comment by odiea** [comment] 2019-11-07 00:30
@mckaygerhard  Instead of bitching about a module next time show how you expect it to work so we do not waste our time trying to read your mind.

**Comment by andriux1990** [comment] 2019-11-07 04:28
@jekkos  @SteveIreland  @daN4cat @odiea @WebShells Etc.
I really don't know why they don't understand the definition of an item kit.  but I will tell them.

Definition of Item Kit
Item kits are simply a group of items that you sell as one package. A good examples would be a gift basket which contains multiple items. When an item kit is sold all the items in the kit are deducted from inventory. ... If you do set the price the kit will only show one line item in the sale.

At first I opened this topic with the intention of encouraging it to improve it. But the main developers are not interested in the item kit because they don't use it, and I think nobody uses it, the reason why nobody uses it is also that the kit item doesn't do what a real kit does, Because the Ospos kit item is not finished.

What does the item kit need? Simply 2 things.
First, that you can put a fixed price on this, I mean, put a higher price than the sum of all kit members.

Second: that when the kit is loaded for sale (shopping cart), this is in a single line, which shows the name of the kit and its price. NOT HOW IT DOES CURRENTLY, which shows all kit members, as exemplified above in the images.

If this is achieved, I assure you that everyone will use it and be happy and play with the item kit for the magic it will do.

That is why I am trying to make this possible in Ospos, but I am not a programmer, I have tried all this time and I have not succeeded. But when I manage to do it, I will share the code with ospos.

If anyone wants to join Ospos, to improve and leave the item kit as it should be, I would greatly appreciate it.

Thank you

**Comment by daN4cat** [comment] 2019-11-07 06:55
@andriux1990 please remove my name because as I said I don't use it and have no interest in developing it.

**Comment by Hamzaqureshi401** [comment] 2019-11-07 10:11
> @Hamzaqureshi401 i dont understand, you made it or not? i mean.. you already have that working (a kit as a special produc that contains others but showed and threated as new product??) ???
> 
> i dont understand the picture... can you elaborate it]]? and of course i want some help.. OR if you already have it and want to adapt to newer version .. i can made it! for free, show me your code and i'll adapt.. as i does in many wasy for ospos.. also i can makde some documetnation to the wiki too, (the wiki are structure by me)

Yes i already have that working ill give you the please w8 just for few days ill give u the code

**Comment by Hamzaqureshi401** [comment] 2019-11-07 10:16
> Hello @Hamzaqureshi401 you have modified the article kit, I have been trying to do this for a couple of weeks and I have not succeeded. I want to put a fixed price on each kit (since the item kit only adds the prices of your items and allows discounts) and this does not work on certain kits. and the other thing that when I add a kit for sale, it shows all the products that the kit contains. I am trying to show only the name of the kit and represent all the elements that compose it.
> 
> But those of ospos do not show importance. It's really ridiculous how the kit currently works. Ospos has for the restaurant tables and suppose you sell a pizza, create a kit that will be the pizza and the loads to the verta, and appear, so many pounds of arrina, pineapple, cheese, etc. And if they are two pizzas. how ridiculous does this currently work

Yes i have made some changes in the kit it will behave as special product ill give you the access of my pos so that you can understand how my kit behaviour works but plz give me 5days im busy thanks!

**Comment by Hamzaqureshi401** [comment] 2019-11-07 11:57
> @Hamzaqureshi401 i dont understand, you made it or not? i mean.. you already have that working (a kit as a special produc that contains others but showed and threated as new product??) ???
> 
> i dont understand the picture... can you elaborate it]]? and of course i want some help.. OR if you already have it and want to adapt to newer version .. i can made it! for free, show me your code and i'll adapt.. as i does in many wasy for ospos.. also i can makde some documetnation to the wiki too, (the wiki are structure by me)
pos1.scoopscreamery.org
EMAIL : admin 
Password : pointofsale 
For download 
Scoopscreamery.org/pos.zip

**Comment by Hamzaqureshi401** [comment] 2019-11-07 11:58
> Hello @Hamzaqureshi401 you have modified the article kit, I have been trying to do this for a couple of weeks and I have not succeeded. I want to put a fixed price on each kit (since the item kit only adds the prices of your items and allows discounts) and this does not work on certain kits. and the other thing that when I add a kit for sale, it shows all the products that the kit contains. I am trying to show only the name of the kit and represent all the elements that compose it.
> 
> But those of ospos do not show importance. It's really ridiculous how the kit currently works. Ospos has for the restaurant tables and suppose you sell a pizza, create a kit that will be the pizza and the loads to the verta, and appear, so many pounds of arrina, pineapple, cheese, etc. And if they are two pizzas. how ridiculous does this currently work

pos1.scoopscreamery.org
EMAIL : admin
Password : pointofsale

**Comment by Hamzaqureshi401** [comment] 2019-11-07 12:00
> The item kit system is designed to handle different scenarios. You break it you own it. :-)
> 
> You CAN assign a price to a kit, but because of the way pricing works in OSPOS it is necessary to create an item (an "item kit") that represents the kit and to assign the price to that item. The price from the "item kit"will be used for pricing the kit.

pos1.scoopscreamery.org
EMAIL : admin
Password : pointofsale
For download 
Scoopscreamery.org/pos.zip
Pls check my item kit

**Comment by mckaygerhard** [comment] 2019-11-07 12:14
ok @Hamzaqureshi401 many many thanks.. i'll try to integrate to current 3.3.1 (not 3.3.0) and provide a branch that other can used as goood contribution.. not only parse problems like others

**Comment by mckaygerhard** [comment] 2019-11-07 12:20
> Yes i have made some changes in the kit it will behave as special product ill give you the access of my pos so that you can understand how my kit behaviour works but plz give me 5days im busy thanks!

i'm very busy too.. still i dont understand your implementatin of kit but as i promise integrate with current i can deduce it.. to make more personal.. please fork this repo in your github to do not perturb the issue status until we have someting

**Comment by Hamzaqureshi401** [comment] 2019-11-07 12:37
> ok @Hamzaqureshi401 many many thanks.. i'll try to integrate to current 3.3.1 (not 3.3.0) and provide a branch that other can used as goood contribution.. not only parse problems like others

After the development i tried to upgrade into the latest but i seen the general function has been changed so i quit it in this development u ill see show item in cart yes or no features it is important for item kit i also developed employees attandence sistem in it in employ module for further details contact hamzaqureshi401@gmail.com or +923314266560 (watsapp)

**Comment by mckaygerhard** [comment] 2019-11-07 12:40
> > ok @Hamzaqureshi401 many many thanks.. i'll try to integrate to current 3.3.1 (not 3.3.0) and provide a branch that other can used as goood contribution.. not only parse problems like others
> 
> After the development i tried to upgrade into the latest but i seen the general function has been changed so i quit it in this development u ill see show item in cart yes or no features it is important for item kit i also developed employees attandence sistem in it in employ module for further details contact [hamzaqureshi401@gmail.com](mailto:hamzaqureshi401@gmail.com) or +923314266560 (watsapp)

i dont use watsah.. use telegram.. so i'll  contsat you by gmail.. please remove messages about your mail and about your domiain ospos test .. due are sensible data here @Hamzaqureshi401 please!

**Comment by Hamzaqureshi401** [comment] 2019-11-07 12:45
Ok im busy now tomorrow ill delete it from domain

**Comment by SteveIreland** [comment] 2019-11-11 02:10
Closing this issue again.  I tested the item kit pricing and it works fine.

**Closed** 2020-01-04 10:49 UTC
