### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by debpedrano** [opensourcepos/opensourcepos#2058] opened 2018-07-21 13:28 UTC
Hello , it would be nice to have a logo or a new one for the project. I can also add a ReadMe Banner, hoping for your confirmation and i'll send my design as soon as possible.

**Comment by WebShells** [comment] 2018-07-21 13:36
Thats a duplicate of #2026 please follow up there... This issue will be closed...

**Closed by WebShells** 2018-07-21 13:36 UTC
Labels: duplicate

**Comment by jekkos** [comment] 2018-07-21 15:06
@debpedrano feel free to submit another logo in #2026
