### ISSUE TITLE
Mutiple POS Setup

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1670] opened 2017-10-09 05:01 UTC
Is there any way to sync items table when having 2 different databases with same items data and different sales/recv data?

I want to setup 2 POS in my store in which items will be common in both POS but the sales and recv data will be different...

Please suggest me any idea about this kind of situation....

**Comment by daN4cat** [comment] 2017-10-09 08:24
Duplicate of #1664. We discussed but got no answers from you, hence closed.
I'm afraid we cannot keep going on and on....

**Closed by daN4cat** 2017-10-09 08:24 UTC
