### ISSUE TITLE
Items will not create

### ISSUE THREAD

**Issue by philippejd** [opensourcepos/opensourcepos#3298] opened 2021-09-08 03:09 UTC
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: fe7276
- PHP version is: 7.3.29
- MySQL or MariaDB version is: 15.1
- OS and version is: Raspbian GNU/Linux 10 (buster)
- WebServer is: nginx/1.14.2
- Selected language is: English
- (If applicable) Docker installation:
- (If applicable) Installation package for the LAMP/LEMP stack is:

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have tried to narrow down this error, I even re-built the PI from scratch to see if I screwed up a file and same thing. I am unable to create any item using the new item link and I can only get one CSV import before it wont import anything anymore. The only error I get is the following:

![2021-09-07_17-02-48](https://user-images.githubusercontent.com/50808005/132440009-dab5fd13-79e7-446d-8e8b-1cad170c0a12.jpg)

**Comment by odiea** [comment] 2021-09-08 12:31
You will need to enable the error log.

**Comment by MufassalAmeer** [comment] 2021-09-09 17:48
Im also Facing the same issue after entring quantity on product creation

**Comment by odiea** [comment] 2021-09-09 18:01
You will need to enable the error log. Then post it here.

**Comment by chunter2** [comment] 2021-09-09 20:38
My guess is it's the same as this.  https://github.com/opensourcepos/opensourcepos/issues/3295 And @jekkos fixed it with this commit.  https://github.com/opensourcepos/opensourcepos/commit/a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3

**Comment by philippejd** [comment] 2021-09-09 23:54
> My guess is it's the same as this. #3295 And @jekkos fixed it with this commit. [a2e7c0a](https://github.com/opensourcepos/opensourcepos/commit/a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3)

This did fix some of the issues with sorting as I notice that it would not sort any of the columns but now it will. I will have to do some logging tests later but issue still persists. I can create new items as stock level at 0 but when I put an actual stock level in it errors out. I can "revive" the item by going to receiving and then receiving it but until then it will not show up in the items list.

**Comment by chunter2** [comment] 2021-09-10 13:21
Any chance you've tried reproducing the problem at 

https://dev.opensourcepos.org 
login: admin
password: pointofsale

It seems to be running the latest code.

**Comment by odiea** [comment] 2021-09-10 15:00
The Items table appears to accept an update but not a new Item. Following are the error codes.
ERROR - 2021-09-10 08:57:45 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`test4`.`ospos_items_taxes`, CONSTRAINT `ospos_items_taxes_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `ospos_items` (`item_id`) ON DELETE CASCADE) - Invalid query: INSERT INTO `ospos_items_taxes` (`name`, `percent`, `item_id`) VALUES ('City', 3.5, '-1')
ERROR - 2021-09-10 08:57:45 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`test4`.`ospos_items_taxes`, CONSTRAINT `ospos_items_taxes_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `ospos_items` (`item_id`) ON DELETE CASCADE) - Invalid query: INSERT INTO `ospos_items_taxes` (`name`, `percent`, `item_id`) VALUES ('State', 4, '-1')
ERROR - 2021-09-10 08:57:45 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`test4`.`ospos_item_quantities`, CONSTRAINT `ospos_item_quantities_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `ospos_items` (`item_id`)) - Invalid query: INSERT INTO `ospos_item_quantities` (`item_id`, `location_id`, `quantity`) VALUES ('-1', '1', 5)
ERROR - 2021-09-10 08:57:45 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`test4`.`ospos_inventory`, CONSTRAINT `ospos_inventory_ibfk_1` FOREIGN KEY (`trans_items`) REFERENCES `ospos_items` (`item_id`)) - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-09-10 08:57:45', '-1', '1', '1', 'Manual Edit of Quantity', 5)

**Comment by MufassalAmeer** [comment] 2021-09-10 18:58
Hi odiea,

Video :  https://1drv.ms/v/s!AggWmP4kvK2_g4NiU4Rs4IKV4EKCkA?e=qqUcEP

please find the attched video for more information on the issue. adding new product window strck if we add quantity. 

if we create a new product wihout entering quantity then product creation is successful but product is not visible. once we go to receive and add some quantity then we can see the items. pelase check the video which might help understand the issue. than you

**Comment by MufassalAmeer** [comment] 2021-09-10 19:10
Hi ,

Video : https://1drv.ms/v/s!AggWmP4kvK2_g4NiU4Rs4IKV4EKCkA?e=qqUcEP

please find the attched video for more information on the issue. adding new product window strck if we add quantity.

if we create a new product wihout entering quantity then product creation is successful but product is not visible. once we go to receive and add some quantity then we can see the items. pelase check the video which might help understand the issue. than you

**Comment by dmoatz** [comment] 2021-09-11 19:02
I have the same issues can't add new item ?
Pls help me

**Comment by jekkos** [comment] 2021-09-11 22:40
Can you try latest master? a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3 
the issue seems to refer another commit

**Comment by odiea** [comment] 2021-09-11 23:41
It appears to work fine if I replace 3.3.5 items controller with that from 3.3.3. Maybe something with this NEW_ITEM?

**Comment by MufassalAmeer** [comment] 2021-09-12 03:34
> Can you try latest master? [a2e7c0a](https://github.com/opensourcepos/opensourcepos/commit/a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3)
> the issue seems to refer another commit

Tried this also Still facing the same issue.

**Comment by MufassalAmeer** [comment] 2021-09-12 03:52
> It appears to work fine if I replace 3.3.5 items controller with that from 3.3.3. Maybe something with this NEW_ITEM?

Thank you. just tried this and it works.

**Comment by jekkos** [comment] 2021-09-12 06:52
Ok great news.

**Comment by jekkos** [comment] 2021-09-12 07:29
I think it could be due to the change from double equals to triple equals. My theory is that the item_id is coming in as a string and we are comparing it with an int. In this case '-1' probably isn't equal to -1.

@objecttothis is this something you could check on your side?

**Comment by objecttothis** [comment] 2021-09-12 07:38
I'll be able to look at it on Tuesday.

**Comment by daN4cat** [comment] 2021-09-12 09:12
@jekkos I don't think what you reverted has anything to do with this. It's just adding sorting options, you can reinstate that.

**Comment by jekkos** [comment] 2021-09-12 10:27
I guess the problem is that master is never really tested until we release something..

**Comment by odiea** [comment] 2021-09-12 10:46
So I changed the Items controller and removed the 3rd = sign and it does load properly but I still get the following error but the tables now show. How would this be defined in constants?
ERROR - 2021-09-12 06:39:59 --> Severity: Warning --> Use of undefined constant NAME - assumed 'NAME' (this will throw an Error in a future version of PHP) C:\wamp64\www\master335\application\controllers\Items.php 43

**Comment by objecttothis** [comment] 2021-09-12 10:59
> I guess the problem is that master is never really tested until we release something..

Getting unit tests setup for applicable functions will reduce some of this, but I wonder if also making releases beta before production will catch some of it as well. It may very well be that one or more of the === is the problem and my regression testing missed it. I'll pinpoint it and submit the fix on Tuesday before I start working on the CI4 conversion.

**Comment by jekkos** [comment] 2021-09-12 15:50
@odiea are you sure you have latest Items.php controller? I can't find this constant nowhere in Items.php file. It's not defined in constants.php either.

**Comment by odiea** [comment] 2021-09-12 16:12
The NAME was from the download before your last commit to fix it.

**Comment by jekkos** [comment] 2021-09-12 16:18
Ah ok indeed, I think this constant should be removed in latest master

**Comment by odiea** [comment] 2021-09-12 16:19
Yes it should be. But for some reason it has not been put into the current available downloads.

**Comment by jekkos** [comment] 2021-09-12 16:23
Ok I can replace the download already

**Comment by jekkos** [comment] 2021-09-12 16:38
So but we also need to apply your change of top of this then @odiea , thar might be the fix?

**Comment by objecttothis** [comment] 2021-09-12 16:47
> 
> 
> So but we also need to apply your change of top of this then @odiea , that might be the fix?

Please do not completely replace the items controller with the previous one in the master.  I made a lot of changes in that controller and it will break those (CSV import) if they are just reverted.  It sounds like @odiea has a workaround that will tide him over until I can find the exact line of code that is causing the issue and change just that.

**Comment by odiea** [comment] 2021-09-12 16:52
@objecttothis I don't think any one really takes my changes seriously. Thanks for all the work you are doing.

**Comment by objecttothis** [comment] 2021-09-12 17:10
> @objecttothis I don't think any one really takes my changes seriously. Thanks for all the work you are doing.

Your changes and testing are helpful because it not only narrows down the offending file but helps identify the likely problem... I was just not wanting the baby thrown out with the bathwater 😉

**Comment by jekkos** [comment] 2021-09-12 17:41
> > So but we also need to apply your change of top of this then @odiea , that might be the fix?
> 
> Please do not completely replace the items controller with the previous one in the master. I made a lot of changes in that controller and it will break those (CSV import) if they are just reverted. It sounds like @odiea has a workaround that will tide him over until I can find the exact line of code that is causing the issue and change just that.

Yes it sounded like @odiea was pretty close to fixing the issue. I can't really look into it any further now as I'm on a limited cellular connection...

**Comment by objecttothis** [comment] 2021-09-12 17:48
> 
> 
> > > So but we also need to apply your change of top of this then @odiea , that might be the fix?
> > 
> > 
> > Please do not completely replace the items controller with the previous one in the master. I made a lot of changes in that controller and it will break those (CSV import) if they are just reverted. It sounds like @odiea has a workaround that will tide him over until I can find the exact line of code that is causing the issue and change just that.
> 
> Yes it sounded like @odiea was pretty close to fixing the issue. I can't really look into it any further now as I'm on a limited cellular connection...

OK, sounds good.  @odiea if you are able to identify the specific line or lines of code that are causing the issue you can submit a PR and I'll review it... Otherwise you can post what you think the issue is and on Tuesday I'll make the changes and we can test it.

**Comment by odiea** [comment] 2021-09-13 11:38
Line 569 appears to be the culprit. Got rid of 1 of the + signs and I have no issues now with adding a new Item.
```
if($item_id == NEW_ITEM)
			{
				$item_id = $item_data['item_id'];
				$new_item = TRUE;
			}
```

**Comment by objecttothis** [comment] 2021-09-13 12:24
> 
> 
> Line 569 appears to be the culprit. Got rid of 1 of the + signs and I have no issues now with adding a new Item.
> 
> ```
> if($item_id == NEW_ITEM)
> 			{
> 				$item_id = $item_data['item_id'];
> 				$new_item = TRUE;
> 			}
> ```

Good work @odiea .  The solution here is either to cast the item_id to an int and keep the type-specific operator `if((int)$item_id === NEW_ITEM)` or remove the type-checking operator like you've done.  PHP is moving toward Strongly/Strictly typed, but it will probably never be Strongly typed.  There is a lot of flexibility afforded by weak typing, but bugs can also be introduced by the flexibility too.  

IMO, unit tests can be more complicated.  That said, I introduced the `===` in my changes for speed of execution since large CSV files with thousands of lines to import/update were needing all the help they could get.  I was not trying to make PHP something it isn't, so I don't mind changing it back in places where the type flexibility is needed, but it will come at a slight performance hit.

@odiea do you know how to submit a PR?  If you don't have access to an IDE, you should be able to edit the file right in Github or Github Desktop, then create a commit in a new branch and submit that branch as a Pull Request.  If not, I will do it tomorrow morning when I'm working on OSPOS stuff.

**Comment by objecttothis** [comment] 2021-09-13 12:32
Also === is consider more secure than ==, so should be used when possible.  https://stackoverflow.com/questions/80646/how-do-the-php-equality-double-equals-and-identity-triple-equals-comp#80649

**Comment by odiea** [comment] 2021-09-13 12:45
I will let you handle it. Thanks

**Comment by objecttothis** [comment] 2021-09-13 12:59
Sounds good.  I'm on it in the morning.

**Comment by jekkos** [comment] 2021-09-13 16:31
> Line 569 appears to be the culprit. Got rid of 1 of the + signs and I have no issues now with adding a new Item.
> 
> ```
> if($item_id == NEW_ITEM)
> 			{
> 				$item_id = $item_data['item_id'];
> 				$new_item = TRUE;
> 			}
> ```

Great work thanks @odiea

**Comment by dmoatz** [comment] 2021-09-13 20:24
Very good work
Bug in 569 in items
Remove === to == 
Solve bug very lot tnks

**Comment by objecttothis** [comment] 2021-09-14 05:38
OK, if someone can approve #3302 then we can merge it with the master.  I've created a 3.3.6 milestone as well.

**Closed** 2021-09-14 06:47 UTC
Labels: bug
