### ISSUE TITLE
Small Error in the OSPOS

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2108] opened 2018-08-29 12:15 UTC
Hello

I don't know if it is error or not

in Controllers/Sale.php

`$data['employee'] = $employee_info->first_name . ' ' . $employee_info->last_name[0];`
 
It turn first later from last name; which is not good for non-English language. It show ? mark

`		$data['employee'] = $employee_info->first_name . ' ' . $employee_info->last_name;
`

**Comment by SteveIreland** [comment] 2018-08-29 13:32
Nice catch ... mine.

**Comment by odiea** [comment] 2018-08-29 14:32
Issue #2069 explains a lot of the reasoning behind this.

**Comment by SteveIreland** [comment] 2018-08-29 15:11
@odiea Thanks for bringing that to my attention but I'm not yet sure that it is the same issue.  I was looking through commit history and it appears that this (bug or not bug) was introduced by me back in late 2016.   I'm not sure why I made the code change (surely I had a good reason?) so I was going to give it a little testing tonight to see if I can recall why.

**Comment by odiea** [comment] 2018-08-29 15:23
Here is where it was originally changed. Issue  #1027. I do not see any difference in the code since then.

**Comment by odiea** [comment] 2018-08-29 15:28
@SteveIreland Thanks. It's great that you are going to deal with this issue.

**Comment by SteveIreland** [comment] 2018-08-29 16:29
I’m now leaning toward checking the first character for alpha and if not then printing 2 the first two characters of the last name

**Comment by w002qaa** [comment] 2018-08-29 16:57
Thanks @odiea for the explanation, that why I said early 

> I don't know if it is error or not

Dear @SteveIreland, when the name in English is fine and show the first character of last name. Where in Arabic it print question mark character like in the screen shot

[https://ibb.co/mLdZV9](url)

**Comment by SteveIreland** [comment] 2018-08-29 20:26
I see ... not quite how I interpreted the original post.  :-)

my first experience with multi-byte character strings.  it seems to need to be

`$data['employee'] = $employee_info->first_name . ' ' . mb_substr($employee_info->last_name, 0, 1);`

I'll make that change tonight in my development environment to make sure it works in my environment.  I've never used it before but the function is described  here ... http://php.net/manual/en/function.mb-substr.php.

I don't know what release you running under, but you can manually make the change on your system and you should be good to go.  Yes, I am always overly optimistic.

**Comment by daN4cat** [comment] 2018-08-29 21:53
Looks the right solution Steve.

**Comment by odiea** [comment] 2018-08-30 00:06
Application/Controllers/Sales.php
        Replace line 516 for " original receipt" and line 936 for "reprint receipt"
	$data['employee'] = $employee_info->first_name . ' ' . mb_substr($employee_info->last_name, 0, 1);

**Comment by SteveIreland** [comment] 2018-08-30 01:58
I can confirm it doesn't break anything in none-double byte character environments.  As @odiea points out there are two places in Sales.php where this correction needs to be applied.  The actual line numbers will depend on the version of the system  you are running, but they should be pretty close to the lines 516 and 936 mentioned earlier.

The correction will be included in the India GST pull request.  I don't think it's worth the effort to do a special pull request just for this since the manual fix is so simple.  But maybe it can be included in one if the current four pull requests?

**Comment by w002qaa** [comment] 2018-08-30 06:16
Thanks @SteveIreland and @odiea

Now, it is working in the right way :)

**Comment by jekkos** [comment] 2018-08-30 12:51
@SteveIreland You can push small (tested) fixes like this directly to master, might be more convenient..

**Comment by SteveIreland** [comment] 2018-09-06 12:46
Sorry @jekkos, for some reason I missed your comment a few days ago otherwise I would have applied the fix myself.

**Closed** 2018-09-26 02:52 UTC
Labels: bug
